### ISSUE TITLE
Using secrets.yaml file

### ISSUE THREAD

**Issue by timvancann** [home-assistant/appdaemon#106]
I intend to store my configuration for appdaemon in a repository, just like with the homeassistant configuration.

For home assistant I can create a `secrets.yaml` file (described [here](https://home-assistant.io/docs/configuration/secrets/)) so that I can ignore it in the `.gitignore` and not have my passwords lying around the repo.

I can't seem to find such a solution for the `appdeamon.yaml` file. Is there a way to exclude passwords from that file?

**Comment by acockburn** [comment]
NOt currently but its on my to do list for a future release.
