### ISSUE TITLE
Addon not accepted by Hassio

### ISSUE THREAD

**Issue by Amir974** [home-assistant/appdaemon#110]
log errors:

```
17-08-08 16:28:16 ERROR (MainThread) [hassio.addons.git] Can't clone https://github.com/vkorn/hassio-addons/tree/master/appdaemon repo: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/vkorn/hassio-addons/tree/master/appdaemon /data/addons/git/4db42e04
  stderr: 'Cloning into '/data/addons/git/4db42e04'...
remote: Not Found
fatal: repository 'https://github.com/vkorn/hassio-addons/tree/master/appdaemon/' not found
```

**Comment by acockburn** [comment]
Hi there -

I"m afraid I don't control the hass.io support for AppDaemon, the repository belongs to forum user vkorn - it would make more sense to raise the issue against his repository. If he needs help with a fix I will do so, but I can't fix this, only he can.

**Comment by Amir974** [comment]
I got an answer from him, maybe you should update the instructions to point to the repo root that he has created rather then the addon inside - which is not taken...

**Comment by acockburn** [comment]
Thanks for reporting back - I'll make that change.
