### ISSUE TITLE
Secret warning

### ISSUE THREAD

**Issue by HydrelioxGitHub** [home-assistant/appdaemon#117]
I've tried to put my HA frontend password but I've got some warning in the log

`
2017-08-19 23:26:56.009856 INFO /home/julien/.homeassistant/appdaemon.yaml modified
2017-08-19 23:26:56.073335 WARNING parser says
2017-08-19 23:26:56.074868 WARNING   in "<unicode string>", line 9, column 12:  ha_key:  !secret HTTP_PASSWORD
           ^
2017-08-19 23:26:56.075534 WARNING could not determine a constructor for the tag '!secret'
2017-08-19 23:26:56.076492 WARNING New config not applied
`
The appdaemon.yaml and the secrets.yaml are in the same directory.

**Comment by acockburn** [comment]
What version of PpFaemon are you running?

**Comment by HydrelioxGitHub** [comment]
julien@raspberrypi2 ~/.homeassistant $ sudo pip3 show appdaemon
Name: appdaemon
Version: 2.0.8

**Comment by acockburn** [comment]
Secret support wasn't added until version 2.1.0 - upgrade to the latest and you should b good to go!

**Comment by HydrelioxGitHub** [comment]
I have an error trying to update using pip3
`Failed building wheel for bcrypt` 
`Failed cleaning build dir for bcrypt`

These are the main message of the error (one page of error log throw out)

And thank you for your help.

**Comment by Cecron** [comment]
bcrypt compiled for me (RPi, python 3.4) after doing
`$ sudo apt-get install libffi-dev`

**Comment by HydrelioxGitHub** [comment]
Thank you @Cecron , with this install the update of appdaemon goes well. And then the secrect goes well also.

Thank you @acockburn  also.
