### ISSUE TITLE
Methods that call services, etc. seem to hang Alexa

### ISSUE THREAD

**Issue by bachya** [home-assistant/appdaemon#120]
I have a basic Alexa app in play (similar to what's in the docs). I'm experiencing a problem with an intent designed to turn on a scene:

```Python
def lock_up_intent(self, data):
    """Defines a handler for the LockUpIntent intent."""
    self.turn_on('scene.good_night')
    speech = random.choice(const.AFFIRMATIVE_RESPONSES)

    return speech, speech, 'Lock Up the House'
```

The scene activates, but after several seconds, Alexa responds with, "The requested skill took too long to respond."

Is there something with service calls, "turn-ons," etc. that needs to be asyncio-adjusted?

**Comment by acockburn** [comment]
It shouldn't be necessary- I have a skill that locks my door and it works fine. You get about 5 -7 seconds before Alexa times out, but there doesn't look to be anything in your code that would cause that. Is the scene activation fairly quick or does it take a while?

**Comment by acockburn** [comment]
I can look at adding that but you can roll your own by kicking off a thread to run the scene then immediately returning the response.

**Comment by bachya** [comment]
Is there any way to hook into your existing asyncio event loop?

**Comment by acockburn** [comment]
Not from in an App no, they are sanboxed and have their own worker threads so they are executing outside of the loop to avoid rogue code holding up the whole of AppDaemon (and potentially HASS when I integrate it).

**Comment by bachya** [comment]
Got it. Thank you for taking a look!

**Comment by acockburn** [comment]
Funnily enough this just came up again - I think I might look into adding async support for power users but probably not until everyone is on python 3.5+
