### ISSUE TITLE
Return to page using skin argument

### ISSUE THREAD

**Issue by Darbos** [home-assistant/appdaemon#128]
Trying to use a front page with a certain background image and then once a new navigate page is tapped goto the new page with a new skin.  Then after a period of time be redirected back to the original front page with the original skin called.  This is to get around the only one background image restriction per skin.  

Everything works as expected until the timeout hits on the new page we navigated to and it is time to go back to the original page with the original skin.  I am redirected back to the page but when specifying the original skin it does not create a valid url and fails to load.

**Comment by acockburn** [comment]
Yes, I've seen this too - I'll see about a fix.

**Comment by acockburn** [comment]
If this is still an issue for you can you let me know how you are configuring the widget?

**Comment by acockburn** [comment]
Closing - no response. Happy to re-open if you can give me the requested information.
