### ISSUE TITLE
Request for non-existent domain or service in a call_service to throw an exception.

### ISSUE THREAD

**Issue by Justihar** [home-assistant/appdaemon#1347]
Currently, if a service_call that doesn't exist is called, a WARNING is displayed in logs saying "Unknown domain".

This request is to raise an exception if the domain or the service doesn't exist and specify in the exception if the domain doesn't exist or if it does, specify that the service doesn't exist.

Thank you!

**Comment by ReneTode** [comment]
this is just about the way its logged, not a fix.
1256 and 977 is a problem caused by HA.

those problems probably will never be completely solved.
best practise: never restart HA, without also restarting AD.
