### ISSUE TITLE
notify() doc correction

### ISSUE THREAD

**Issue by bachya** [home-assistant/appdaemon#140]
The official docs say that the `title` attribute of the `self.notify()` function is optional; however, whenever I _don't_ include a title, the message fails to send (with no errors in the logs). Assuming this isn't representative of some other issue, the docs should be updated to reflect this.

**Comment by acockburn** [comment]
Thanks - I'll take a look. I made a change to notify at some point and this probably got missed.

**Comment by acockburn** [comment]
I was unable to reproduce this. If it still occurs in 3.0 let me know.
