### ISSUE TITLE
homeassistant.appapi vs appdaemon.appapi

### ISSUE THREAD

**Issue by n8henrie** [home-assistant/appdaemon#141]
I'm getting an import error with `import homeassistant.appapi`, and I don't see that module in the HA source, but documentation in both https://github.com/home-assistant/appdaemon and https://github.com/home-assistant/home-assistant.github.io refers to `homeassistant.appapi` at least once. I'm wondering if this is an error and references to `homeassistant.appapi` should actually be to `appdaemon.appapi`.

Because both repos contain at least one reference in question, I'm starting (identical) issues in both repos: 
- https://github.com/home-assistant/appdaemon/issues/141
- https://github.com/home-assistant/home-assistant.github.io/issues/3407

Should be a simple fix, but before I make a PR I wanted to make sure this wasn't intentional, i.e. preparation for an upcoming merge of appdaemon into HA (to avoid having to do separate installs) or something. Searching existing issues for `homeassistant.appapi` doesn't yield any results.

**Comment by acockburn** [comment]
It's probably a typo - the correct import is currently:

```python
import appdaemon.appapi as appapi
```

Although this may soon change for the upcoming merge you mention, that is not currently the case, and I'll document it as a breaking change when it happens.

**Comment by acockburn** [comment]
I fixed the ones I could find, Should be live on the hass website shortly, and in the AppDaemon docs in the next release.
