### ISSUE TITLE
Documentation for callback format has gone missing

### ISSUE THREAD

**Issue by gpbenton** [home-assistant/appdaemon#149]
There used to be documentation about the format of callbacks (state callbacks and schedule callback) in the api documentation,  but I can no longer find either of them.

There are references to both in the api sections, just not anything to say how to write the callback.

Unless of course, I'm searching for the wrong thing, but if so, it just isn't easy to find.  Maybe a link to it in the documentation?

**Comment by mmmmmtasty** [comment]
I think you are after the following:

http://appdaemon.readthedocs.io/en/latest/APIREFERENCE.html#listen-state
http://appdaemon.readthedocs.io/en/latest/APIREFERENCE.html#listen-event
http://appdaemon.readthedocs.io/en/latest/APIREFERENCE.html#scheduler-calls

**Comment by mmmmmtasty** [comment]
As far as the layout of the documentation goes, I didn't write it but it actually seems like it is pretty well organised how it is with the distinction between scheduling calls/event based calls etc

**Comment by gpbenton** [comment]
No, those are the functions that define when to call the callbacks.  What I need is the format of the callbacks themselves.

**Comment by acockburn** [comment]
It’s still there, in the section above the reference. I split it out and intended to link back to the callback format but haven’t got to that point yet.

**Comment by mmmmmtasty** [comment]
Ah I see - this bit?

http://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#state-callbacks

**Comment by acockburn** [comment]
Thanks for linking - I’m on a plane at the moment ;)

**Comment by gpbenton** [comment]
That's it.  The trouble is, that is on a different page from the api docs which I have open when I'm writing an app, so its rather hard to find, especially when the api reference says it is 'above'.  

Perhaps you can add a link from the api reference page to the definition?

**Comment by gpbenton** [comment]
Is the new documentation that fixes this in the pipeline?  The current website still says

> Function to be invoked when the requested state change occurs. It must conform to the standard State Callback format documented above.

When `above` should actually be a link to section you moved.

**Comment by acockburn** [comment]
It is planned for 3.0 so is not in the main docs yet. I just pushed it to the dev branch of the docs if you want to take a look.
