### ISSUE TITLE
Moving docs to home-assistant.io

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/appdaemon#15]
Hi @acockburn,

We are about to add a new section to home-assistant.io titled "Ecosystem". It's a place where any external tools can share their documentation in an official and easy to reference capacity. I think that appdaemon would be a great fit. The PR to add this section should be merged tonight or tomorrow and docs can start being written shortly thereafter. I don't think you would need to do anything more than taking the existing README.md and splitting it up into pages for easy linking. 

Obviously you don't have to do this but we thought we'd let you know.

We could also potentially take this opportunity to move appdaemon into the home-assistant organization if you wanted.

The PR that needs to be merged is [here](https://github.com/home-assistant/home-assistant.github.io/pull/1312).

Thanks!

**Comment by acockburn** [comment]
Hi there - cool, I am very happy to own the docs piece of this. Also moving AppDaemon under HomeAssistant is fine with me - let me know how you want to coordinate that.

**Comment by robbiet480** [comment]
@acockburn I'll be around for a couple more hours tonight, can you hop on [Gitter](https://gitter.im/robbiet480) at some point and private message me so we can coordinate the transfer in real time?

**Comment by robbiet480** [comment]
PR is merged, add docs whenever
