### ISSUE TITLE
Add extra repository for additional python packages

### ISSUE THREAD

**Issue by nixiam** [home-assistant/appdaemon#1629]
Hello,
thanks for your project.

I'm trying to add **tflite_runtime** as additional python package but it's not in the [wheels.home-assistant.io/musllinux](url) search repositories.

How can I add a new external repo like this ? [https://google-coral.github.io/py-repo/tflite-runtime/](url)

Thanks

**Comment by mion00** [comment]
Hi. To help you I would need some more information from your setup.
- How are you running AppDaemon? As a Python package in a venv or using Docker?
- How does the official `tfilte` documentation recommends the installation of the packag be done?
