### ISSUE TITLE
Defining a sub_entity in relation to an entity in a widget

### ISSUE THREAD

**Issue by mmmmmtasty** [home-assistant/appdaemon#163]
So I want to write a widget which will, for example, use the basedisplay widget. I want to ask the user to define a single entity. I then want the sub_entity to always be {{entity}}.Description. I don't think this is currently possible, I would have to implement a new base widget to do this.

Is there any way to define a sub_entity as being the entity + some extra information like this?

**Comment by acockburn** [comment]
There is no reason you couldn't add something like a `sub_attribute` argument to BASEDISPLAY that modified its behavior, then you could have a new derived widget that sets it, or you could have it as optional on any of the other widgets that use BASEDISPLAY as the base widget.

**Comment by mmmmmtasty** [comment]
That is a good idea....that is actually an improvement on the way that I implemented the basedisplay changes in my weather_summary PR because it is more flexible. I will update that to take an entity and sub_entity attribute.

Thanks!
