### ISSUE TITLE
Button dont back to original state

### ISSUE THREAD

**Issue by prsolucoes** [home-assistant/appdaemon#168]
Hi,

Button dont back to original state if the state was not changed. In the home-assistant web panel, if you click on a switch and the state is not changed, it back to old state, but this behavior dont happen on appdaemon switch daemon.

Thanks for any help.

**Comment by acockburn** [comment]
HADashboard uses optimistic switching by design so this isn't really an issue, it is working as expected. I do have plans to add pessimistic switching in the future which will make it work more like the HASS UI.

**Comment by acockburn** [comment]
Closing as this has been added to potential features list.
