### ISSUE TITLE
Appdaemon uses 100% CPU if run daemonized

### ISSUE THREAD

**Issue by hanrelan** [home-assistant/appdaemon#172]
I installed appdaemon using pip3 (no Docker) on Mac OS X

If I run appdaemon using the `--daemon` flag, it uses 100% of my CPU. But if I run appdaemon without `--daemon` it uses close to 0% CPU.

For now my workaround is to run with `nohup` to it can continue to run in the background, but it seems like the daemon is broken on OS X.

**Comment by acockburn** [comment]
I'm changing a lot of the code in 3.0 and I'll see if I can reproduce this, although I do not run on a mac and it might be mac specific.

**Comment by acockburn** [comment]
Please let me know if this still happens in 3.0 and I'll be happy to reopen.
