### ISSUE TITLE
Remove constraints for small cells/widgets in dashboard

### ISSUE THREAD

**Issue by mad-ady** [home-assistant/appdaemon#173]
I'm using the dashboard feature on a small display (480x320) and I use navigation to switch between dashboards.
The widget_dimensions I'm using are 38x38 in a 12x8 cells grid. The reason for this is to create a menu structure on the left of the dashboard for navigation.

Here is a sample layout:
```
#
# Main arguments, all optional
#
title: 3.5in LCD panel - high quality 480x320 divided into 12x8 cells - Home
widget_dimensions: [38, 38]
widget_margins: [1, 1]
columns: 12
use_gass_icon: 1

#
# Layout
#    
layout:
    - include: navigation-definition
    - home, clock(4x4), weather(7x4)
    - mpd
    - webcams
    - tv
    - webcambedroom, sensorkids(2x4), sensorliving(2x4), heater(2x4), forecast(5x4)
    - webcamliving
    - webcamkids
    - reload
```
The way this renders by default is:
https://imgur.com/jFoEUQ0.png

If I change https://github.com/home-assistant/appdaemon/blob/dev/appdaemon/widgets/javascript/javascript.css and comment out the "absolute" positioning under the icon style:
```
.widget-javascript-{{id}} .icon {
/*      position: absolute;**/
        top: 43px;
        width: 100%;
}

```

Then this is how the same dash renders:
https://imgur.com/F17uhjL.png

The problem is that by default all icons are positioned 43 pixels downward from the top, and for small screens 43 pixels is a lot :)

Is there a nice way to integrate this change and permit small widgets without breaking everything else? Perhaps a way to override the css per dashboard? (e.g. if I serve small dashboards I should be able to import a custom css which overrides the defaults and if I serve a large dashboard (for a tablet or TV) I will skip  loading it).

Thanks

**Comment by mmmmmtasty** [comment]
I also struggle with this and use a really small widget size by default. I was planning on trying to update them so that they don't break existing setups but behave better with more extreme sizes but only after my current set of PRs are merged.

**Comment by mad-ady** [comment]
Apart from absolute offsets for certain items (like icons, titles, etc)
there are also other issues - such as icon sizes are streched to 300% by
default and some texts have fixed colors. These could be changed either
with css or by loading some javascript code that iterates through the
elements and makes the changes.
Apparently support for a custom javascript should be already possible:
https://github.com/home-assistant/appdaemon/issues/59#issuecomment-297765452.
I need to play with it to get it working...


On Nov 28, 2017 6:16 PM, "mmmmmtasty" <notifications@github.com> wrote:

I also struggle with this and use a really small widget size by default. I
was planning on trying to update them so that they don't break existing
setups but behave better with more extreme sizes but only after my current
set of PRs are merged.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/home-assistant/appdaemon/issues/173#issuecomment-347575924>,
or mute the thread

**Comment by mmmmmtasty** [comment]
The fixed colours should be fixed by updating the widget to have the right
css variables and adding them to the skins. Which widgets have fixed
colours?

**Comment by mad-ady** [comment]
For me, a regular sensor (temperature) with this configuration:
```
sensorkids:
    widget_type: sensor
    title: Teo
    title_style: "font-size: 14pt;"
    text_style: "font-size: 16pt; font-color: white;"
    value_style: "font-color: yellow;"
    precision: 1
    entity: sensor.dormitor_teo
```
Renders the value with blue instead of yellow. Most likely I'm doing
something wrong...

**Comment by mad-ady** [comment]
Ok, I've managed to get this working - more specifically - to change position absolute for icons and to reduce the font size in h2 sections from 300% to 250% (it made the icons overflow a little).
The way I did it is with a skin, so that it doesn't interfere with the appdaemon installation.

Here are the details:
1. Clone the default skin as a custom skin (called defaultsmall):
```
$ cd ~homeassistant/.homeassistant/
$ mkdir custom_css
$ cd custom_css
$ cp -ar /usr/local/lib/python3.5/dist-packages/appdaemon/assets/css/default/ defaultsmall
```
2. Create the following Javascript file under ```~homeassistant/.homeassistant/custom_css/defaultsmall/dashboardsmall.js```:
```
window.onload = function(){
        console.log("Js onLoad");
        clearIconAbsolute();
        h2IconSize();
}

function clearIconAbsolute(){
        var sheet = document.styleSheets[0];
        var rules = sheet.cssRules || sheet.rules;
        console.log("Extracted CSS rules");
        for(var i=0; i < rules.length; i++){
                //console.log("Looking at "+rules[i].selectorText);
                //do a regex to see if it's 
                // .widget-javascript-default-.* .icon
                if(/\.widget-javascript-default-.* \.icon/.test(rules[i].selectorText)){
                        console.log("Found "+rules[i].selectorText);
                        rules[i].style['position'] = "";
                }
        }
}

function h2IconSize(){
        var sheet = document.styleSheets[0];
        var rules = sheet.cssRules || sheet.rules;
        console.log("Extracted CSS rules");
        for(var i=0; i < rules.length; i++){
                if(/h2/.test(rules[i].selectorText)){
                        console.log("Found "+rules[i].selectorText);
                        rules[i].style['font-size'] = '250%';
                }
        }
}
```
I got the names of the styles and tested out the development by making use of the Developer Tools and Breakpoints in Firefox/Chrome.
3. Import the javascript file in the skin in ```variables.yaml```:
```
body_includes:
 - <script src="/custom_css/defaultsmall/dashboardsmall.js"></script>
```
4. Load the dashboard with the skin name appended, e.g: ```http://192.168.1.9:5050/lcd35-hq?skin=defaultsmall```
The resultis in the image below:
https://imgur.com/yzr2Les

So, this issue should be closed and referenced whenever people wish to make core changes in their dashboards.

**Comment by mad-ady** [comment]
Here's a link to the skin: https://github.com/mad-ady/home-assistant-customizations/tree/master/appdaemon_skins/defaultsmall

If anyone wants me to push it to the official repository, let me know.

**Comment by mmmmmtasty** [comment]
I think it's good you found a way round nd it but I do think this should be fixed in the widgets by giving some slightly better defaults. People will be using a variety of skins and it's not great to have to 'post-process' them into shape and update the skins
