### ISSUE TITLE
wrong app_dir in the appdaemon.yaml did not throw an error

### ISSUE THREAD

**Issue by coolkau** [home-assistant/appdaemon#174]
I specified the app_dir wrong, that is `home/homeassistant/.../apps` instead of `/home/homeassistant/.../apps` (missing leading dash). I expected an error to be thrown if the the directory is wrong.

AppDeamon only sometimes printed a warning about the missing modules. It seems to have found the modules in some instances, despite the wrong config. So I could in change the name of the python file to trigger the error in around 50% of the cases. The python file howerver was never executed (I added some errors to the code to check this).

Given that the modules were found I googled a lot of things but not the config file. So it would be good to have a check if the app_dir exists and throw and error.

**Comment by acockburn** [comment]
I'll look at adding this in 3.0

**Comment by acockburn** [comment]
Fixed in 3.0
