### ISSUE TITLE
Parsing variables.yaml error

### ISSUE THREAD

**Issue by frafall** [home-assistant/appdaemon#176]
In function _get_styles in appdaemon/dashboard.py, a css line is split by colon and tested for two parts, this fails ex. when the valid css contains colons such as:

`background-image: url("http://myhost:8080/image.jpg");`

**Comment by acockburn** [comment]
Thanks I'll take a look at fixing this in 3.0

**Comment by acockburn** [comment]
This should be fixed in 3.0

**Comment by acockburn** [comment]
Reverted change - reopening

**Comment by acockburn** [comment]
OK, should be fixed now
