### ISSUE TITLE
Feature request: navigate overlay on non-clickable widgets

### ISSUE THREAD

**Issue by mad-ady** [home-assistant/appdaemon#179]
I use a small screen for my dashboards and I constantly navigate to display more information.
It would be nice to assign navigation functionality to widgets that don't react to clicks (like clock, weather, webcams). Clicking on a clock could navigate to a calendar, clicking on weather could navigate to a dashboard/iframe with hourly forecast, clicking on a webcam could navigate to a fullscreen view.

I am willing to look into it, but I could use some tips on how this could be done in an easy to extend way.

Thanks

**Comment by acockburn** [comment]
Makes sense - I would just add an optional url to the widgets params and also support direct links to dash pages like in the navigate widget

**Comment by acockburn** [comment]
Thanks - I'll get to this at some point but if you get there first I'm happy for the help ;)

**Comment by acockburn** [comment]
Closing for now - I have this on my list.
