### ISSUE TITLE
Enhance reload mechanism to support dependencies between files

### ISSUE THREAD

**Issue by insertjokehere** [home-assistant/appdaemon#18]
The automatic reload mechanism in appdaemon in cool, but doesn't support one of the most compelling use cases for appdaemon vs HAs built in automations: code reuse.

For example: I have a `utils.py` file that contains some utility functions that are used across several of my apps, like so:

-- utils.py --
```python
class BaseApp(appapi.AppDaemon):
    def do_a_thing(self):
        self.foo()
```

-- lights.py --
```python
from utils import BaseApp

class FunLights(BaseApp):

    def on_lights_on(self, kwargs):
        self.do_a_thing()
```

At the moment, if I change `lights.py`, everything is reloaded as expected (good) but if I change `utils.py` appdaemon doesn't recognize that it needs to reload `lights.py` as well (bad)

It would be really awesome if appdaemon would recognize (automatically? specially formed docstring?) that if `utils.py` changes, it also needs to reload `lights.py`

Thanks

**Comment by acockburn** [comment]
This is an excellent idea - how about listing dependencies for an APP in the configuration file?

**Comment by snairolf** [comment]
There should be a way figuring it out based on the imports?

Maybe https://pypi.python.org/pypi/modulegraph/

F

**Comment by acockburn** [comment]
Added in next release.
