### ISSUE TITLE
appdaemon error with hassio.io addon

### ISSUE THREAD

**Issue by vMeph** [home-assistant/appdaemon#184]
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: AppDaemon v0.3.0
 Python Apps and HADashboard for Home Assistant
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 20-init-configuration.sh: executing... 
[cont-init.d] 20-init-configuration.sh: exited 0.
[cont-init.d] 21-compiled-dir.sh: executing... 
[cont-init.d] 21-compiled-dir.sh: exited 0.
[cont-init.d] 50-compiled-symlink.sh: executing... 
[cont-init.d] 50-compiled-symlink.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
starting version 3.2.4
[services.d] done.
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 323, in main
    raise ValueError("Invalid host for 'dash_url'")
ValueError: Invalid host for 'dash_url'

where i can find this file with error i cant see nowhere, how to fix?`

**Comment by acockburn** [comment]
What do you have for dash_url in your configuration file?

**Comment by acockburn** [comment]
Closing for now. Will be happy to reopen when you supply the requested info.
