### ISSUE TITLE
duckdns addon error help

### ISSUE THREAD

**Issue by vMeph** [home-assistant/appdaemon#186]
i been trying for awhile to set duckdns addon for ssl certificates with out sucess, i keep getting this error
any ideas in whats going on?
this is my log info
`starting version 3.2.2
# INFO: Using main config file /data/workdir/config
+ Account already registered!
Sun Dec 24 10:05:41 WET 2017: KO
# INFO: Using main config file /data/workdir/config
Processing smartplan.duck.dns.org
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for mytest.duck.dns.org...
KO + Responding to challenge for mytest.duck.dns.org...
KOUnknown hook invalid_challenge
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "dns-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:unauthorized",
    "detail": "No TXT records found for DNS challenge",
    "status": 403
  },
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/CFa9oFLdl3bxfsTAFFbXQ-o5Kch46lXRvtMo2ZIXHhU/2854025900",
  "token": "OTyvHAU8uaT6jD3f_aEB2-5jDOCGkdS4Tgy057kn--4",
  "keyAuthorization": "OTyvHAU8uaT6jD3f_aEB2-5jDOCGkdS4Tgy057kn--4._V82lYjNbKdb3MO4tQWeuEJRPJlifPKmU0qJKueD2rU"
})`

**Comment by acockburn** [comment]
This has nothing to do with AppDaemon - I suggest you ask on the forums.
