### ISSUE TITLE
Light Brightness - value remebered

### ISSUE THREAD

**Issue by nicholh** [home-assistant/appdaemon#188]
Hi,

I have noticed a problem in Appdeamon Dashboard wherby the previous brightness level set in the dashbaord is remembered.

In more detail:
1) change a lights brightness via the dashbaord
2) adjust the same lights brightness via another means (i.e. directly in HA interface)
3) turn off the light (either via the dashboard or another means)
4) turn the light on via the dashboard.

Behaviour: the light is turned on at the brightness that was set in step 1
Expected Behavior: the light is turned on without affecting the previous brightness - ideally no brighness control sent.

I have tried to follow what is happening, however my pyton skills are not up to the level required.

**Comment by acockburn** [comment]
I can;t reproduce this - can you verify that the correct level is reflected in the percentage below the bulb before you turn the light off? This might be explained by slow state updates.

**Comment by nicholh** [comment]
Hi. 

Thanks for investigating.

The brightness does correctly show in the dashboard.

I only use template lights that reset to a default brightness as part of the turn on actions. this may be related. I will do some more tests tomorrow  and let you know how it can be reproduced.

Thanks,
Nichol

**Comment by nicholh** [comment]
Hi,

I hope you had a great new year.

I have set up a stripped down config for testing and have reproduced the problem in the below scenarios.

1) widget associated with physical phillips hue light in HA
2) widget associated with physical zwave light in HA
3) widget associated with template light in HA

I am running HA version 0.59.2, both HA and Appdaemon as docker images.

Am happy to do any further testing if you can point me in the right direction. (it is good learning for me also :))

Thanks,
Nichol

**Comment by acockburn** [comment]
OK, I finally managed to reproduce this - looking into a fix.

**Comment by acockburn** [comment]
This should be fixed in 3.1.0
