### ISSUE TITLE
Input Select changes to first item in list when page reaload in dashboard.

### ISSUE THREAD

**Issue by nicholh** [home-assistant/appdaemon#189]
Hi,

I have noticed a problem in Appdeamon Dashboard wherby on a dashboard load/reload input select widgets momentaraily change to the first item in the list then back to the previosly selected item.

In more detail:

1) set Input select in HA/Dashbaord is set to any value other than the first in the list
2) load or reload a dashboard that includes an input select widget associated to the the HA input select object.
3) Input select value is monantarilly set to the first object in the list (this is not just in the Dashboard, it updates the object in HA also. 
4) the input select value then reverts to the origial selected value (n.b. sometime (about 10% of the time the value does not revert and stays as the first value)

Expected Behavior: no change to input select unless new value is selected.

This casues a problem where outomations in HA are triggered from input selected changes.

I have tried to follow what is happening, however my pyton skills are not up to the level required.

Thanks,
Nichol

**Comment by acockburn** [comment]
This has been fixed in 3.0, soon to be released.
