### ISSUE TITLE
Issue with the run_every scheduler

### ISSUE THREAD

**Issue by siam28** [home-assistant/appdaemon#19]
Hello

I was getting an error with the run_every() scheduler, complaining of ``"TypeError: unsupported operand type(s) for +=: 'int' and 'datetime.timedelta'"``.

In appdaemon.py, I added `.total_seconds()` to the following line:

```args["basetime"] += args["interval"].total_seconds()```

This seemed to have fixed the issue. Just wanted to let you know for the next release. I'm surprised nobody else was getting this error.

**Comment by acockburn** [comment]
This is because you were supplying a timedelta object instead of an integer to the `run_every()` call, so not a bug. To make your code work, apply the `.total_seconds()` to the sun_every() call in your App.
