### ISSUE TITLE
Docker builds (acockburn/appdaemon) failing.

### ISSUE THREAD

**Issue by lamiskin** [home-assistant/appdaemon#191]
Commit `8f83955` has broken the 'offical' docker build, as now that the version has been moved to `appdaemon.utils`.

When running `pip3 install .` it tries to use `requests` even though it has not been installed, due to the import requirement in `appdaemon.utils` triggered by `setup.py`.

https://github.com/home-assistant/appdaemon/commit/8f83955b66687e02bcc56811d0d31db93cc4efe8#diff-2eeaed663bd0d25b7e608891384b7298R6

Can the docker build file include installing requests before installing the rest of the packages, or would it be better to have the version elsewhere with no non-standard packages being imported?

**Comment by acockburn** [comment]
Thanks for the heads up - since this is a dev version I hadn't got around to testing the Docker build yet. I'll make sure this is fixed for the 3.0 beta.

**Comment by acockburn** [comment]
OK, dev build is fixed - I didn't need the request import in that module in the first place so I moved it out.

**Comment by lamiskin** [comment]
Thanks :) 
The latest stable build had a bug that has been resolved in the dev branch, so I was keen to get the dev built (I just built locally for now).
