### ISSUE TITLE
Hass.io install instructions

### ISSUE THREAD

**Issue by cogneato** [home-assistant/appdaemon#192]
Can the Hass.io install instructions in the documentation point to a repo other than vkorn's? As far as I know, it has never been updated or maintained. Hassio users have a few other options floating around out there but I usually point users to this one: <https://github.com/hassio-addons/repository> mostly because @Frenck (@Frenck#4484 in discord) is often around and answers questions about his addons.

**Comment by acockburn** [comment]
Thanks - I had already removed the vkorn link in the most recent Docs (under dev) - I added in @frenk as well.
