### ISSUE TITLE
Not retrieving state of widgets 

### ISSUE THREAD

**Issue by twistedatoms** [home-assistant/appdaemon#195]
I have the appdaemon up and running but anytime i add something that has a state to check, like a switch or media_player, I get the following error “Error getting state, check Java Console for details” in my browser. the dashboard is pulling data from my Home-assistant docker for things like darksky weather just fine. I read a few post that had some similarity but nothing that would seem to solve the issue.

sorry I didn't clarify i am running the Dockerized version of appdaemon

**Comment by acockburn** [comment]
Did you check the Java Console for details?

**Comment by twistedatoms** [comment]
I guess that is where i am partly confused. i didn't think this was a java page. Also i don't know how to view a java console from a browser whenever it isn't a launched java program or applet.

**Comment by acockburn** [comment]
It's not actually JAVA, It's JavaScript which is different. Every browser is different in chrome you can access the developer tools from the menu on the far right, and select More Tools/Developer tools.

**Comment by twistedatoms** [comment]
![capture](https://user-images.githubusercontent.com/2582672/34471080-819b1334-eeeb-11e7-9cfa-d8976f1761ec.PNG)

I dug around in there and this is the only error coming up.

**Comment by acockburn** [comment]
Can you post your dashboard config, your appdaemon.cfg file and any log
entries you have from AppDaemon itslef.

**Comment by twistedatoms** [comment]
Hopefully everything is here that you needed. I just redacted the passwords and renamed everything to .txt because .yaml isn't supported. also just as a note this is a new installation where I switched from a manual installed Home-assistant and hadashboard to a dockerized version of both. so the dashboard is 
so the dashboard is farely empty. I had this all working before not sure why these dockers would be much different.

[appdaemon_docker.txt](https://github.com/home-assistant/appdaemon/files/1596412/appdaemon_docker.txt)
[appdaemon.txt](https://github.com/home-assistant/appdaemon/files/1596413/appdaemon.txt)
[MainPanel.txt](https://github.com/home-assistant/appdaemon/files/1596408/MainPanel.txt)

**Comment by acockburn** [comment]
You are missing the entity argument to your switch widget - that probably
explains the problem.

**Comment by twistedatoms** [comment]
You were totally right. Sorry I didn't catch that. After adding the required entity it is not have a problem. I won't make that mistake again. it has been awhile since I made a dashboard. 

quick question is the media_player suppose to display what is playing? It shows me in home-assistant but that doesn't seem to be getting pulled into HADashboard

**Comment by acockburn** [comment]
Not sure, haven’t looked for a while ... it works for me but each player
seems to be different and I can only work with the ones I have

**Comment by twistedatoms** [comment]
I sometimes don't know if something is a bug or I'm just not doing it right what is the best place for support?

**Comment by acockburn** [comment]
Forum is usually best when it’s workimg - that way if I’m not around others
can help.

**Comment by twistedatoms** [comment]
great thank you
