### ISSUE TITLE
Update MDI icons

### ISSUE THREAD

**Issue by eithe** [home-assistant/appdaemon#196]
Hi, any chance you could update the MDI icons to the latest version? I'm missing mdi-door-open (which was added in the beginning of Nov 2017). I've just manually upgraded locally, but would be great to get it into the main repo for future updates.

Thanks for considering :)

**Comment by acockburn** [comment]
Sure - I'll see if I can get this into the next release.

**Comment by acockburn** [comment]
This will be in 3.0 beta 3.
