### ISSUE TITLE
Question: Defaults for apps

### ISSUE THREAD

**Issue by yawor** [home-assistant/appdaemon#198]
Hi, it's been a long time since I've last updated Appdaemon and I've been using a version still using ini-style file configuration. I've updated today and converted my configuration to yaml. I've had to do some minor fixes but it works.
Unfortunately my configuration now looks horrible. In the ini-style configuration I've been using a DEFAULT section to set some data (quite a lot) I needed in most apps. After converting, all that data has been dumped into all apps separately (I understand why it happened, the DEFAULT section in configparser is automatically propagated to all other sections). Is there something in the new yaml-style configuration that can be used to keep some settings outside of individual apps' configuration and still be somehow included in them? If not I can try creating a PR with such functionality.

**Comment by yawor** [comment]
I've added my defaults to appdaemon.yaml as another dict key (besides appdaemon and HASS) and then I'm getting it in the app with self.config['MyDefaults'] and merge it with app config (for now a shallow merge is enough for me). This works for me but the issue is that updating appdaemon.yaml doesn't trigger reloading of the apps nor the config itself (if I force reload of the app by changing apps.yaml, the global config is still unchanged).

**Comment by acockburn** [comment]
This area is changing a little in 3.0 - I've already made some changes. I'll be happy to look at this with a view of making sure it works in 3.0, but my question would be how would you expect to track the dependencies? Should a change in a global section both change the contents of global and force a reload of all apps?

One workaround that would work in the current release is to build an App that owns all the global values and supply them as parameters to that app, then make any dependent apps explicitly dependent on the global app. That way, changing any of the parameters will force that app to reload, updating the global values, and also would force a reload of any dependent apps. Values from the global app can be retrieved using the `get_app()` function.

**Comment by acockburn** [comment]
To expand a little - at some point I added dependencies to apps to allow you to mark an app as dependent upon one or more other apps to ensure the correct loading order - not sure if you have seen that.

**Comment by yawor** [comment]
I know that feature. In the older version of Appdaemon it was my first approach to do a configuration section shared between some apps. But for some reason I've resigned from that approach and replace it with DEFAULT section. It was quite some time ago so I don't remember why I've done that. Maybe I'll look again at that feature.

As for the shared config dependency, in yaml there are tags (with ! at the beginning). In python yaml library handlers can added to handle these tags in some way. For example there could be a !use tag or something like that, which would take a key name from the global config dict. Appdaemon could track which apps are !using which config entries and reload them accordingly.

Anyway I've now rewritten configuration handling in my apps to take advantage of yaml syntax and restructured my config. Because of non-flexible ini-style my previous config (which was non-trivial, I needed more levels than just key-value pair) used ast.literal_eval to parse python dicts and lists stored as values in the ini. So yaml config is a lot better, even without support for DEFAULT section :). Fortunately in my case, the shared part of the config doesn't change much, so it works for me right now.

**Comment by acockburn** [comment]
Yes, that was one of the ideas behind YAML, to lose the single level approach to everything, so I'm glad you found that useful. 

I'll take another look at the DEFAULT replacement piece and see if I can come up with something less static.

**Comment by acockburn** [comment]
For lack of a better idea, having thought a little about this, I still think that the dependency tracking via an app used specifically for shared variables is the best approach, and the one that I use. I'll close this for now, but if this doesn't meet your current needs and you can come up with a better model I am happy to revisit this.
