### ISSUE TITLE
Serial connection with Appdaemon

### ISSUE THREAD

**Issue by roflcoopter** [home-assistant/appdaemon#199]
I am trying to start a serial connection to an Arduino, but it doesnt look like appdaemon is able to create the connection properly.

This is my code, when executed does nothing
```
import appdaemon.appapi as appapi
import serial

class KitchenCounterLight(appapi.AppDaemon):
    def initialize(self):
        ser = serial.Serial('/dev/ttyACM0',9600)
        clicks = '3'
        ser.write(bytes(clicks.encode('ascii')))
```

However, if i open the python interpreter and write:
```
import serial
ser = serial.Serial('/dev/ttyACM0',9600)
```
and then reload the script, my Arduino receives the message.

Is this a flaw in appdaemon?

**Comment by acockburn** [comment]
There is no reason this should be the case but I have no experience whatsoever with Audrino.

Have you verified that the initialization code is actually being called, e.g. with a log statement?

**Comment by roflcoopter** [comment]
Yes the apps initializing correctly.

I find it really strange that by just opening the connection in the interpreter makes it work in appdaemon

**Comment by roflcoopter** [comment]
Found what was causing the error, it needs some time to establish the serial connection so doing it this way works fine;
```
class KitchenCounterLight(appapi.AppDaemon):
    def initialize(self):
        self.listen_event(self.single_click, "click", entity_id=BUTTON, click_type=EVENT_SINGLE)
        self.ser = serial.Serial('/dev/ttyACM0',9600)
        
    def single_click(self, event_name, data, kwargs):
        clicks = '1'
        self.ser.write(bytes(clicks.encode('ascii')))
```
since the connection is being established when the app initializes but the ser.write doesnt happen until later
