### ISSUE TITLE
Possible error in Installation Docs

### ISSUE THREAD

**Issue by jmesberg** [home-assistant/appdaemon#200]
After I complete install (on raspi3 running stretch) and i try to start appdaemon using:

(homeassistant) pi@raspberrypi:~ $ appdaemon -c /home/homeassistant/conf

I get the following error:
Traceback (most recent call last):
  File "/usr/local/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/admain.py", line 198, in main
    config.read_file(open(config_file_conf))
TypeError: invalid file: None

It seems as if its looking for a file called config_file_conf but the installation instructions make no mention of such a file.

**Comment by yawor** [comment]
You need at least two files: appdaemon.yaml (for global configuration) and apps.yaml (for apps configuration). Do you have them?

**Comment by acockburn** [comment]
As this seems to be an installation issue, please ask on the Home Assistant forum.
