### ISSUE TITLE
Getting error on starting Appdaemon with latest Home Assistant

### ISSUE THREAD

**Issue by shekhardivekar** [home-assistant/appdaemon#209]
With following errors

[cont-init.d] 03-version-requirements.sh: executing... 
/var/run/s6/etc/cont-init.d/03-version-requirements.sh: line 44:   438 Illegal instruction     (core dumped) semver -q "${SUPERVISOR_VERSION}" "${version}"
FATAL: You Supervisor version is: 0.81
FATAL: This add-on requires: >=0.77.0
FATAL: Please consider upgrading.

**Comment by acockburn** [comment]
Hello - as this seems to be an installation issue, please ask on the Home Assistant forum.
