### ISSUE TITLE
Is it possible to use custom images instead of fa/mdi icons?

### ISSUE THREAD

**Issue by mad-ady** [home-assistant/appdaemon#211]
I'm looking into adding some links to script elements to load custom playlists (radio stations) in MPD. The thing is - I would prefer to keep the widgets small and only display an icon, but the icon needs to be suggestive, so I would prefer to add the radio station's logo. Any suggestion on how I could do this within the dashboard?

**Comment by acockburn** [comment]
It's not currently possible unless you create a custom widget, but it is on my list of things to add at some point.

**Comment by mad-ady** [comment]
Thanks for the answer. I take it I could also override the icons via
javascript with a custom skin and unique ids (as a hack). I'll take a look
when I have access to developer tools :)

**Comment by horchi** [comment]
I'am also looking for a ways to use custom icons (and gifs), in my case for the icon widget. 
Does this is possible in the meanwhile if not how are the plans ablout this?

**Comment by horchi** [comment]
here is my solution
[symbol-widget.zip](https://github.com/home-assistant/appdaemon/files/2569302/symbol-widget.zip)

the widget expect the image path realtive to custom_css, in the example below the images are stored in custom_css/img/

`p4state:
  widget_type: symbol
  title: P4
  entity: sensor.p4_status
  state_text: 1
  icons:
    "Betriebsbereit":
      icon: img/heating-p4.png
      style: "max-width: 60%"
    "Vorbereitung":
      icon: img/state-preparation.gif
      style: "background-color: #f9f2bb; max-width: 60%"
    "Anheizen":
      icon: img/state-heatup.gif
      style: "background-color: #f9f2bb"
    "Vorwärmen":
      icon: img/state-warmup.gif
      style: "background-color: #f9f2bb"
    "Zünden":
      icon: img/state-heatup.gif
      style: "background-color: #f9f2bb; max-width: 60%"
    "Heizen":
      icon: img/state-fire.gif
      style: "background-color: #f9f2bb; max-width: 60%"`

I use it to display the state of my pellets central heating

**Comment by mad-ady** [comment]
So, is it a read-only widget, or is it actionable?

**Comment by horchi** [comment]
it’s read only, almost like the icon widget the only differece is to display a custom icon (jpg, gif, png, ....) instead on of the fa or mdi icons

**Comment by JBX77** [comment]
Works perfectly.
Thanks for sharing.

**Comment by 230delphi** [comment]
For anyone trying to get this working on the latest version of appdaemon... 
Slight modification required to symbol.yaml - parameters need to be quoted:
```
entity: "{{entity}}"
fields:
  title: "{{title}}"
  title2: "{{title2}}"
```
This resolved the error "Error in widget definition '%s':"...

**Comment by fredvanwest** [comment]
I got this working as well. At the risk of being obvious, the files needed to be staged to the following locations for me:
config/appdaemon/custom_widgets/symbol.yaml (had to create custom_widgets folder, needed to edit symbol.yaml to add quotes)
config/appdaemon/custom_widgets/basesymbol/basesymbol.css
config/appdaemon/custom_widgets/basesymbol/basesymbol.html
config/appdaemon/custom_widgets/basesymbol/basesymbol.js
config/appdaemon/custom_css/img/prioritymail.gif (Had to create custom_css folder, this was an animated GIF I was using)
config/appdaemon/custom_css/img/YGM.gif (another animated GIF I was using)

In my dashboard.dash, file my widget call out looks like:
animated_gif_mail:
    title: Mail Call
    widget_type: symbol
    entity: binary_sensor.virtual_switch_contact
    state_text: 1
    state_map:
       "off": "Mail Waiting"
       "on": "No Mail Today"
    icons:
      "off":
         icon: img/YGM.gif
         style: "max-width: 40%"
      "on":
         icon: img/prioritymail.gif
         style: "max-width: 60%"

Good luck!
