### ISSUE TITLE
ERROR no 'appdaemon' section in /conf/appdaemon.yaml

### ISSUE THREAD

**Issue by kaareseras** [home-assistant/appdaemon#212]
After the update of the docker image for a few hours ago, appdeamon crashes, with this error:

ERROR no 'appdaemon' section in /conf/appdaemon.yaml

I have tried to complete remove my config, so the container writes its own config, and these files is written, but still the error above, and then the container just reatarts

sudo docker run --name=appdaemon -d -p 5050:5050 \
  --restart=always \
  -e HA_URL="http://xxx.xxx.xxx.xxx:8123" \
  -e HA_KEY="SomePassword" \
  -e DASH_URL="http://$HOSTNAME:5050" \
  -v /volume1/docker/HADaemon:/conf \
  -v /etc/localtime:/etc/localtime:ro \
  acockburn/appdaemon:latest

log:
  logfile: STDOUT
  errorfile: STDERR
appdaeaemon:
  threads: 10
  plugins:
    HASS:
      ha_url:
      ha_key:

**Comment by acockburn** [comment]
I just released AD 3.0 with some breaking changes in the config:

https://community.home-assistant.io/t/announcement-appdaemon-3-0-beta-1/38916/5

Please report any issues on that thread when you have made the appropriate changes.
