### ISSUE TITLE
Typo in example appdaemon.yaml

### ISSUE THREAD

**Issue by m4rkireland** [home-assistant/appdaemon#213]
In the example appdaemon.yaml https://github.com/home-assistant/appdaemon/blob/dev/conf/appdaemon.yaml.example

instead of AppDaemon: there is appdaeaemon:

Also HASS is part of the plugins: tree rather than at the same level as AppDaemon

**Comment by acockburn** [comment]
Thanks - I corrected it, it should in fact be `appdaemon` in lower case for 3.0, but thanks for catching the typo. Will be fixed in the dev docs soon, and in the next beta when I release it.
