### ISSUE TITLE
run hourly documentation

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/appdaemon#22]
The run hour documentation says the format is 
run_hourly(<callback>,time=None,kwargs)

Using that, I got the following error:

`TypeError: run_hourly() missing 1 required positional argument: 'start'`

Also the example for run_hourly is the example from above for run_daily.

If you will tell me how to edit the document to submit changes, I'll be happy to work on it.

**Comment by acockburn** [comment]
Fixed the example - couldn't find a problem with the actual format.
