### ISSUE TITLE
Unable to find widget type 'temperature'

### ISSUE THREAD

**Issue by KrunchMuffin** [home-assistant/appdaemon#225]
Hope this is the correct place to post this. I am trying to setup HADashboard and tried using the temperature widget like in the docs. When I reload the page I get `Unable to find widget type 'temperature'`.

    outdoor_temperature:
      widget_type: temperature
      entity: sensor.netatmo_outdoor_temperature
      settings:
          minValue: -40
          maxValue: 40
          width: 120
          height: 120
          majorTicks: [15,20,25,30]
          highlights: [{'from': -40, 'to': 10, 'color': 'rgba(0,0, 255, .3)'},{'from': 11, 'to': 40, 'color': 'rgba(255, 0, 0, .3)'}]

Am I missing something?

**Comment by acockburn** [comment]
This is only available in the 3.0 beta - what version of AppDaemon are you running?

**Comment by KrunchMuffin** [comment]
ahh, ok, docs automatically go to Latest, assumed latest stable.
Using the one from Hass.io
Assuming version no. is not correct?

Description | Python Apps and HADashboard using AppDaemon 2.x for Home Assistant
Version | 1.0.0

**Comment by acockburn** [comment]
The hass.io addon hasn't been updated no. I believe @frenk is working on an addon for AD 3.0. The stable branch of the docs points to the ones you need, latest points to the beta version. When the beta becomes a real release latest will point there too - it's a little confusing I know!

**Comment by KrunchMuffin** [comment]
don't believe I can install over top on hass.io, correct?

**Comment by acockburn** [comment]
No, that won;t work I am afraid.
