### ISSUE TITLE
HADashboard on WindowsRT (8.1) Surface Tablet.

### ISSUE THREAD

**Issue by KrunchMuffin** [home-assistant/appdaemon#228]
I was going to use this tablet I had laying around to display the dashboard. Been getting the dashboard all set up. Went to test it on the tablet and the touches do not register a click event. Has anyone tried to use it on this type of tablet before? or like a laptop with touchscreen? the dev tools were not coming up, so I can't debug what is going on. Tried regular internet exploder and the metro version. If you are not familiar with WinRT, suffice it to say, you can't install any other browsers, o rapps for that matter, unless they can be had from the windows app store and that they have a version for the ARM platform.

**Comment by acockburn** [comment]
I don;t have one of these and I'm not sure if anyone else has had success - I suggest you ask on the Forums as I have no direct knowledge.
