### ISSUE TITLE
Redundant configuration entries

### ISSUE THREAD

**Issue by bcelary** [home-assistant/appdaemon#23]
Maybe I am missing something obvious but what is the reason of creating these redundant entries in the configuration file:

```
latitude = <latitude>
longitude = <longitude>
elevation = <elevation
timezone = <timezone>
```

Shouldn't the appdeamon know them from HA?

P.S. Not sure if raising an issue is the right way to address such question...

**Comment by acockburn** [comment]
An excellent point, don;t know why I didn't think of it myself!

This is fixed in the next version, with the exception of Elevation which is not available in the RESTFul interface. This seems to be an oversight and I have raised an issue for it.
