### ISSUE TITLE
Example `appdaemon.yaml` 

### ISSUE THREAD

**Issue by fabaff** [home-assistant/appdaemon#231]
If one tries to run `appdaemon` with the sample [`appdaemon.yaml`](https://github.com/home-assistant/appdaemon/blob/dev/conf/appdaemon.yaml.example) you get a traceback.

```bash
$ appdaemon -c /home/fa143321/repos/home-assistant-appdaemon/
Traceback (most recent call last):
  File "/home/fa143321/Documents/repos/home-assistant-appdaemon/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/home/fa143321/Documents/repos/home-assistant-appdaemon/lib64/python3.6/site-packages/appdaemon/admain.py", line 230, in main
    conf.logfile = config['AppDaemon'].get("logfile")
KeyError: 'AppDaemon'
```

It looks like a discrepancy between code, docs and example.

**Comment by fabaff** [comment]
This was mentioned in the [release notes](http://appdaemon.readthedocs.io/en/latest/HISTORY.html#b1-2018-01-12) but only released as beta.

**Comment by acockburn** [comment]
Just to add to Fabian;s explanation - there have been several breaking changes in the 3.0 beta. From that error looks like you are actually running the beta so yo ushould be referring to the latest not the stable docs, here:

http://appdaemon.readthedocs.io/en/latest/
