### ISSUE TITLE
Provide docker tags for specific versions

### ISSUE THREAD

**Issue by jackwilsdon** [home-assistant/appdaemon#232]
Currently `latest` points to 3.0 beta, and the only other tag is `dev`. Would it be possible to get some tags for exact versions?

**Comment by jackwilsdon** [comment]
```

**Comment by acockburn** [comment]
OK, I think I cracked it. Docker is setup to build tags. Moving forward I'll tag releases.

**Comment by jackwilsdon** [comment]
Something like this would work;

```Bash
docker build https://github.com/home-assistant/appdaemon.git#tags/2.1.12 -t acockburn/appdaemon:2.1.12
docker push acockburn/appdaemon:2.1.12
```

**Comment by acockburn** [comment]
Thanks - I think I achieved the same by explicitly adding a tag on the hub, so there are now images for:

- latest
- dev
- 3.0b1
- 3.0b2
- 2.1.12

Moving forward latest and dev should be maintained with explicit tags for each new version as I release it.

**Comment by jackwilsdon** [comment]
Sounds great, thanks!
