### ISSUE TITLE
Repeated "ERROR no 'appdaemon' section in /conf/appdaemon.yaml" in Docker container

### ISSUE THREAD

**Issue by marthoc** [home-assistant/appdaemon#233]
I'm using the latest acockburn/appdaemon image. There is most certainly a /conf/appdaemon.yaml file at the config dir with an AppDaemon section in it. Any idea what could be causing the error?

**Comment by acockburn** [comment]
You are using a 3.0 version that has breaking changes - see my response to your forum post.
