### ISSUE TITLE
Install apps into docker container

### ISSUE THREAD

**Issue by efficiosoft** [home-assistant/appdaemon#235]
Hi,

I'm wondering what the suggested way of adding custom python modules into the docker container is, e.g. when running under hass.io.

Background is that I developed some apps that are distributed via GitHub and PyPi. Currently, hass.io users have to download the package containing the app's code and copy it into their ``apps`` directory. However, this makes keeping the apps up-to-date difficult, as any upgrade has to be done manually, which somehow feels nasty and is against the plug-and-play philosophy of hass.io.

What do you think about a configurable list of python packages for which ``pip install --upgrade`` is ran automatically when the appdaemon container starts?

I must admit that I have virtually no experience with docker at all, but as far as I understand, acomplishing this should be relatively simple by processing an environment variable holding all packages to install inside the dockerStart script, isn't it?

Best regards
Robert

**Comment by acockburn** [comment]
That sounds like a relatively simple idea and would add a lot of value - I'll add it to my list.

**Comment by efficiosoft** [comment]
@acockburn Nice to hear, thanks! This addition will make distributing apps a lot easier.

**Comment by sammy-tam** [comment]
related to this, my current workaround is to actually have my own docker image based on this repo's DOCKERFILE and add additional steps to the dockerStart.sh to check for a "requirements.txt" file and ``pip install -r requirements --upgrade`` when appdaemon docker image is started..

**Comment by Diaoul** [comment]
I was looking into the docs and was wondering how to use a package in PyPi within AppDaemon. It seems this is not supported yet (automatically I mean) so one has to install the dependencies manually to his instance.

I really don't want to maintain a dependency tree under my apps directory, `requirements.txt` and `Pipfile` are made for that. Looking forward for this feature.

**Comment by acockburn** [comment]
Closing as I merged the above PR which should address this.
