### ISSUE TITLE
Have some of the run_ functions take a string time

### ISSUE THREAD

**Issue by OmenWild** [home-assistant/appdaemon#237]
It would be really handy if run_once(), run_at(), and run_daily() could take a string time (anything parsable by parse_time()). 

I have an app that changes the colors of my Gardenspots that starts at `sunset - 00:15:00` and ends at `22:45:00`. Since sunset changes day-to-day I can't convert the time once and use run_daily(). What I do is have my end time callback convert the start_time string to a datetime object for run_at(). 

It would be awesome if run_daily() could recognize and parse the string (every time re-runs). Since datetime handling is always so tricky, it would probably be better for you to solve it once than have everyone implement their own.

Thanks,
   Omen

**Comment by acockburn** [comment]
This usecase is exactly what `run_at_sunset()` was written for. It will run every day relative to sunset for that day, and you can apply an offset. No need to reset the timer every day.

The functions you mentioned are intended to run at specific times so you don;t need them to implement your usecase.

**Comment by OmenWild** [comment]
`run_at_sunset()` could be made to work, but it would require me to parse the input from the yaml configuration file and decide if it's an absolute time, or sunrise/sunset relative time, then parse out the remainder, basically the guts of `parse_time()`.

In the yaml I want to accept anything that can be used with `parse_time()`, so it makes sense to me to be able to pass those directly to the scheduling functions. Unless I missed a function that already does this?

**Comment by hhaim** [comment]
I agree with @OmenWild 

let's take this example (smart_heat.py)

evening = self.parse_time(self.args["evening_on"])
self.run_daily(self.evening, evening)

in case user set a specific time there is no problem, however if user asks "sunset" the parse_time() will be evaluated only once. there should be an easy way to achive that, not sure the string is the right way.

to achive this today, there is a need to create another copy of the parse_time and in case it is sunset call the sunset API else call the time API

**Comment by acockburn** [comment]
This will be in 3.1.0.
