### ISSUE TITLE
log to both file and stdout/stderr

### ISSUE THREAD

**Issue by uchagani** [home-assistant/appdaemon#241]
Is there a way to do this?

**Comment by acockburn** [comment]
The only way currently is with 3.0beta, which gives you access to the underlying logger objects. You could then, from an app, add additional handlers.

**Comment by uchagani** [comment]
I have `appdaemon 3.0.0b3` can you point me to how to do this?

**Comment by acockburn** [comment]
use `get_main_log() and/or `get_error_log()` wich gives you the underlying logger object. You can then add additional handlers as per the logger docs:

https://docs.python.org/3.5/library/logging.html
