### ISSUE TITLE
How do I get rid of the dimmer slider on a light button?

### ISSUE THREAD

**Issue by DNA99** [home-assistant/appdaemon#244]
Hi,

Can anyone teach me how to remove those sliders at the bottom? I dont use dimmers..
![capture](https://user-images.githubusercontent.com/29714334/36733452-a7429e70-1c0b-11e8-844a-835f22a53ef9.JPG)

**Comment by acockburn** [comment]
Use a widget type of `switch` instead of``light`.

**Comment by DNA99** [comment]
can you point me to where I can find a sample of the code for this?

**Comment by acockburn** [comment]
Rather than using the implicit entity names, you need to define the widget higher up in the dashboard file and set it's widget type to "switch" as described here:

http://appdaemon.readthedocs.io/en/latest/DASHBOARD_CREATION.html#detailed-widget-definition

**Comment by DNA99** [comment]
@acockburn Thank you! Appreciate your help!
