### ISSUE TITLE
Can not get dash to compile

### ISSUE THREAD

**Issue by wayne47git** [home-assistant/appdaemon#245]
Could not get dash files to compile. Problem was that the docs at [http://appdaemon.readthedocs.io/en/stable/DASHBOARD_INSTALL.html](url) are ambiguous.  Please change this line:
  You just need to add a directive to the config file

to include a reference to  **appdaemon.yam**l 

(I put the lines into **/config/configuration.yaml** which was never going to work)

**Comment by acockburn** [comment]
I made the change - it will be in the next beta.
