### ISSUE TITLE
Migrate from deprecated "async"

### ISSUE THREAD

**Issue by peterhoeg** [home-assistant/appdaemon#246]
According to upstream:

>  DEPRECATION NOTE: Please do not use this library ! It’s not working correctly in python 3, and besides that might be called a failed experiment.

I don't know enough python to advise on a suitable substitute.

**Comment by acockburn** [comment]
I'm not actually using it anywhere - where do you see it?

**Comment by dotlambda** [comment]
It's in setup.py:
https://github.com/home-assistant/appdaemon/blob/415ae032e47a0eb5d4e1724a00d56b75207faccb/setup.py#L17

**Comment by acockburn** [comment]
Thanks @dotlamba - I merged your PR and removed it.

@peterhoeg I'm not sure why that requirement was even there, I never used it to my knowledge. Thanks.
