### ISSUE TITLE
Calling listen_state() with duration parameter doesn't work as expected if registered to a device type, and two devices change state for less than the specified duration

### ISSUE THREAD

**Issue by liwenyip** [home-assistant/appdaemon#247]
I have some buttons set up as binary_sensors. I've used `listen_state()` with a `duration` parameter to 
fire a callback if any of the buttons is held for 3 seconds. It works fine if only one button is pressed. But if I press and hold 2 buttons together for less than 3 seconds, the callback still fires for one of the buttons (it shouldn't)

Here's my app:
```
import appdaemon.appapi as appapi

#
# Hello World App
#
# Args:
#

class HelloWorld(appapi.AppDaemon):

  def initialize(self):
     self.log("Hello from AppDaemon")
     self.log("You are now ready to run Apps!")
     self.listen_state(self.state_change, "binary_sensor", old="off", new="on", duration=3) 

  def state_change(self, entity, attribute, old, new, kwargs):
     self.log("entity=%s attribute=%s old=%s new=%s" % (entity, attribute, old, new))
```

I added some debug messages at
https://github.com/home-assistant/appdaemon/blob/master/appdaemon/appdaemon.py#L1956
and
https://github.com/home-assistant/appdaemon/blob/master/appdaemon/appdaemon.py#L1980
so I can see when the timer is set and cancelled.

Here is what I get when one of my binary_sensors changes state to ON for less than 3 seconds:

```
2018-03-01 21:47:53.016156 INFO hello_world: entity=binary_sensor.b attribute=state old=off new=on
2018-03-01 21:48:44.007240 INFO Reloading Module: /home/homeassistant/.homeassistant/apps/hello.py
2018-03-01 21:48:44.017112 INFO Loading Object hello_world using class HelloWorld from module hello
2018-03-01 21:48:44.025116 INFO hello_world: Hello from AppDaemon
2018-03-01 21:48:44.031943 INFO hello_world: You are now ready to run Apps!
```
(press button A)
```
SETTING TIMER FOR binary_sensor.a
```
(press button B)
```
SETTING TIMER FOR binary_sensor.b
```
(release button A)
```
CANCELLING TIMER FOR binary_sensor.a
```
(release button B)
```
CANCELLING TIMER FOR binary_sensor.b
```
(a few seconds later)
```
2018-03-01 21:48:55.028099 INFO hello_world: entity=binary_sensor.b attribute=state old=off new=on
```

There's a fairly easy workaround, which is to register separate callbacks for each binary_sensor (instead of one callback for all binary_sensors). So I understand if you don't want to fix this, but can I suggest we at least add something to the docs to say that the duration parameter may not work correctly if registered to a device type (as opposed to a specific entity).

Thanks in advance :-)

**Comment by acockburn** [comment]
Thanks for the heads up - I'll take your suggestion of adding a warning to the docs in the next beta.
