### ISSUE TITLE
listen_state() callback with duration parameter fires up to one second early

### ISSUE THREAD

**Issue by liwenyip** [home-assistant/appdaemon#249]
I think it's because appdaemon's clock ticks in 1-second intervals, and timestamps are rounded DOWN to the nearest second by casting them to `int`.

Here's my app:
```
import appdaemon.appapi as appapi

#
# Hello World App
#
# Args:
#

class HelloWorld(appapi.AppDaemon):

  def initialize(self):
      self.log("Hello from AppDaemon")
      self.log("You are now ready to run Apps!")
      self.listen_state(self.a_off, "binary_sensor.a", new="off") 
      self.listen_state(self.a_on, "binary_sensor.a", new="on") 
      self.listen_state(self.a_held, "binary_sensor.a", new="on", duration=1) 

  def a_off(self, entity, attribute, old, new, kwargs):
    self.log("Button A released")
  
  def a_on(self, entity, attribute, old, new, kwargs):
    self.log("Button A pressed")

  def a_held(self, entity, attribute, old, new, kwargs):
    self.log("Button A held")
```

Here's my output:
```
2018-03-02 20:00:59.265259 INFO hello_world: Button A pressed
2018-03-02 20:00:59.446171 INFO hello_world: Button A released
2018-03-02 20:00:59.963887 INFO hello_world: Button A pressed
2018-03-02 20:01:00.016264 INFO hello_world: Button A held <-- fired after only 50ms
2018-03-02 20:01:00.232505 INFO hello_world: Button A released
2018-03-02 20:01:00.768718 INFO hello_world: Button A pressed
2018-03-02 20:01:00.990076 INFO hello_world: Button A released
```

I haven't got a workaround for this - other than to set duration=2 so the callback will fire after a random time between 1 and 2 seconds.

Ideas for other workarounds?

**Comment by acockburn** [comment]
Unfortunately, any workaround would suffer from the same issue - the resolution of 1 second means that without changes you are stuck with this kind of issue in an event driven environment. I have been giving some thought to allowing the clock resolution to be increased - 0.1s would give you a far better result. I'll leave this open to remind me to look into this some more.

**Comment by acockburn** [comment]
As of AppDaemon 3.03 (to be released soon) you can specify a much faster schedule click time - down to 100th of a second works on my hardware. This should allow you to run the scheduler at say 1/20th second resolution and you should get a much better result for the above issue.
