### ISSUE TITLE
No longer working after Docker updates

### ISSUE THREAD

**Issue by twistedatoms** [home-assistant/appdaemon#257]
several weeks ago the docker got updated. I haven't gotten the dashboards to work since then. At that same time it looks like the structure of appdaemon.yaml changed, and the variables HA_URL and HA_KEY and DASH_URL no longer get injected into the config file when the docker is installed. Below is the docker command. I have tried deleting the docker and all the files and doing a fresh install with no luck.

docker run -d --name='AppDaemon' --net='bridge' -e TZ="America/Anchorage" -e HOST_OS="unRAID" -e 'HA_URL'='http://xxx.xxx.xxx.xxx:8123/' -e 'HA_KEY'='xxxxxxx' -e 'DASH_URL'='http://xxx.xxx.xxx.xxx:5050' -p '5050:5050/tcp' -v '/mnt/user/appdata/AppDaemon/':'/conf':'rw' 'acockburn/appdaemon'

**Comment by acockburn** [comment]
There was a fix for this released in beta 5 yesterday, of you upgrade it
should work for you.

**Comment by twistedatoms** [comment]
your right it did inject 2 of the 3. is the DASH_URL no longer needed?

**Comment by acockburn** [comment]
DASH_URL is still required, but the injection should work as it is in beta 5 - can you share your appdaemon.yaml file?

**Comment by twistedatoms** [comment]
This is the appdaemon.yaml file contents. as you can tell it doesn't create the 
hadashboard:
  dash_url: http://[ip]:[port]


log:
  logfile: STDOUT
  errorfile: STDERR
appdaemon:
  threads: 10
  plugins:
    HASS:
      type: hass
      ha_url: http://[IP]:8123
      ha_key: [Passphrase]

**Comment by acockburn** [comment]
The DASH_URL issue should be fixed in 3.0.2
