### ISSUE TITLE
some package versions in setup.py don't match versions required by HA

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/appdaemon#260]
I have appdaemon and HA in the same virtual env. so when i update appdaemon some of the packages (like aiohttp) are downgraded because the version mentioned in setup.py is older than the one required by HA.

is it possible to match the versions required by appdaemon and HA?

**Comment by acockburn** [comment]
At the moment the best practice is to run them in separate venvs as I am making no attempt to harmonize the packages at this time. At some point in the future I'll be integrating AD with HASS and at that point, they will need to run in the same venv, so this will be done then.
