### ISSUE TITLE
Icon do not refresh

### ISSUE THREAD

**Issue by martyouel** [home-assistant/appdaemon#267]
Hi,
just discovered HAdashboard/appdaemon yesterday and already passed a lot of hours working with this and I love it ;) great job !

I have a small problem with a tile icon that do not refresh automaticaly in the dashboard. My problem is with a switch for my garage door. Here's the config of my switch within HA.

  - platform: command_line
    switches:
      mygarage:
        command_on: 'curl http://mywebservice/GarageDoor -d "actiontodo=open"'
        command_off: 'curl http://mywebservice/GarageDoor -d "actiontodo=close"'
        command_state: 'curl http://mywebservice/GetGarageInfo'
        value_template: '{{ value_json.Status == "open"}}'        
  - platform: template
    switches:
      mygarage2:
        value_template: "{{ is_state('switch.mygarage', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.mygarage
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.mygarage        
        icon_template: >-
          {% if is_state('switch.mygarage', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}  

So basically, I have a commandline switch to control and get status from my garage door (throught a custom c# webservice that I built).

On top of this switch I have a switch template  to manage the icon on the way I want. So, when the door is open (switch.mygarage ON) I want the icon "garage-open". When switch.mygarage is OFF, I want the icon "garage".

The problem is that the ICON do not change from one to the other. The only way to correctly get the new icon is by doing a whole refresh of the page.

Here's an example -> 

My garage door is open
I load my HA dashboard in my browser
I have the icon "garage-open" and the icon is in green because the switch is at state ON
I click on the icon
The garage door close and the icon goes to grey but remain the same icon "garage-open" rather than switch it to "garage"

![image](https://user-images.githubusercontent.com/22892975/37867152-a615a93a-2f6a-11e8-9b2c-607a692ff60f.png)

![image](https://user-images.githubusercontent.com/22892975/37867158-bb741d0c-2f6a-11e8-9e55-e8d2c0e25c0e.png)

If I then do a complete refresh, I now get the "garage" icon

![image](https://user-images.githubusercontent.com/22892975/37867163-ce7c5a90-2f6a-11e8-8175-2f5e94002e1f.png)

Any help will be appreciated

thanks

**Comment by acockburn** [comment]
Hi there - glad you like AppDaemon!

I would suggest you post questions like this in the forum, you'll get a much quicker response. I would need to see your dashboard configuration for the widget in question, as well as AppDaemon's logfile. Also, please use the preformatted text when posting code samples or it is impossible to see where the problem might be. Again, I'd prefer you re-posted this in the forum.

**Comment by martyouel** [comment]
Hi,

thanks for your answer.
As requested, I posted to the forum with the added information.

https://community.home-assistant.io/t/icon-do-not-refresh-in-my-hadashboard/48233

**Comment by acockburn** [comment]
And I think I spotted the problem in the meantime - see the forum :)
