### ISSUE TITLE
listen_event not possible with named argument 'name'

### ISSUE THREAD

**Issue by fabianschaefer** [home-assistant/appdaemon#269]
I have an Appdaemon automation which listens for homematic.keypress events. (see https://www.home-assistant.io/components/homematic/)
In the **kwargs I have to set a 'name' Argument to filter events from a specific device name:
`self.listen_event(self.rotate_scene, "homematic.keypress", name=self.switch_name, param="PRESS_CONT", channel=self.switch_channel)`

It worked like a charm in Appdaemon 2, but in Version 3 it throws the following Error:
```
File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1513, in init_object
    init()
  File "/config/appdaemon/apps/scenes2.py", line 15, in initialize
    self.listen_event(self.rotate_scene, self.event, name=self.switch_name, param="PRESS_CONT", channel=int(self.args["switch_channel"]))
  File "/usr/lib/python3.6/site-packages/appdaemon/plugins/hass/hassapi.py", line 187, in listen_event
    return super(Hass, self).listen_event(namespace, cb, event, **kwargs)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 226, in listen_event
    return self.AD.add_event_callback(name, namespace, cb, event, **kwargs)
TypeError: add_event_callback() got multiple values for argument 'name'
```

It seems like a new function has been introduced that already uses the argument 'name'. How can I get it working?

**Comment by acockburn** [comment]
The easiest way is to change your name parameter to something else, e.g. "_name"

**Comment by fabianschaefer** [comment]
That‘s not an option because this ‚name‘ is given by the homematic component. It would be possible to change the homematic component accordingly but that‘s a breaking change and would require many config changes for all homematic users.

**Comment by acockburn** [comment]
OK, well I can fix this by changing my parameter to something else, but that will be in the next release.

**Comment by acockburn** [comment]
OK, that change is made and will be in 3.0.1, which should be out soon.
