### ISSUE TITLE
Units wrong  in baseweather

### ISSUE THREAD

**Issue by rcastberg** [home-assistant/appdaemon#273]
Units are not updated as they are in home assistant. The values home assistant report are 'si' but baseweather shows, e.g. "Mph" instead of 'm/s'

**Comment by acockburn** [comment]
The units are currently hard coded in the weather widget - this i being worked on.

**Comment by kabturek** [comment]
@rcastberg  you can test it using code from https://github.com/home-assistant/appdaemon/pull/281 (just put the files in custom_components - check in docs)

**Comment by kabturek** [comment]
Can be closed (released in 3.0.1)
