### ISSUE TITLE
Firefox android fullscreen

### ISSUE THREAD

**Issue by alexandre72** [home-assistant/appdaemon#275]
It will be cool to have fullscreen mode in firefox for android too

**Comment by acockburn** [comment]
I don;t have an Android device so this would be hard to test. Do you have any information on how to make it work in fullscreen mode on Android?

**Comment by alexandre72** [comment]
webapp manifest seems to be a solution, I don't know how hadaemon html files are served,  but when you own a web server and put a manifest.json at root path, with some options in it, you can allow user to install it as "an android native" app. index.html must contains a link to it.

See more at:
 https://developer.mozilla.org/en-US/docs/Web/Manifest

<link rel="manifest" href="/manifest.webmanifest">

Here's a sample manifest, works on my own html static page:
{
  "name": "coolApplication",
  "short_name": "coolApp",
  "start_url": "index.html",
  "display": "standalone",
  "orientation": "landscape",
  "description": "A cool app",  
  "icons": [
    {
      "src": "icon-48x48.png",
      "type": "image/png",
      "sizes": "48x48"
    },
    {
      "src": "icon-256x256.png",
      "type": "image/png",
      "sizes": "256x256"
    }
  ],
  "author": {
    "name": " Doe John",
    "website": "https://sample"
  }
}

**Comment by alexgeertsema** [comment]
firefox for android has a fullscreen add-on.  don't know how en if it works. never tried it.
[https://addons.mozilla.org/en-US/android/addon/fullscreen-mobile/](https://addons.mozilla.org/en-US/android/addon/fullscreen-mobile/)

**Comment by alexandre72** [comment]
Hi!

Thanks for answer, I know these add-on but don't works nicely and mozilla team implemented a webapp native mode in Firefox 58 to solve these issue.

Got a clean solution by replacing file content of(I suggest to have 48x48 and 256x256 icons size):
appdaemon/appdaemon/assets/images/manifest.json
by the following:
{
  "name": "HaDashboard",
  "short_name": "HaDashboard",
  "start_url": "/main",
  "display": "standalone",
  "orientation": "landscape",
  "description": "Home-Assistant Dashboard",  
  "icons": [
    {
      "src": "/images/android-chrome-192x192.png",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
       "src": "/images/android-chrome-512x512.png",
      "type": "image/png",
      "sizes": "512x512"
    }
  ],
  "author": {
    "name": AppDaemon Team",
    "website": "https://appdaemon.readthedocs.io/"
  }
}
