### ISSUE TITLE
Feature request listen_state numeric_state below or above

### ISSUE THREAD

**Issue by runningman84** [home-assistant/appdaemon#276]
I would like to replace some existing automations with an appdaemon implementation.

My old automation code looked like that:
```
    - platform:         numeric_state
      entity_id:        sun.sun
      value_template:   '{{ state.attributes.elevation }}'
      below:            10
```
It would be cool if I you just write something like that:
```
self.handle = self.listen_state(self.my_callback, "sun.sun", attribute = "elevation", numeric_state_below = 10)
```

Right now it looks like I have to watch for any state change of the corresponding attribute and evaluate the value in my own code...

**Comment by acockburn** [comment]
Hi,

This is really the whole point of AppDaemon, it's flexible logic gives great power but is not always simpler than something like the above. So, although I think constraints add value for common cases, I really don't want to implement the whole of HASS' YAML functionality as constraints when you have access to all of Python's logical statements and conditions easily available.
