### ISSUE TITLE
What is the minimal structure for a fully centralized app?

### ISSUE THREAD

**Issue by wsw70** [home-assistant/appdaemon#278]
I would like to centralize all my actions (except if this is a bad idea performance-wise) in one single app.

Does this still require to have:

- `appdaemon.yaml` to configure `appdaemon` (in my case only to configure HA access)
- a directory `apps`
- within this directory an `app.yaml` file which will have just one entry:

```
All:
  module: all
  class: All
    listen_to_sensor: all_events
```

- and the `all.py` file which does the dispatching

I fully understand and support the idea of having a modular approach which allows all kind of setups, I was just wondering is there is a minimal set suitable to my centralized approach?

**Comment by acockburn** [comment]
Yes, this would work fine - you would need to fix the indentation of `listen_to_sensor` to match module and class is all.

Modualrity is there if you want to use it, but is not mandatory if you want to keep all your code in one place.
