### ISSUE TITLE
Callback keyword arguments inconsistent with API documentation

### ISSUE THREAD

**Issue by yawor** [home-assistant/appdaemon#28]
Hi,

I've found that the documentation for callback functions says that the callback should get extra args as a standard python keyword args (**kwargs). Unfortunately this seems to not be true and instead whole kwargs dict is passed as a last positional argument.

For example here's a code that calls callback for event:
```
function(args["event"], data, args["kwargs"])
```
but, to be consistent with documentation, it should be:
```
function(args["event"], data, **args["kwargs"])
```

The same for other calls.

**Comment by acockburn** [comment]
Thanks for pointing that out - I'll fix the docs for the next release.
