### ISSUE TITLE
UID not found: 1000 when running self-built image

### ISSUE THREAD

**Issue by xTCx** [home-assistant/appdaemon#283]
Hi,

I'm trying to run AppDaemon on my RPi3 by building the image myself.
I've followed the [instructions](http://appdaemon.readthedocs.io/en/latest/INSTALL.html), but I'm getting the following traceback while trying to run the image:

## Traceback

```
Traceback (most recent call last):

  File "/usr/local/bin/appdaemon", line 11, in <module>

    load_entry_point('appdaemon==3.0.1', 'console_scripts', 'appdaemon')()

  File "/usr/local/lib/python3.6/site-packages/appdaemon/admain.py", line 374, in main

    admain.main()

  File "/usr/local/lib/python3.6/site-packages/appdaemon/admain.py", line 359, in main

    utils.check_path("config_file", self.logger, config_file_yaml, pathtype="file")

  File "/usr/local/lib/python3.6/site-packages/appdaemon/utils.py", line 207, in check_path

    owner = find_owner(path)

  File "/usr/local/lib/python3.6/site-packages/appdaemon/utils.py", line 163, in find_owner

    return pwd.getpwuid(os.stat(filename).st_uid).pw_name

KeyError: 'getpwuid(): uid not found: 1000'

```

## My Dockerfile:

```
FROM arm32v7/python:3.6

VOLUME /conf
VOLUME /certs
EXPOSE 5050

# Environment vars we can configure against
# But these are optional, so we won't define them now
#ENV HA_URL http://hass:8123
#ENV HA_KEY secret_key
#ENV DASH_URL http://hass:5050
#ENV EXTRA_CMD -D DEBUG

# Copy appdaemon into image
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .

# Install
RUN pip3 install requests && pip3 install .

# Start script
RUN chmod +x /usr/src/app/dockerStart.sh
CMD [ "./dockerStart.sh" ]
```

Everything (git, docker, etc) runs as the `pi` user (UID=1000) so I'm not sure what could possibly be the issue. Also, the reason I'm building the image myself is because the one mentioned in the docs seem to be outdated.

Running Raspbian Stretch Lite, RPi Model B.

Thanks in advance.

**Comment by acockburn** [comment]
Looks like you are building against the dev branch - this is a recently added check hat hasn;t been tested on docker yet and indeed a quick google shows issues in this area, so thanks for reporting it, I'll look into a fix.

For now, if you use the master branch you shouldn't have this issue.

**Comment by acockburn** [comment]
OK, this is now fixed in the dev branch
