### ISSUE TITLE
Docker installation conf file issues

### ISSUE THREAD

**Issue by Kranzy** [home-assistant/appdaemon#291]
I had been trying to get appdaemon to run in docker on a synology for a few days. When following the docs the appdaemon.yaml file below was created. 
`log:`
`  logfile: STDOUT`
`  errorfile: STDERR`
`appdaemon:`
`  threads: 10`
`  plugins:`
`    HASS:`
`      type: hass`
`      ha_url: ha_url_text`
`      ha_key: ha_key_text`
It would run, however dashboard would not be available. I saw a sample config file in a youtube video that i then used as a guide to edit my file by adding the bold lines below.
`log:`
`  logfile: STDOUT`
`  errorfile: STDERR`
`appdaemon:`
`  threads: 10`
**`  app_dir: /conf/apps`**
`  plugins:`
`    HASS:`
`      type: hass`
`      ha_url: http://10.1.1.2:8123`
`      ha_key: R@in2310`
**`hadashboard:`**
**`  dash_url: http://10.1.1.2:5050`**
**`  dash_dir: /conf/dashboards`**
After making  those changes everything seems to be working great. Not sure if there is an error in the code that is causing the file not to be created correctly. I did pass ha_url, ha_key & dash_url as -e variables. 
The appdaemon.yaml file created could not be edited (any changes didn't save) so i created a new file and renamed the old file.

Apologies for the code block formatting.

**Comment by acockburn** [comment]
The issue of the DASH not working in the initial docker setup has now been fixed
