### ISSUE TITLE
appdaemon is trying to import pwd on Windows

### ISSUE THREAD

**Issue by wsw70** [home-assistant/appdaemon#297]
When running `appdaemon` on a fresh Python 3.6.5 on Windows 10, the following Traceback is thrown:

```
C:\Users\yop\dev-perso\domotiqueNG\hass-appdaemon>appdaemon -c .
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\appdaemon.exe\__main__.py", line 5, in <module>
  File "c:\python36\lib\site-packages\appdaemon\admain.py", line 15, in <module>
    import appdaemon.utils as utils
  File "c:\python36\lib\site-packages\appdaemon\utils.py", line 4, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

The `pwd` module is only implemented in Unix (https://docs.python.org/3.6/library/pwd.html)

**Comment by ahmetem** [comment]
maybe change this "user = pwd.getpwuid(os.getuid()).pw_name" to
use Win32::Perms;
 my $username = Win32::Perms->new($filename)->Owner;

**Comment by ahmetem** [comment]
is there any progress on the subject?

**Comment by acockburn** [comment]
Not yet - my day job has been getting in the way. If you want to speed resolution you could submit your fix above as a PR.

**Comment by acockburn** [comment]
I made a change in the dev version, which will be in 3.1.0 that disables the file checking for windows. I don't have the time or the setup to do anything more than that unfortunately. If this works for you great - if not I'll need some help to figure out what further needs to change via a PR. Closing this for now.

**Comment by wsw70** [comment]
The current `dev` version works great on Windows, thank you!
