### ISSUE TITLE
Appdaemon cannot connect to HA - Error: getting metadata  (docker)

### ISSUE THREAD

**Issue by jakubradziwon** [home-assistant/appdaemon#301]
Hi,
lately I've tried to test appdaemon together with HA. As My setup was only for testing I didn't set any HA password. As the docs from appdaemon says [http://appdaemon.readthedocs.io/en/latest/DOCKER_TUTORIAL.html#testing-your-system](appdaemon docker docs) :

> Now, on your Docker host, for linux users, run the following command, substituting the values above in the quotes below. (Note, if you do not need an HA_KEY, you can omit the entire -e HA_KEY line)

I ommited the "HA_KEY". 

After running docker, in logs I saw :

> 2018-05-01 19:39:03.524688 INFO AppDaemon: HASS: Connected to Home Assistant 0.63.1
2018-05-01 19:39:03.530392 WARNING AppDaemon: HASS: Error getting metadata
2018-05-01 19:39:03.530711 WARNING AppDaemon: HASS: Disconnected from Home Assistant, retrying in 5 seconds

Appdaemon did connect to HA (got its version) but didn't work. The problem was in appdaemon config yaml. When i set password (both in HA and AppDaemon) everything was ok. It was also ok, when I commented out password in HA, but in AppDaemon config yaml had to remove empty :

>       ha_key:  <empty>

My conclusion is, when AppDaemon docker is deployed without environment HA_KEY there should be no ha_key in skeleton config yaml.

**Comment by andyinno** [comment]
I don't know if this relates to what I noticed yesterday and posted on home assistant forum: https://community.home-assistant.io/t/solved-home-assistant-upgrade-to-0-68-1-continuous-disconnection/52570

It was related to hassio and an update to the base level that fixed the connection.

Andrea

**Comment by acockburn** [comment]
I think this is a different issue, and needs to be fixed in AppDaemon.

**Comment by acockburn** [comment]
Closing this as we have updated to use Long Lived Tokens.
