### ISSUE TITLE
Proposal: plugin for dbus integration 

### ISSUE THREAD

**Issue by andyinno** [home-assistant/appdaemon#308]
I was thinking about a way to have some functionality of dbus transmitted to home assistant.

The ways I was thinking about are basically:
- dbus => mqtt forwarder
- dbus / appdaemon plugin => home assistant

I was thinking about the second would be a bit more complex to setup but more reliable in the long run.
It could publish states to home assistant about screen locked / unlocked and other amenities that could help to deeper integrate linux systems with home assistant.
For this to work it is needed that appdaemon runs on the same device where dbus daemon is running.

I already made some tests with multiple appdaemon instances connected to the same home assistant and I don't see any drawback with it.

What do you think? Would it be a nice feature to have or am I just overcomplicating the thing and a direct connection via dbus => mqtt would be preferred?

**Comment by acockburn** [comment]
I think this could be a useful plugin - you would need the plugin, then an App to transmit the information to Home Assistant, but for AD, the plus side is that this would work whether or not there was a HASS instance so would add value.

If you want to work on the plugin I'd be happy to merge it when you are done.
