### ISSUE TITLE
appdaemon doesn't load apps when the config path is relative

### ISSUE THREAD

**Issue by alexpirine** [home-assistant/appdaemon#309]
Hi,

I tried to follow the installation guide but I find it very confusing: no matter what I do, nothing happens, my app is not loaded, and I have no error message.

I am using a Raspberry Pi with hassbian on it.

I installed appdaemon with pip3:

```console
$ pip3 freeze|grep appdaemon
appdaemon==3.0.1
```

I created a `conf` folder as advised and wrote some configuration in `appdaemon.yaml`:

```console
$ pwd
/home/homeassistant/.homeassistant/conf
$ ls -l
-rw-r--r-- 1 homeassistant homeassistant  333 May 10 09:56 appdaemon.yaml
drwxr-xr-x 2 homeassistant homeassistant 4096 May 10 10:11 apps
$ cat appdaemon.yaml 
log:
  accessfile: /home/homeassistant/logs/access.log
  errorfile: /home/homeassistant/logs/error.log
  logfile: /home/homeassistant/logs/appdaemon.log
  log_generations: 3
  log_size: 1000000
appdaemon:
  threads: 10
  plugins:
    HASS:
      type: hass
      ha_url: http://hassbian.local:8123
      ha_key: mykey
```

I also created a “hello world” app with the associated YAML file:

```console
$ ls apps
apps.yaml  hello.py
```

```yaml
# apps/apps.yaml
hello_world:
  module: hello
  class: HelloWorld
```

```python
# apps/hello.py 
import appdaemon.plugins.hass.hassapi as hass

#
# Hello World App
#
# Args:
#

class HelloWorld(hass.Hass):

  def initialize(self):
     self.log("Hello from AppDaemon")
     self.log("You are now ready to run Apps!")
```

But nothing happens when I run appdaemon:

```console
$ appdaemon -c .

```

And not much going on in the logs:

```
$ tail -f /home/homeassistant/logs/*
==> /home/homeassistant/logs/appdaemon.log <==
2018-05-10 10:21:21.049373 INFO AppDaemon Version 3.0.1 starting
2018-05-10 10:21:21.050413 INFO Configuration read from: ./appdaemon.yaml
```

I also tried doing other things in `hello.py`, like using the `print` statement, or turning a light on or off, but none of it manifested in real life…

Am I doing something wrong?

**Comment by alexpirine** [comment]
It always surprises me how writing an issue often magically solves it.

It turns out `appdaemon -c` wasn't happy with relative paths. It prefers absolute ones:

```console
$ appdaemon -c `pwd`
```

```console
$ tail -f /home/homeassistant/logs/*
==> /home/homeassistant/logs/appdaemon.log <==
2018-05-10 10:28:42.536288 INFO AppDaemon Version 3.0.1 starting
2018-05-10 10:28:42.537111 INFO Configuration read from: /home/homeassistant/.homeassistant/conf/appdaemon.yaml
2018-05-10 10:28:42.542272 INFO AppDaemon: Starting Apps
2018-05-10 10:28:42.544160 WARNING config_dir: /home exists, but is not writeable, owner: root
2018-05-10 10:28:42.557661 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-05-10 10:28:42.592577 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-05-10 10:28:42.593757 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-05-10 10:28:42.594812 INFO Dashboards are disabled
2018-05-10 10:28:42.595364 INFO API is disabled
2018-05-10 10:28:42.612178 INFO AppDaemon: HASS: Connected to Home Assistant 0.68.1
2018-05-10 10:28:42.688271 INFO AppDaemon: Got initial state from namespace default
2018-05-10 10:28:44.912835 INFO AppDaemon: Reading config
2018-05-10 10:28:44.919797 INFO AppDaemon: /home/homeassistant/.homeassistant/conf/apps/apps.yaml added or modified
2018-05-10 10:28:44.920518 INFO AppDaemon: /home/homeassistant/.homeassistant/conf/apps/apps.yaml added or modified
2018-05-10 10:28:44.921102 INFO AppDaemon: App 'hello_world' added
2018-05-10 10:28:44.921816 INFO AppDaemon: Adding /home/homeassistant/.homeassistant/conf/apps to module import path
2018-05-10 10:28:44.922957 INFO AppDaemon: Loading App Module: /home/homeassistant/.homeassistant/conf/apps/hello.py
2018-05-10 10:28:44.946085 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2018-05-10 10:28:45.146684 INFO hello_world: Hello from AppDaemon
2018-05-10 10:28:45.150226 INFO hello_world: You are now ready to run Apps!
2018-05-10 10:28:45.152143 INFO AppDaemon: App initialization complete
```

I'm changing the title…

**Comment by manojjenago** [comment]
Hi ,

I have a similar issues where I am running HASS.IO.

I have the 
appdaemon.yaml
with the following:
secrets: /config/secrets.yaml
log:
  logfile: STDOUT
  errorfile: STDERR
appdaemon:
  threads: 10
  app_dir: /config/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://localhost<IP>:8123
      ha_key: Welcome1
hadashboard:
  dash_url: http://localhost<IP>:5050
  dash_dir: /config/appdaemon/dashboards

In my app dir 
 app_dir: /config/appdaemon/apps

apps.yaml , hello.py and flashLight.py files are there

in apps.yaml 
-------------------------------------------
hello_world:
  module: hello
  class: HelloWorld

flash_Light:
  module: flashLight
  class: FlashyMotionLights  

----------------------------

and in flashLight.py
---------------------


import appdaemon.appapi as appapi
#import appdaemon.plugins.hass.hassapi as hass

#class FlashyMotionLights(hass.Hass):
class FlashyMotionLights(appapi.AppDaemon):

  def initialize(self):
    self.listen_state(self.motion, "sensor.sn1_pir", new = "on")
  
  def motion(self, entity, attribute, old, new, kwargs):
    if self.sun_down():
      self.turn_on("light.sn1_led")
      self.run_in(self.light_off, 10)
  
  def light_off(self, kwargs):
    self.turn_off("light.sn1_led")

and in hello.py
-----------
import appdaemon.plugins.hass.hassapi as hass

#
# Hellow World App
#
# Args:
#

class HelloWorld(hass.Hass):

  def initialize(self):
     self.log("Hello from AppDaemon")
     self.log("You are now ready to run Apps!")

But I can not see any thing in dash board .. please suggest
Thanks,
MJ

**Comment by ReneTode** [comment]
this is completely unrelated, because its hassio and you dont start AD with a commandline.
dashurl shouldnt be localhost in hassio, but because its 24 days ago posted i guess this issue is closed.

**Comment by zenitraM** [comment]
I think this is still a bug, or at least confusing behavior (same thing happened to me as on https://github.com/AppDaemon/appdaemon/issues/1192 which also mentioned).

When setting up appdaemon outside Docker/hassio/etc, you can't call `appdaemon -c .` from the configuration folder - it will just ignore all apps unless you pass an absolute folder, or at least one not starting by `.`. 
Haven't seen anything on docs regarding this limitation, which I think could be confusing by someone just getting started - at least it was for me.

**Comment by ReneTode** [comment]
i think for someone just gettin started its easier to give the full path then to go to the right dir with CD and then use the dot version.
the examples in the docs are also all with full path.

i dont think its a bug (unless Andrew intended to have relative paths as option)
but in the docs it could state that it needs to be an absolute path.

unless someone takes the time to find out and add the option to use relative paths.

**Comment by ported-pw** [comment]
I will just say that I just ran into this as well and spent a solid hour googling to find out why I was getting an error about missing app descriptions. It loads the python modules fine, but does not find the `.yaml` files. I think generally unless specified otherwise, relative paths are expected to work when given to programs so this was confusing to me.

**Comment by rct** [comment]
I know this is closed but I just ran into the same thing:

`appdaemon -c .`  saw my `apps` directory but ignored the `.py` files because it didn't read `./apps/apps.yaml` 

Glad I found this after only 5-10 minutes of googling.
