### ISSUE TITLE
Stock Price Alert notification 

### ISSUE THREAD

**Issue by manojjenago** [home-assistant/appdaemon#312]
Hi ,

I am trying to automate a process where I can set a price limit for a stock and will get a notification on phone if that price is met or below. I am not sure how to get it done. 

Hopefully someone will guide me in right direction.

Thanks,
Manoj

**Comment by acockburn** [comment]
Please ask this kind of question on the homeassistant forum.

**Comment by manojjenago** [comment]
Thanks
