### ISSUE TITLE
Configuring New Apps in Appdaemon

### ISSUE THREAD

**Issue by manojjenago** [home-assistant/appdaemon#314]
Hi,

I have crated a files called flashLight.py , hello.py and apps.yaml under "\\HASSIO\config\appdaemon\apps" folder

And apps.yaml has below content

> hello_world:

  module: hello
  class: HelloWorld

flash_Light:
  module: flashLight
  class: FlashyMotionLights  

Now I am not seeing any thing on my dashboard.

I create a Automation.dash under "\\HASSIO\config\appdaemon\dashboards"
has content 

> 

# Main arguments, all optional
#
title: Flashlight
widget_dimensions: [122, 120]
widget_margins: [5, 5]
columns: 8
#skin = green
#
# Includes (Optional)
#
layout:
    - include: /config/apps/apps

But I can not see anything in my dash board. Only the Automation link is showed but a blank file ...with nothing inside it..
Please suggest ...How can I link my automation to dashboard ...??

Thanks,
MJ

**Comment by acockburn** [comment]
Please ask this question on the HASS forum.

**Comment by manojjenago** [comment]
Thanks for guiding, I use the HASS forum.
