### ISSUE TITLE
Update MDI icons

### ISSUE THREAD

**Issue by grm** [home-assistant/appdaemon#316]
Hello,

I wanted to know if it was possible to update the material design icons. I wanted to use the mdi-set-top-box, but the icon does not appear. I am using the AppDaemon Version 3.0.1.

I think it is a mdi version issue as i could not find it in the CSS.

Thanks for the great work.

**Comment by grm** [comment]
I created a pull request to help : https://github.com/home-assistant/appdaemon/pull/317

**Comment by acockburn** [comment]
Thanks - I've been planning to do this but have been holding back as it will introduce breaking changes to many users since the icon names changed, and I was breaking enough things during the 3.0 beta as it was. I'll merge the PR in the next release.
