### ISSUE TITLE
AppDaemon 3.x vs Home Assistant 0.68.1: The Battle over aiohttp 2.x and 3.x

### ISSUE THREAD

**Issue by ahmetem** [home-assistant/appdaemon#318]
appdaemon 3.0.1 has requirement aiohttp==2.3.10, but you'll have aiohttp 3.1.3 which is incompatible.

When trying to upgrade Home Assistant to 0.68.1 I get this error:
homeassistant 0.68.1 has requirement aiohttp==3.1.3, but you'll have aiohttp 2.3.10 which is incompatible.

Anyone else experience this interesting conflict? Shouldn’t the latest version of HA be compatible with the latest version of AppDaemon?

**Comment by Odianosen25** [comment]
@ahmetem, You need to install AppD in  a virtual environment separate from HA. Either using docker or a python virtual environment

**Comment by Odianosen25** [comment]
Well true @petersohn

**Comment by ReneTode** [comment]
@petersohn  installing appdaemon in a seperate environment is not a workaround but an adviced way to work.
Allthough Andrew always tried to keep it compatible it is almost impossible to make sure it is compatible.
HA releases new versions every 2 weeks and they change libs when they think they need it.
it is impossible to keep the libs in sink with all HA versions at all time unless Andrew also starts releasing every 2 weeks and AD gets a version that is compatible with a specific HA version.

so if Andrew for whatever reason decides to use another version from a lib then HA does, he is free to do so, and users have to deal with it appropriatly.

**Comment by acockburn** [comment]
I'll upgrade to the new aiohttp when a need arises, but as has been stated here, appdaemon and hass are 2 different packages and are not mutually dependent in any way so there is no requirement to synch package versions, that would be a huge amount of work. Virtual Environments are the answer here.
