### ISSUE TITLE
1.5.1 Doesn't like Dev

### ISSUE THREAD

**Issue by mezz64** [home-assistant/appdaemon#32]
Looks like the new version pull/check doesn't account for someone running a dev build of HASS.  Not sure the best way to handle the fix since you want to check against the version to determine whether or not to use websockets.

```bash
2017-01-30 08:51:47.626748 INFO AppDaemon Version 1.5.1 starting

Traceback (most recent call last):
File "/usr/local/bin/appdaemon", line 11, in <module>
load_entry_point('appdaemon==1.5.1', 'console_scripts', 'appdaemon')()
File "/usr/local/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 1250, in main
conf.version = int(ha_config["version"].replace(".", ""))

ValueError: invalid literal for int() with base 10: '0380dev0
```

**Comment by acockburn** [comment]
Thanks for pointing this out - I already have an undocumented argument to force Websockets or EventStream - I will make this mandatory in the event I can't figure it out from the version e.g. in the case of a dev version like this.

It will take me a few days to get to this as I am traveling on business, let me know if it is urgent and I can give you a manual fix in the meantime.

**Comment by acockburn** [comment]
Or I could probably assume that if it is a dev version it is > 0.34 ...

**Comment by mezz64** [comment]
No need to provide me a fix, I already forked this morning to correct the error and updated my docker.  I'll move everything back to this repo once you get a chance to fix it.

**Comment by acockburn** [comment]
Cool - I figured since you were playing with a dev version you would be able to figure out a fix :) I'll leave this open until I fix it in the net release.

**Comment by acockburn** [comment]
Fixed in next release
