### ISSUE TITLE
Sunrise/sunset alternative geo locations

### ISSUE THREAD

**Issue by jacobtomlinson** [home-assistant/appdaemon#320]
It would be great if you could provide the sunrise/sunset callbacks and helper functions a location to allow writing automations which behave as if they were at a different global location.

The example I have in my mind is automating the artificial lighting for my tortoise. I am trying to simulate a warmer climate for him and so I would like his lights to come on and off with sunrise and sunset at a lower latitude, like Athens rather than London. 

I imagine the functions pick up the lat and lon from the HASS home location config and use those to calculate the sunrise/sunset times, so hopefully it would be a case of adding kwargs to override those values.

I'll start looking through the code to see if I can raise a simple PR to fix it, but as a first time contributor to appdaemon I would appreciate help from someone with a better knowledge of the project.

**Comment by ReneTode** [comment]
i dont know if it would work, but there is an option to set the longtitude and latitude in the appdaemon.yaml
AD should take that settings and not the HA settings when they are entered.
so i guess you need to try out if that is the solution for you.

**Comment by jacobtomlinson** [comment]
Thanks for the response! I only want to set the different location for a single automation, your workaround would end up changing it for everything.

**Comment by ReneTode** [comment]
in that case i suggest an app to create your own sun sensor.
how to calculate sunset and sunrise on specific locations can be found here:
https://stackoverflow.com/questions/19615350/calculate-sunrise-and-sunset-times-for-a-given-gps-coordinate-within-postgresql
with run_at you can update your sensor(s) at the needed time(s) and then use a listen_state for the sensor(s)

an app like:
```
def init(...):
  self.update_sunset(self)
  self.update_sunrise(self)

def update_sunset(self,kwargs):
  #calc next sunset
  self.set_state("sensor.my_sunset", state = next_sunset)
  self.run_at(self.update_sunset, next_sunset)

def update_sunrise(self,kwargs):
  #calc next sunrise
  self.set_state("sensor.my_sunrise", state = next_sunrise)
  self.run_at(self.update_sunrise, next_sunrise)
```

**Comment by jacobtomlinson** [comment]
Thanks for the suggestion! Is that code not already in appdaemon somewhere? Perhaps I could just use it rather than re-implementing it. Or does appdaemon use the sunrise/sunset triggers from home assistant?

**Comment by ReneTode** [comment]
i am not sure, i would need to dig into the AD code to find that out for sure.

but there are 2 things i always keep in mind when i create apps:
1) i try to avoid changing AD code at all time, because you lose the option to upgrade easy
2) i only ask andrew to input something in AD if i think that there is a use for it for a greater group of people, in most cases i just write an app and share it. if it gets used by more people it is time to think about implementing it.

there are reasons for that
a) we dont want to overcomplicate AD with stuff that is rarely used
b) there is more then enough stuff that needs to be done and Andrew only has 1 life ;)

**Comment by jacobtomlinson** [comment]
That all sounds reasonable thanks.
