### ISSUE TITLE
Enable secrets in apps.yaml

### ISSUE THREAD

**Issue by eifinger** [home-assistant/appdaemon#328]
I couldn't find an issue about this.
Would it be possible to have secrets in apps.yaml not just appdarmon.yaml?
I am sharing my code on GitHub and want to hide some names of sensors, zones etc.

**Comment by ReneTode** [comment]
i think that will be a difficult thing to do (if not i think Andrew would have implemented that)
secrets and appdaemon.yaml are static settings. they dont change and dont get reloaded and reexamined when code or yaml from apps are changed.
the yaml from apps (formaly apps.yaml) isnt static and is examined all the time.

you could use a global settings file and not share that. (dont forget to comment that you use it and what is in it ;) )
in the meantime Andrew can think about if it is possible.

**Comment by eifinger** [comment]
If anyone comes across this issue with the same idea, here is how I implemented my workaround:
https://github.com/eifinger/appdaemon-scripts#globals-and-secrets

**Comment by acockburn** [comment]
I think that is a bettor solution than support for secrets in apps.yaml, so closing.
