### ISSUE TITLE
iFrame - Obsidian skin

### ISSUE THREAD

**Issue by MPopti0n** [home-assistant/appdaemon#331]
Hi!

Hassio 0.72.0 running on RPI3 with appdeamon up to date
Context ::
HA dashboard with obsidian skin on iFrame widget

I was wondering if it's possible (and how) to override the skin backgroud (not the color, that I know how! but the half white upper tingy) because it makes the image all blurry

![sans titre 2](https://user-images.githubusercontent.com/36873863/41818005-1ea6ac0e-7774-11e8-8c46-b872ebb42556.jpg)

**Comment by ReneTode** [comment]
its a part from the widget_style.
so you need to override that part from the css.

in the widget in the dashboard you should use stuff like:
```
widget_style: background-image: None; border-style: None"
```
i dont know if that is a shadow, or border part. you need to look in the console to find out which part from the css should be set off.

**Comment by MPopti0n** [comment]
Thanks, found the lines but I can't figure out what to put in the `.dash` file to override it ::

```
.widget:after{
  position: absolute;
  content: ' ';
  width: 100%;
  height: 50%;
  top: 0;
  left: 0;

  -webkit-border-radius: 15px;
  -moz-border-radius: 15px;
  border-radius: 15px;

  background: -moz-linear-gradient(top, rgba(90,90,255,0.4) 0%, rgba(255,255,255,.2) 100%);
  background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(90,90,255,0.4)), color-stop(100%,rgba(255,255,255,.2)));
  background: linear-gradient(top, rgba(90,90,255,0.4) 0%,rgba(255,255,255,.2) 100%);}
}

```
It's those 3 last `background:` lines

**Comment by ReneTode** [comment]
sorry. that is a problem from the skin.
at this moment i see no way to take it out without taking it out everywhere in the skin or you need to start editing the skin itself. (but even then i think it will be very hard)

**Comment by MPopti0n** [comment]
Haha. I'm not that dumb than, because I have tried a whole bunch of things and nothing was working. Thanks for your time! 👍
