### ISSUE TITLE
Use icons from HA zone config in device tracker widget

### ISSUE THREAD

**Issue by epruesse** [home-assistant/appdaemon#336]
The `zone` configuration in HA allows setting an icon. While the states of `device_tracker` entities contain the zone name as text, not the object, it would be neat to use that icon in the `device_tracker` widget.

**Comment by ReneTode** [comment]
you can use the icon widget for that.

**Comment by acockburn** [comment]
I agree with Rene - Icon widget should work well for that usecase.
