### ISSUE TITLE
"Entities" created using `self.set_app_state()` gets deleted

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#339]
Hello,

I have noticed that when I create entities using the `self.set_app_state()` function, it is created as required. My issue is that after a while, this entities are no longer available in AD and I would have also lost all my data within it.

Please can it be ensured this remains and its not deleted? I think its because the plugins are made to reload their entities every 10 mins, and this means entities not stored in the plugin or those created only within AD gets deleted.

Thanks and regards

**Comment by Odianosen25** [comment]
Created a pull request to correct this here #341 

Regards

**Comment by Swamp-Ig** [comment]
Put a comment on the pull. It's not as straight-forward as all that unfortunately.

**Comment by Odianosen25** [comment]
Pull requested been added. Thanks @acockburn and closing this
