### ISSUE TITLE
Error with installing "PyYAML-4.1-cp35-cp35m-linux_armv7l.whl"

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#343]
I am trying to setup a new system with AppD, and I am getting the error while it is trying to install "PyYAML-4.1-cp35-cp35m-linux_armv7l.whl". Looking at the link where its trying to download it, there seems the file isn't existing for some reason [here](https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff).

So how do I get out of this, or is there any other alternative I have except using docker?

Regards

**Comment by Odianosen25** [comment]
@ReneTode, I just tried it and its same issue.

Here are the errors:
```
HTTP error 404 while getting https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
  Could not install requirement pyyaml from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff because of error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl
Could not install requirement pyyaml from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff because of HTTP error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl for URL https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
```

**Comment by ReneTode** [comment]
i search on google and found that there is a pyyaml issue.

a workaround that i saw that people reported as working is:

pip3 install git+https://github.com/yaml/pyyaml.git

**Comment by Odianosen25** [comment]
Many thanks @ReneTode, but even though I have it installed, it still goes out to look for it, an spits out the errors.

So I had to use my folk, where I had removed the `pyyaml` from the `setup.py` file.

Many thanks for the help.

Kind regards
