### ISSUE TITLE
Revice feature request #276 isten_state numeric_state below or above

### ISSUE THREAD

**Issue by deisi** [home-assistant/appdaemon#358]
Searching for an elegant way of listening for nummeric state changes in appdeamon I found that there is no straight forward way of doing something like #276 . Plz correct me if I'm wrong here.

I see the point in not reimplementing everything, but I would like to reconsider not implementing this specific feature. The point is, that one can't create an equal trigger easily with appdaemon if you have a noisy sensor, that you want/need to use.
A simple get state and if else, would do it. You would need to manually compare new and old state, to see if a certain threshold was passed and also track the duration of when it happend. 

I think currently the best way of doing it is a kind of hybrid solution. Create a boolean sensor in HA that switches when the nummeric state changed and then use appdeamon to pick it up. From my point of view this looks awkward. One of the reasons why I started to use appdeamon was, that I found myself creating dozens of virtual sensors and switches in HA to implement "easy" tasks.

**Comment by Odianosen25** [comment]
Hell @deisi,

Well I get your point, but one could use constraints as @acockburn had highlighted in the referenced issue. I newly started using it and I think its cool. 

Besides constraints, now HA has nice sensors that help to consume others to be used for what you want. Like Filter, Statistics and Max/Min. With these, there is honestly no need of bloating up appdaemon in my opinion as you can just set these ones up in HA and let that be HA's headache and you up and running.

Regards

**Comment by ReneTode** [comment]
creating virtual sensors isnt needed at all.
just use AD to create and update sensors.

elegance is always in the eyes of the beholder.
checking if a numeric sensor gets over a certain threshhold is just a few lines of code.
if you want to use that often then you can create your own general function for it.

is it more elegant when the few lines are inside appdaemon itself or in a general function?
i dont think so. 
with creating your own function you have more flexibility.
but when its added to the listen_state then EVERY listen_state will get another check and so EVERY listen_state will be slower. (its also a few microseconds, but there are more things that can be implemented like that, and in the end it adds up)

creating a boolean sensor in HA can be done by:
```
  self.set_state("sensor.boolean", state=True)
```

**Comment by deisi** [comment]
Okay, thanks for the tips of how to implement this else. I close this then.

**Comment by runningman84** [comment]
btw. this is my sample app to implement a numeric state sensor...
```
import appdaemon.plugins.hass.hassapi as hass

#
# NumericStateSensor App
#
# Args:
#

class NumericStateSensor(hass.Hass):

    def initialize(self):
        self.log("Hello from NumericStateSensor")

        # setup sane defaults
        self.__sensor_src = self.args.get("sensor_src", None) # myfancysensor
        self.__sensor_dst = self.args.get("sensor_dst", None) # mysensor.boolean
        self.__mode = self.args.get("mode", None) # above, below
        self.__threshold = self.args.get("threshold", None)

        self.listen_state(self.sensor_change_callback, self.__sensor_src)


    def sensor_change_callback(self, entity, attribute, old, new, kwargs):
        self.log(
            "Callback sensor_change from {}:{} {}->{}".format(entity, attribute, old, new))

        if (self.__mode == "above"):
            if (new > self.__threshold):
                 new_state = True
            else:
                 new_state = False

        if (self.__mode == "below"):
            if (new < self.__threshold):
                 new_state = True
            else:
                 new_state = False

        if (self.get_state(self.__sensor_src) != new_state):
              self.set_state(self.__sensor_dst, state=new_state)

```
