### ISSUE TITLE
Multiple "plugin_restarted" event

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#374]
When using multiple plugins, when a single plugin restarts, one gets the event multiple times the number of plugins in use.

Regards

**Comment by ReneTode** [comment]
add which event you get multiple times and Andrew will know where to look ;)

**Comment by Odianosen25** [comment]
Ok thanks @renetode. 

The event is “plugin_restarted”, and it’s fired globally for each of the plugins, across all apps, even if it’s just one that restated.

Regards

**Comment by acockburn** [comment]
Looks like this is working as designed - plugin_started events are global so will go to any namespace. If you have 7 apps with 7 namespaces they will each get a copy of the event if they are listening. I have cleaned up the code a little and I am reconsidering making the event global - that should be the choice of the app.
