### ISSUE TITLE
Appdaemon broken in 0.80.0

### ISSUE THREAD

**Issue by tkwatson63** [home-assistant/appdaemon#384]
After upgrading from 0.79.2 to 0.80.0 I am getting the following in appdaemon.log 3 times before being banned from HA.

WARNING AppDaemon: HASS: Error in authentication

I have been using the "Legacy" workaround until now. Has there been any progress on implementing OAuth 2 into AD? If so, HOW? I cannot find anything on the forums or in the docs.

**Comment by ReneTode** [comment]
no the new auth isnt implemented in HA yet.
Andrew is working on that.
but they didnt report any breaking changes in the blog, so it should still work.
so better take this up on the forum, or discord.

**Comment by grewhit25** [comment]
Appdaemon 3.0.1 works find for me on HA release 0.80.0 using the legacy API.
Just double check you config making sure that your api_pasword is not located in a package and is also in your appdaemon.yaml file. 

You could also have a look at your ip.bans.yaml file in your config directory that will give you a clue as to which IP/s are the culprit. You may have to trust that network, take a look at [Authentication Providers Trusted Networks](https://www.home-assistant.io/docs/authentication/providers/#trusted-networks).

Once you are happy you can delete the contents of ip_bans.yaml, then restart HA may fix your problem.

**Comment by tkwatson63** [comment]
Thanks Greg, the issue was that I had a http.yaml package. Moved contents into configuration.yaml, restarted HA and AD and life got better. After hours of searching yesterday I could not find anywhere that indicated that http should not be a package. It worked fine in 0.79.2 so when it broke after upgrading to 0.80 I assumed the upgrade broke AD. Sorry for the chicken little moment.
