### ISSUE TITLE
self.listen_log doesnt show everything

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#387]
when using self.listen_log only the log entries created in apps with self.log or self.error get returned.
errors that appear in the errorlog (like sybtaxerror) are not reported by the listen_log
same for all logentries created by appdaemon itself (like termiting and initialising app, or warnings)

**Comment by acockburn** [comment]
This was by design, however in 3.0.2, AppDaemon messages are no longer filtered, and you can set a log level to avoid getting hundreds of DEBUG messages!
