### ISSUE TITLE
set_value doesn't appear to work

### ISSUE THREAD

**Issue by bachya** [home-assistant/appdaemon#388]
Using version 3.0.1. I have an input select that I'm working with. This:

```
self.set_value('input_number.master_bathroom_fan_timer', 5)
```

...doesn't produce any change in HASS. This, however:

```
self.call_service(
    'input_number/set_value',
    entity_id='input_number.master_bathroom_fan_timer',
    value=5)
```

...works as expected.

**Comment by acockburn** [comment]
Hi there - I already have a fix for this in the next version.
