### ISSUE TITLE
Python module search path in Docker container

### ISSUE THREAD

**Issue by sebk-666** [home-assistant/appdaemon#440]
Hi,

I just dropped my ancient appdaemon version and updated to the latest one using the official Docker image, starting from scratch.
I wanted to run the `switch_reset.py` example app and it did throw an error `ModuleNotFoundError: No module named 'hassapi'`.

I was able to fix it by changing 
`import hassapi as hass`
to
`import appdaemon.plugins.hass.hassapi as hass`

So it looks like Python's module search path is missing some elements.
Did I miss a configuration setting that I should have applied?

Sebastian

**Comment by Odianosen25** [comment]
Hello @sebk-666 ,

`import hassapi as hass` is a new feature yet to be released. So you are good.

Still use the old one for now, but once 4.0 is released, the new one can be used.

Regards

**Comment by sebk-666** [comment]
Ah, I see, thanks!
I was downloading the switch_reset.py directly from the git repo.
Just checked the version provided within the conf/example_apps directory in the container and this one looks like my fixed version.
Should have looked there first... ;)

Sebastian
