### ISSUE TITLE
-p PIDFILE should be possible without the -d argument

### ISSUE THREAD

**Issue by sj3fk3** [home-assistant/appdaemon#442]
When starting AppDaemon it's only possible to create a pidfile when also using the -d (daemonize) argument. When using something like systemd or upstart the -d argument is not really desirable. I would like to be able to use the PID and start AppDaemon with systemd (so without -d).

**Comment by ReneTode** [comment]
you also just could have waited for an answer from Andrew on the forum.
why bother him twice?
you wont get a faster answer when you ask the same question on several places.

**Comment by sj3fk3** [comment]
> you also just could have waited for an answer from Andrew on the forum.
> why bother him twice?
> you wont get a faster answer when you ask the same question on several places.

It's a feature request..

**Comment by acockburn** [comment]
Looking to add this in 4.0

**Comment by acockburn** [comment]
Question: From my research, pidfile is only usefule in a systemd setting if the intention is to have systemd track multiple processes that the daemon created. AppDaemon is a single process, no forks, so what would be the benefit of the pidfile option since systemd should be able to track the main (and only) process perfectly well without it?

**Comment by sj3fk3** [comment]
I would like the PID file for [monit](https://mmonit.com/). While I start (and stop) appdaemon with systemd (and therefore cannot use the -d option), I would like to monitor it with monit. It can look for stuff like the infamous thread starvation in logfiles, stalled processes etc.. I've had those a couple of times and monit can save me out of these situations (by restarting the process).

**Comment by acockburn** [comment]
This has been added in the latest dev and will be in 4.0
