### ISSUE TITLE
Entity Callback for Set_state not called when executed immediately after another

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#453]
AD version 4.0b1

I just noticed that when I have something like the below

```
self.set_state(entity, state = 'Response', attributes = attribute)
self.set_state(entity, state = 'Task Completed')
```

Before both used to be  executed one after the other, and their respective callbacks are called one after the other

But now, the first though executed and from the Admin interface I can see the data is stored within the entity, its callback in another app is not processed and is totally omitted, but the second one is executed. Its like the second one over writes the first and the callback for the first never gets called
This is a recent issue
This is happening in MQTT namespace, which has no set_plugin_state in the plugin to execute

Regards

**Comment by acockburn** [comment]
Fixed in async branch will be pushed to dev in a day or two
