### ISSUE TITLE
docker build is failing

### ISSUE THREAD

**Issue by marcelveldt** [home-assistant/appdaemon#458]
Hi, I'm using your dockerhub image for appdaemon but it seems that it is failing to build for some time.
I want to update to 3.1 as it fixes an issue I have but the current docker build is stuck at 3.02.

**Comment by acockburn** [comment]
3.0.2 is the latest production version of AppDaemon

**Comment by marcelveldt** [comment]
Ah, that explains it... I was experiencing an issue and in the replies was a comment that the issue was fixed in version 3.10 (on November 12th) so I tried upgrading but did not look any further. Thanks. I'll just be patient and in the meanwhile I'll workaround the issue.

**Comment by acockburn** [comment]
I think that may have been because I was planning on releasing a 3.1.0 then decided to jump to 4.0 and release a beta - which issue was this?

**Comment by marcelveldt** [comment]
this one:
https://github.com/home-assistant/appdaemon/issues/185

**Comment by acockburn** [comment]
OK, yep, 3.1.0 became 4.0 and when it is released that fix will be in there. If you are feeling adventurous you could take a look at the current dev version but there are several breaking changes in there ...

**Comment by marcelveldt** [comment]
thanks, I'll wait for the 4.0 release. I've worked around the issue now with an additional timer for the state change. Works for now. Great work with this project btw, I've written a lot of apps to completely automate my house and replaced 10000's lines of yaml craziness... Thanks!
