### ISSUE TITLE
empty event raises an unexpected error

### ISSUE THREAD

**Issue by wsw70** [home-assistant/appdaemon#460]
I use AppDaemon to log events when debugging HA, by creating a simple app:

```
import appdaemon.plugins.hass.hassapi as hass

class Logger(hass.Hass):

    def initialize(self):
        self.listen_event(self.print_log)

    def print_log(self, event_name, data, kwargs):
        self.log(event_name)
        self.log(data)
```

I tested this by firing an empty event in HA (in Dev Tools -> Events -> Event type: state_changed). Thsi raised an unexpected error in my log:

```
2018-12-29 18:34:33.112786 WARNING AppDaemon: ------------------------------------------------------------
2018-12-29 18:34:33.113169 WARNING AppDaemon: Unexpected error during process_event()
2018-12-29 18:34:33.113390 WARNING AppDaemon: ------------------------------------------------------------
2018-12-29 18:34:33.114035 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/appdaemon/events.py", line 83, in process_event
    entity_id = data['data']['entity_id']
KeyError: 'entity_id'

2018-12-29 18:34:33.114513 WARNING AppDaemon: ------------------------------------------------------------
```

**Comment by acockburn** [comment]
OK, this should never happen in a normal system ;) What would you expect the result to be - log a message and drop the event?

**Comment by ReneTode** [comment]
i think this is a HA issue.
HA should never fire the event state_changed when no entity is specified.

**Comment by wsw70** [comment]
@acockburn : I forgot to mention that I am the master of abnormal systems :)

I believe that just issuing a warning that the entity is missing in the event would be fine - to avoid the frightening `Unexpected error`

**Comment by wsw70** [comment]
@ReneTode in that case I just used the development tools provided by HA and issued a (possibly nonsensical but allowed nevertheless) event.

While this should never happen in normal life, the interface allows for such cases so I believe that they should be handled, to avoid as I mention earlier the terrifying `Unexpected error`

**Comment by ReneTode** [comment]
its an issue you should raise with HA.

it is possible but it shouldnt be possible.

**Comment by acockburn** [comment]
OK, I'll add some checking and a warning

**Comment by acockburn** [comment]
Fixed in the latest dev version
