### ISSUE TITLE
OrangePI Instalation

### ISSUE THREAD

**Issue by lourivalbarreto** [home-assistant/appdaemon#463]
Hi Andrew,

Congratulations for your jobs... its very useful!
I'm using the OrangePI PC+ (armhf platform) to run my HA, MQTT, etc. 
Is the acockburn/appdaemon image compatible with ARMHF platform?

Thanks!
Jose

**Comment by acockburn** [comment]
It depends on your installation method - you didn't say. For pip3, the PyPi install should work fine. For Docker, no, only a Linux image is available. There are instructions for Radpberry Pi in the docs:

https://appdaemon.readthedocs.io/en/latest/INSTALL.html#raspbian

They should work for Ornage Pi although I have never tried it.
