### ISSUE TITLE
visibility of apps across plugins

### ISSUE THREAD

**Issue by thomasdelaet** [home-assistant/appdaemon#465]
Hey,

I have 2 plugins configured: HASS and MQTT.

I'm trying to change the status of an input_boolean in home assistant based on an MQTT message received but can't seem to make that work.

The way that I've modelled this:
- One app that uses MQTT plugin
- Another app that uses HASS plugin
- The MQTT app uses get_app to retrieve the other app and then executes function.

However, get_app returns None even though I'm 100% sure the app exists. I've tried:
- using set_namespace before the get_app
- specifying the HASS app as dependency (which gives a message that the dependency does not exist)

Any ideas?

Thanks.

Thomas

**Comment by ReneTode** [comment]
the most easy way to do it is to use only HASS plugin and get the stuff from the mqtt plugin by using set_namespace or using namespace.
you also can use get_app from the hass plugin into the mqtt plugin app, but not everything is perfect with the mqtt plugin in 3.0.2

working with plugins will be changed quite a bit in the next release. and it will make things a lot easier.
untill then, my advice is to inherit from HASS when you want hass stuff at all, andget data from mqtt into the hass app.

**Comment by thomasdelaet** [comment]
Thanks Rene for your fast response. This works for now :-) Looking forward to changes.
