### ISSUE TITLE
Feature request: Adding context for stage changes

### ISSUE THREAD

**Issue by thomasdelaet** [home-assistant/appdaemon#473]
Hey,

I noticed it's not possible to subscribe to state_changed events from home assistant since these are filtered out before and need to be captured with listen_state.

However, listen_state does not pass on the context (user_id, context_id). I solved this locally by also generating an event for state_changed events but maybe this can be incorporated in the callback data from listen_state?

Happy to do a PR if others find this useful.

**Comment by acockburn** [comment]
For now I prefer the approach of firing the state changed events locally- a PR for that would be helpful, thanks!

**Comment by acockburn** [comment]
Closing this as we now have a PR
