### ISSUE TITLE
Logging API doesn't match python logging

### ISSUE THREAD

**Issue by TD22057** [home-assistant/appdaemon#476]
I tried to do this:
```
    def initialize(self):
        for dev in self.args['devices']:
            self.log("Tracking %s", dev)
```
yields:
```
  File "/opt/appdaemon/lib/python3.6/site-packages/appdaemon/utils.py", line 161, in log
    logger.log(levels[level], "{} {}{} {}".format(timestamp, level,
KeyError: 'device_tracker.ted'
```

Seems wrong to me since python allows:
```
logging.error( "foo %s", "asdf" )
> ERROR:x:foo asdf
```
Shouldn't the logging system work the same as Python's logging system?  I'm curious why regular python logging objects are used?  Is there an API to just use regular python logging objects?

**Comment by benleb** [comment]
Sure :) https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html#get-main-log

**Comment by ReneTode** [comment]
> Shouldn't the logging system work the same as Python's logging system?

there are all kind of logginsystems for python.
you can use them by importing them and create your own logsystem.

you are using a program called appdaemon, that is created with python.
in such cases you have to first follow the programs api, which will always override the python api.

logging will have more options in the next version.

**Comment by acockburn** [comment]
As @benleb says, getting the underlying logger object is possible already. And as Rene says, Logging is getting a complete overhaul in version 4.0.
