### ISSUE TITLE
Allow API Calls to dump schedule etc.

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/appdaemon#48]
I know we talked about this a few months ago, but can you move the dump_schedule, dump_callbacks, etc functions into the api and have them return a list or dictionary or something?  It would be useful from a debugging perspective to be able to monitor the schedule and callbacks as well as others and have the choice of outputting the results to the log or to the command line.  Outputting the results of the killall 10 command just push everything I am looking for up in the log so that it's hard to compare the output I put in the log against the output of the debug statement, or alternatively, make the dups accessible from the appdaemon command line so that we could just type in appdaemon --dump=schedule or --dump=callbacks, etc

**Comment by acockburn** [comment]
Yep, I sure will when I am done with HADashboard beta.

**Comment by acockburn** [comment]
Added in 2.0.4
