### ISSUE TITLE
Invalid default conf due to 'log' entry

### ISSUE THREAD

**Issue by danieldotnl** [home-assistant/appdaemon#485]
When following the docker guide (https://appdaemon.readthedocs.io/en/latest/DOCKER_TUTORIAL.html) and start the container according to the 'Testing your system' section, the container does not start and give the error: 'log' directive deprecated, please convert to new 'logs' syntax

After that I mounted a volume for the conf folder, which was then filled with a default configuration. This configuration is apparently invalid as it contains a 'log' entry. Removing the log entry fixed the issue and I could start the container.

**Comment by acockburn** [comment]
Yes, the DEV image needs to be updated to use the latest log format - thanks for the reminder.

**Comment by danieldotnl** [comment]
Clear, but I didn't choose on purpose for the dev image, as I use a raspberry pi and had to build the image myself. Just cloned the repository.

**Comment by Raphael99-99** [comment]
Same problem here. I edited the DockerFile to make it compatible with my rpi 3b+ and the same error happens to me. 
What should i do to update to the latest log format? 
Thanks

**Comment by ReneTode** [comment]
the docs for the logformat for the dev version are here, if thats what you are looking for
https://appdaemon.readthedocs.io/en/dev/CONFIGURE.html
