### ISSUE TITLE
[Help] Calling services with nested data

### ISSUE THREAD

**Issue by viertaxa** [home-assistant/appdaemon#489]
How do you call a service with nested data? For example, iOS push notifications.

      service: notify.ios_<your_device_id_here>
      data:
        title: "Smart Home Alerts"
        message: "Something happened at home!"
        data:
          push:
            badge: 5

**Comment by ReneTode** [comment]
self.call_service("notify/ios_" + "your_device_id_here", title="Smart Home Alerts",message="Something happened at home!",data={"push":{"badge":5}})

**Comment by acockburn** [comment]
I assume Rene answered your question - closing.
