### ISSUE TITLE
when an callback hangs things are not reported right.

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#494]
i got a callback that somehow blocked my thread.
in the errorlog nothing can be found
in the mainlog there is also nothing to be found.
the entry before the problem and after the problem started were:
```
DEV 2019-01-25 13:52:11.982612 AppDaemon       Queue size is 51, suspect thread starvation
DEV 2019-01-25 08:11:34.625674 sensor_donkered donkere dag verlichting aan
```
admin showed 1 thread busy all the time
and in the threads section this could be found
```
thread-32    0    idle    never    true    ["test2hasses"]
thread-33    0    idle    never    true    ["mysensors"]
thread-34    0    idle    never    true    ["handy_group"]
thread-35    0    idle    2019-01-25T08:45:05+01:00    true    ["light_bank_hoek"]
thread-36    0    checknow() in forum_sensors    2019-01-25T09:37:00+01:00    true    ["forum_sensors"]
thread-37    0    idle    2019-01-25T15:02:51+01:00    true    ["checkmountbackup"]
```
that shows that the callback was hanging since 9:37
from 13:52 untill i restarted AD (around 16:45) every 5 mins the qsize went up with 1, and the app runs every 5 mins. so the qsize from the app was definitely going up.
in diag file there were dumps also from 13:52 untill restart.

in terminal there is no way to look back to the moment the problem started, because the thread dumps also did go to the terminal, filling the buffer out.

a part of the normal log
```
DEV 2019-01-25 14:54:49.396233 AppDaemon       Queue size is 63, suspect thread starvation
DEV 2019-01-25 14:53:43.597845 AppDaemon       Queue size is 63, suspect thread starvation
DEV 2019-01-25 14:52:37.969023 AppDaemon       Queue size is 63, suspect thread starvation
DEV 2019-01-25 14:51:32.197585 AppDaemon       Queue size is 62, suspect thread starvation
DEV 2019-01-25 14:50:26.205931 AppDaemon       Queue size is 62, suspect thread starvation
DEV 2019-01-25 14:49:20.062012 AppDaemon       Queue size is 62, suspect thread starvation
DEV 2019-01-25 14:48:14.282986 AppDaemon       Queue size is 62, suspect thread starvation
DEV 2019-01-25 14:47:08.337399 AppDaemon       Queue size is 62, suspect thread starvation
DEV 2019-01-25 14:46:02.521164 AppDaemon       Queue size is 61, suspect thread starvation
DEV 2019-01-25 14:44:56.492792 AppDaemon       Queue size is 61, suspect thread starvation
DEV 2019-01-25 14:43:50.879524 AppDaemon       Queue size is 61, suspect thread starvation
DEV 2019-01-25 14:42:45.246938 AppDaemon       Queue size is 61, suspect thread starvation
DEV 2019-01-25 14:41:39.457066 AppDaemon       Queue size is 60, suspect thread starvation
DEV 2019-01-25 14:40:33.708869 AppDaemon       Queue size is 60, suspect thread starvation
DEV 2019-01-25 14:39:27.051362 AppDaemon       Queue size is 60, suspect thread starvation
DEV 2019-01-25 14:38:21.240830 AppDaemon       Queue size is 60, suspect thread starvation
DEV 2019-01-25 14:37:15.524009 AppDaemon       Queue size is 60, suspect thread starvation
```
--------------------------

helpfull would be if the warning would show
- which thread
- which callback
- the time that the callback was started

terminal should be clean from dumps
qsize should be updated in admin.

you also mentioned that a warning should be in the docs, when a callback takes to much time

we also discussed the option for a callback timeout.

----------------------------------------

i tried to restart the app by changing the py file, but the app and thread kept the same state.
i tried to restart the app, by editing out the yaml (log showed, the app was deleted, but the tread kept running)
then i did restart the app by adding the yaml again, but allthough in the logs the app amount went up with 1, there was no new thread and the app was only in the old thread that was still hanging.

at that point all i could do was restarting AD.

it would be nice if it was possible that at least the restart from the app would cancel the hanging callback.

**Comment by acockburn** [comment]
OK, I fixed the AUI to show the increasing Q size and I added info to the error message:

`2019-09-14 14:58:37.536835 WARNING AppDaemon: Queue size for thread thread-2 is 498, callback is 'run_every_c() in schedule' called at 2019-09-14 14:50:19-04:00 - possible thread starvation`

I don;t think removing the warning fro the log is a good idea, it is likely to be missed but you can tune the frequency of the messages now.

Finally, it isn't going to be possible to kill the thread at app reload without major changes to AD - specifically replacing threads with processes which don't want to do.

This should be a big improvement, so closing.

**Comment by scadaguru** [comment]
It will be nice if can get queue size via this call: get_thread_info()
Thanks
