### ISSUE TITLE
important! all apps for which a priority is set are seen as a group

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#498]
i had a few apps where i have set priority to 1
every time i edit something in 1 of them (and sometimes also when i edit another app) all apps are reloaded.

```
DEV 2019-01-27 22:53:17.855389 AppDaemon       App 'create_input_numbers' changed
DEV 2019-01-27 22:53:17.854430 AppDaemon       App 'create_switches' changed
DEV 2019-01-27 22:53:17.853353 AppDaemon       App 'create_input_booleans_foscam' changed
DEV 2019-01-27 22:53:17.852430 AppDaemon       App 'create_input_booleans_diversen' changed
DEV 2019-01-27 22:53:17.851497 AppDaemon       App 'create_input_booleans_lichtgroepen' changed
DEV 2019-01-27 22:53:17.850570 AppDaemon       App 'create_input_booleans_woonkamer_tv' changed
DEV 2019-01-27 22:53:17.849616 AppDaemon       App 'create_input_booleans_personen' changed
DEV 2019-01-27 22:53:17.848638 AppDaemon       App 'create_internal_sensors' changed
DEV 2019-01-27 22:53:17.847693 AppDaemon       App 'create_new_input_text' changed
DEV 2019-01-27 22:53:17.846730 AppDaemon       App 'create_input_texts' changed
```
to see if i get more info i numbered the priority from 1 to 9.
didnt change anything. still every app with priority is reloaded.

i dont have any dependencies set for the apps
and the docs state that the priority is for loading order only.

https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#app-loading-priority

i hope you can figure that out soon.

extra info:
the apps above are all apps that use 1 module, but have different yaml files.
but the same happens also when there are more then 1 module.

**Comment by acockburn** [comment]
Should be fixed now
