### ISSUE TITLE
Values Not shown if external Access to dashboard

### ISSUE THREAD

**Issue by thundergreen** [home-assistant/appdaemon#50]
If i try to watch from outside my network I don't see the entity values

**Comment by acockburn** [comment]
This has been discussed on the Beta thread - it is a security mechanism in the browser. The workaround is to ensure that you use the same URL in your browser as you use in the Dashboard config file to avoid the conflict.

A more robust solution is to use NGINX to proxy the connection.

**Comment by thundergreen** [comment]
Thanks .Will use nginx

Am 14.03.2017 18:51 schrieb "Andrew Cockburn" <notifications@github.com>:

Closed #50 <https://github.com/home-assistant/appdaemon/issues/50>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/home-assistant/appdaemon/issues/50#event-999528130>,
or mute
the thread
