### ISSUE TITLE
ability to override main_log on an app by app basis

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/appdaemon#501]
Right now we can create new logs in the appdaemon.yaml file.  It would be nice if in the apps.yaml file we could specify a main_log= that overrides the main_log specified in the appdaemon.yaml file.  This way we don't have to change our code to specify which log we want to write to, we just keep doing as normal and change the apps.yaml file.  Makes switching to a different log for debugging purposes easier and quicker.

**Comment by Odianosen25** [comment]
@turboc1208,

I will assume you are using AD 4.0, if that is the case it is possible to specify which log you want to use in the `app.yaml` file using the `log:` directive.

Added to that, it is also possible to use the `self.log(text, log = log)` when writing logs.

Regards

**Comment by turboc1208** [comment]
Not seeing it at the app level in the docs, only at the appdaemon.yaml level.

**Comment by Odianosen25** [comment]
Yes we will work at updating the docs to reflect this.

Regards
