### ISSUE TITLE
Plugin Didn't Process App Restart 

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#502]
I just had an issue where the MQTT plugin had disconnected and reconnected, but the apps didn't process a restart.

I think the reason was after it connected, there was an error in the log as an app tried to access an entity within the namespace and that might have broken its ability for it to process a restart. 

Logs:
[log.log](https://github.com/home-assistant/appdaemon/files/2804131/log.log)

**Comment by acockburn** [comment]
I need a little more info as to what is going on here - which restart are you talking about and what was the error in the app? There are a lot of restarts in the log and I'm not sure what I'm looking for.

**Comment by Odianosen25** [comment]
I meant the plugin restart.

Normally when a plugin restart, it processes restart of the apps. If you notice in the log, there is no indication that the restart was processed, and it will have a message like “processing plugin restart” or something.

If you notice when the plugin said it was connected to the broker at different times, and though it reported the plugin has completed its initialisation and gotten initial state from the namespace, it would normally process app restart which are linked to it using the plugin: directive in the apps config or default if not allocated to None.

Regards
