### ISSUE TITLE
Dialogflow get_apiai_intent() uses wrong key

### ISSUE THREAD

**Issue by dennisschroeder** [home-assistant/appdaemon#511]
In file appapi.py on line 98 the key to get the intent from the request has changed from the dialogflow side. It´s not `result` anymore. They changed it to `queryResult`.

So the code should be:

```
    @staticmethod
    def get_apiai_intent(data):
        if "queryResult" in data and "action" in data["queryResult"]:
            return data["queryResult"]["action"]
        else:
            return None
```

Same with the get_apiai_slot_value() method in line 106

**Comment by acockburn** [comment]
Fixed in dev
