### ISSUE TITLE
home-assistant key should be able to config via enviroment variable or specifiy in separate file

### ISSUE THREAD

**Issue by yuchangyuan** [home-assistant/appdaemon#52]
Currently we can only config home-assistant key with 'ha_key' in appdaemon.cfg. I think it's better to have alternative ways to specify this value, either via environment variable or a separate file, so we can store config file and credential separately.

**Comment by acockburn** [comment]
SOUnds like a good enhancement to me - I will look at adding this when I have finished work on the HADashboard beta.

**Comment by acockburn** [comment]
Will be addressed under issue #67
