### ISSUE TITLE
run_in not correctly validating entity ids

### ISSUE THREAD

**Issue by dmwyatt** [home-assistant/appdaemon#520]
This code:
```python
class SomeApp(hass.Hass):
    def initialize(self):
        self.log(type(self.args['device']))
        self.log(self.args['device'])
        self.run_in(self.turn_off, 1, entity_id=self.args['device'])
```

Results in this error:
```
2019-02-16 18:31:28.549967 INFO percent_time_toggle: <class 'str'>
2019-02-16 18:31:28.551291 INFO percent_time_toggle: switch.sonoff_1970
2019-02-16 18:31:48.002496 WARNING AppDaemon: ------------------------------------------------------------
2019-02-16 18:31:48.002763 WARNING AppDaemon: Unexpected error in worker for App percent_time_toggle:
2019-02-16 18:31:48.003003 WARNING AppDaemon: Worker Ags: {'name': 'percent_time_toggle', 'id': UUID('91da3dc9-e619-4c70-9bf8-368bcd63986a'), 'type': 'timer', 'function': <bound method hass_check.<locals>.func_wrapper of <percent_time_toggle.PercentScheduler object at 0x7f69dc0d5710>>, 'kwargs': {'entity_id': 'switch.sonoff_1970'}}
2019-02-16 18:31:48.003166 WARNING AppDaemon: ------------------------------------------------------------
2019-02-16 18:31:48.003646 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 586, in worker
    funcref(self.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/usr/local/lib/python3.6/site-packages/appdaemon/plugins/hass/hassapi.py", line 22, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/plugins/hass/hassapi.py", line 349, in turn_off
    self._check_entity(namespace, entity_id)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appapi.py", line 79, in _check_entity
    "{}: Invalid entity ID: {}".format(self.name, entity))
ValueError: percent_time_toggle: Invalid entity ID: {'entity_id': 'switch.sonoff_1970'}

2019-02-16 18:31:48.003836 WARNING AppDaemon: ------------------------------------------------------------
```

At some point the `entity_id` named argument is getting passed to the `_check_entity` method as a dict instead of the value.

If I just call `self.turn_off(entity_id=self.args['device'])` instead of using `run_in`, it works correctly.

**Comment by ReneTode** [comment]
you cant use a function as callback.
your code should be:
```
class SomeApp(hass.Hass):
    def initialize(self):
        self.log(type(self.args['device']))
        self.log(self.args['device'])
        self.run_in(self.cb, 1, entity_id=self.args['device'])

    def cb(self,kwargs):
        self.turn_off(self.args['device'])
```

**Comment by dmwyatt** [comment]
What do you mean I can't use a function as a callback?

What is the difference between `self.turn_off` and `self.cb`?  AFAICT, they're both just methods on the class.

**Comment by ReneTode** [comment]
self.turn_on is a predefined function from dashboard
a callback ALWAYS need a specific way its build.

every timer callback expects the def to look like:
```
def callback(self,kwargs)
```
self.turn_on doesnt look like that.

every listen_state callback needs to look like:
```
def callback(self, entity, attribute, old, new, kwargs):   
```
thats the way AD is designed and how its in the docs.

so the difference between self.turn_off and self.cb is that 1 is defined as callback and the other isnt.

**Comment by dmwyatt** [comment]
Oh, ok.  So it's *not* this:

> you cant use a function as callback.

It's the function signature that is the issue.

**Comment by ReneTode** [comment]
if you want to call it that way. ;)
my learning from python was about the same as learning from AD.

in my eyes there is a clear difference between a callback and a function.
for me a callback isnt some function with a specific signature, but another ballpark.

but at least you know now why you got errors. it could be helpfull to read the docs to find out whats different between appdaemon and python, and whats the appdaemonic way to write apps ;)

**Comment by dmwyatt** [comment]
The following is just presented in a good-natured effort to elucidate.  Don't take it in any sort of negative way!

> if you want to call it that way. ;)

Yes, that is what those words mean.  🤣 

> in my eyes there is a clear difference between a callback and a function.

Every function can be a callback, and every callback is a function.

The word callback is a shorter way of saying "a function that is passed to another function for later execution".  In fact, `func` is often the name given to the argument that is expecting the callback.

Python makes this easier than some other languages because everything is an object, including functions.

The [wikpedia](https://en.wikipedia.org/wiki/Callback_(computer_programming)) article is pretty decent on the subject.

> but at least you know now why you got errors. it could be helpfull to read the docs

Yes, thank you for your help. I found the section in the docs where it talks about the expected signature.

> whats different between appdaemon and python, and whats the appdaemonic way to write apps ;)

There's really nothing appdaemon is doing here that is different from python.  It's just standard programming.  Developers write code that expects callbacks with certain signatures all of the time. The only reason I was confused was that appdaemon doesn't raise a useful exception in this case.  I will open a PR to fix that.

When code expects to call a function with a specific signature and you don't give it a function with that signature, there will be problems.  

This is one of the downsides of using a non-statically-typed language.  If, for example, this project was written with support for python/mypy, this error would have been immediately flagged with a more useful error message because the type checker would see I was passing a function with a different signature.

**Comment by ReneTode** [comment]
> There's really nothing appdaemon is doing here that is different from python.
still there are a lot of people complaining that its not the pythonic way.
and my response to that is: thats true its the appdaemonic way.

in appdaemon there is a clear difference between a function and a callback.

thats why i say if you would call it that way.
you talk python, i talk appdaemon.

**Comment by dmwyatt** [comment]
> in appdaemon there is a clear difference between a function and a callback

In what way?

**Comment by ReneTode** [comment]
a function can have every kind of signature you like and can return a value and cant be constraint(in yaml or in the script)

a callback needs the set signature, will always return a handle, and can be constraint (with cancel_timer)

you said:

> Every function can be a callback, and every callback is a function.
> 
> The word callback is a shorter way of saying "a function that is passed to another function for later execution".

but thats not true in appdaemon.
not every function can be a callback, because a callback needs a specific setup

in appdaemon it would be "a callback is a function that is setup in the defined way, it will be excuted based on state, schedule or event, and can be constraint"

like i said its a matter of how you look at things.
you look at whats the same, i look at the differences.
you see an apple and say its just a fruit (which is absolutely correct)
i see an apple and say its an apple
not every fruit(function) can be an apple(callback)
(at least not in AD)
