### ISSUE TITLE
Widget_type: Navigate not returning as expected

### ISSUE THREAD

**Issue by DaBIGOne** [home-assistant/appdaemon#521]
# Problem/Motivation

I try to navigate to a 2nd dash with a separate skin and then return after an amount of time, for test purposes I've set 3 seconds for now.

in may main dashboard Home.dosh I added: 
verlichting:
    widget_type: navigate
    title2: Verlichting
    dashboard: Verlichting
    skin: Verlichting
    args:
        timeout: 3
        return: Home
        skin: Home

## Expected behavior

I expected to go to verlichting.dash with skin Verliching and after 3 seconds to return to Home.dash with Home skin

## Actual behavior

It returned to Home.dash but with Verlichting skin.

## Steps to reproduce

see above

## Proposed changes

I see it takes the arguments into the adressline when navigating to the other dash.
/Verlichting?timeout=3&return=Home&skin=Home&skin=Verlichting
after 3 seconds it returned to:
/Home?skin=Verlichting

somehow the &skin=Home got lost.

When I do not add the skin argument (/Verlichting?timeout=3&return=Home&skin=Verlichting) it still comes back with the verlichting skin to home: /Home?skin=Verlichting

I think this is behaviour is good for keeping the selected skin, but for me every dash needs his own skin.

Maybe it's possible to add a skin variable in the .dash file so it loads with the assigned skin and not with the skin passed in the address bar?

Thanks,

Dennis

**Comment by ReneTode** [comment]
> Maybe it's possible to add a skin variable in the .dash file so it loads with the assigned skin and not with the skin passed in the address bar?

that would lose the flexibility to use any dashboard with any skin at any time.
the temp files for every dashboard with every skin are build on different places. so it wouldnt be possible to give the skin in the url anymore.

but i think the navigate should return to the old skin as default with the option to change to the new skin.

skins are not designed to use with a single dashboard. in a skin you set general options for your dashboards.
i dont know why you need a seperate skin for each dashboard, but we should think of a way to take away that need.

**Comment by DaBIGOne** [comment]
Well, the main reason why I want a separate skin for each dashboard is the background image.
Maybe if it would be possible to assign the background image in the .dash file it would be workable for me too.

I make small changes for every skin, but I can work around that I think. Like a big clock on the main screen, but smaller clocks on the other pages, maybe I can assign CSS to the name in stead of class.

**Comment by ReneTode** [comment]
clock can be completely changed in the dashboard.
so no need to do that in skin.
for the background from each dashboard there is a script solution.

place this in the headscript from your skin, and you can give each dashboard a background with the same name as the dashboard.
```
head_includes:
  - <! head tags go here ->
###############################################################################
# function to load background based on dash name
###############################################################################
#  - "<script type='text/javascript'>"
#  - "function changeImg()   {"
#  - "var htmlurl = window.location.pathname;"
#  - "htmlparts = htmlurl.split('/');"
#  - "var filename = htmlparts[htmlparts.length - 1];"
#  - "var vars = {};"
#  - "var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) { vars[key] = value; });"
#  - "var skin = vars['skin']"
#  - "var Image = '/custom_css/' + skin + '/img/' + filename + '.jpg'"
#  - "document.body.style.backgroundImage = 'url(' + Image + ')';"
#  - "}"
#  - "window.onload=changeImg;"
#  - "</script>"
###############################################################################
```
place the background images in /custom_css/skin_name/img

**Comment by DaBIGOne** [comment]
That is awesome, that would solve my issue. I'll try it when I get home from work.
Thanks.

**Comment by DaBIGOne** [comment]
Yes, added it to my variables.yaml and it worked like a charm :)
Thanks, this is a much better solution than having an CSS for every file :)

**Comment by ReneTode** [comment]
i am glad it helped you.
if you are satisfied then please close the issue.
