### ISSUE TITLE
terminate() is not running

### ISSUE THREAD

**Issue by SupahNoob** [home-assistant/appdaemon#53]
I'm on AppDaemon 1.5.2 ... I'm unsure of how to help debugging this one.

```python3
class Camera(appapi.AppDaemon):

    def initialize(self):
        #self.utils = self.get_app('utils')

        if self.args['node'] == 'server':
            self.log('Starting server...')
            self.start_server()

        self.log('Initializing app...')

    def terminate(self):
        self.log('Terminating..')
        self.stop_server()

    def start_server(self):
        """
        For the life of this app turn our cfg content above into a file, for 
        purposes of standing up `ffserver` 

        Less scattered files == More user-control
        """
        self.config = NamedTemporaryFile()
        #_config_path = config.name
        self.config.write(SERVER_CONFIG.encode())
        self.config.flush()

        self.server = subprocess.Popen(
                [ # popen args!
                    'ffserver',
                    '-hide_banner',
                    '-f', self.config.name
                ], stderr=subprocess.PIPE
            )

    def stop_server(self):
        self.log('Error: {}'.format(self.server.stderr.read()))
        self.server.kill()
        self.config.close()
        self.log('Killed..')
```

Nothing serious going on in the app thus far ... terminate() just never gets called. My log files don't show teardown of **any** app, now that I'm looking through it.

I uninstalled/installed the AppDaemon package and it didn't change a thing -- not that it should have, but I thought I might had changed the program a bit~
- SN

**Comment by acockburn** [comment]
I was unable to reproduce - if you have a simple example I'll take another look - works fine in my apps. i think in your case it might be that creating a new process is gumming things up - have you tried using a thread instead?

**Comment by SupahNoob** [comment]
If I remember correctly, I was creating the app itself in a new process, which makes sense now why it wouldn't work. D'oh! Thanks.
