### ISSUE TITLE
listen_state fires every second  while state is unchanged

### ISSUE THREAD

**Issue by martinwk** [home-assistant/appdaemon#539]
Hi there, 
great software you have created. 

I was running into an issue where the listen_state fires every second while the state stays the same. In particular this line of code:
```
        self.listen_state(self.switch_on, entity="media_player.geluidstromer", new='playing')
```
which listen to the chromecast audio state. 
when printing the args it says:
```
('media_player.geluidstromer', 'state', 'playing', 'playing', {'handle': UUID('f...')
```
showing the state is indeed not changed.

adding the old states to the listen_state def does not trigger the callback every second:

```
        self.listen_state(self.switch_on, entity="media_player.geluidstromer", new='playing', old='idle')
```

**Comment by martinwk** [comment]
Oh I see, did not find it when I was looking for a fix. Good to hear a fix is in the next update!

**Comment by Odianosen25** [comment]
This has been fixed in latest dev, so closing this issue @martinwk

**Comment by martinwk** [comment]
Great I will check it out!
