### ISSUE TITLE
"state_text_style" does not work

### ISSUE THREAD

**Issue by wangjiwang** [home-assistant/appdaemon#541]
"If it is showing text it will use the text style, which among other things makes the text size smaller."
Hi, How to solve this problem? the  text size is too small and the  state_text_style: "font-size: 80%; color: red" doesn't work.

**Comment by acockburn** [comment]
The default for state_text_style is "color: $white; font-size: 100%" so you are actually making it smaller. Try something like "font-size: 200%; color: red"

**Comment by acockburn** [comment]
Assuming resolved since there was no reply.
