### ISSUE TITLE
can't install python-Levenshtein

### ISSUE THREAD

**Issue by sensei73** [home-assistant/appdaemon#557]
Hello when I tried to install python-Levenshtein, I have this error:

error: command 'gcc' failed with exit status 1

Thanks in advance.

**Comment by ReneTode** [comment]
if you try this on hassio, you need to include the needed stuff into requirements.txt
i advice to look at the forum for more info, because there are several simular topics.
you could also lookup the documentation about the hassio addon, because this belongs there.

this is not an appdaemon issue.

**Comment by sensei73** [comment]
Thanks for showing me the right direction. Solved, by adding "g++" in "system_packages", I didn't see this section... (even if this was right in front of me)! Thanks
