### ISSUE TITLE
AppDaemon hangs when calling service from a coroutine

### ISSUE THREAD

**Issue by foxy82** [home-assistant/appdaemon#570]
I have an app that runs a coroutine to check evdev for inputs. On receiving an input it should publish to MQTT using the mqtt plugin. When it runs the mqtt_publish hangs and never returns here are some code snippets:

`
class EvdevToMqtt(mqtt.Mqtt):
    def initialize(self):
        self.topic = self.args["topic"]
        for device_name in self.args['devices']:
            device = evdev.InputDevice(device_name)
            device.grab()
            task = self.AD.loop.create_task(self.handle_evdev_events(device))

    async def handle_evdev_events(self, device):
        self.log("Listening for events on {}".format(device))
        async for event in device.async_read_loop():
             self.log("Publishing")
             # Hangs here
             self.publish_mqtt(self.topic, "ON")
             self.log("Published")
`

The log never gets to the published and no further key presses are detected

`2019-05-23 07:12:33.710661 INFO evdev_to_mqtt: Listening for events on device /dev/input/by-id/usb-ZY.Ltd_ZY_Control_Mic-if02-event-kbd, name "ZY.Ltd ZY Control Mic", phys "usb-20980000.usb-1/input2"
2019-05-23 07:12:33.733706 INFO evdev_to_mqtt: Listening for events on device /dev/input/by-id/usb-ZY.Ltd_ZY_Control_Mic-if03-event-mouse, name "ZY.Ltd ZY Control Mic", phys "usb-20980000.usb-1/input3"
2019-05-23 07:12:37.289883 INFO evdev_to_mqtt: Publishing`

If I remove the publish it will log published and further key presses work as expected. 

Any ideas?

**Comment by acockburn** [comment]
I believe you are running into a locking issue when trying to mix threaded and async code

Your code is running in a separate thread from ADs code, but you are trying to use ADs loop. I have experimented in this area and run into quite a few locking problems, as under the covers your call to the plugin has its own locking in the call from the tread into ADs async core.

I am working on async apps for a future release, but I suggest that until then you avoid it in apps. Another possibility might be to create and use your own loop.

**Comment by foxy82** [comment]
Thanks - I'm running on a pi zero so I only have one core. Creating my own loop also didn't seem to work very well. 

I could achieve this using a standard python script so I might have to go that way but I like the way AD will reload things for me and keep it neat. Is there anyway to see the async work in progress or anyway you can see to change my app to use the threaded model? 

I considered writing an evdev plugin but then that gets complicated as that will only work on linux and not windows so might not be a good fit for AD.

**Comment by Odianosen25** [comment]
Hello @foxy82,

I am of the view developing a plugin is your best option, as doing it within an app, will complicate things as stated by Andrew. Besides most of the API are not async friendly, so even if you get the data, wouldn't you want to pass the data to AD? 

If you still insist on doing it this way, it might be still possible but it will mean using AD in such a way it wasn't exactly intended to be used. So please just develop a plugin as you alluded to. You can use this one I did as start [here](https://github.com/Odianosen25/Custom-AppDaemon-Plugins/blob/master/hwstats/hwstatsplugin.py), as its also reading system hardware stats (though I use an app for that now), but its a good step to what you want.

regards

**Comment by acockburn** [comment]
I agree with @Odianosen25 - today your best bet is a plugin for this - there you will have full access to the main loop without hitting the locking issue. You can always revisit when we figure out async apps.
