### ISSUE TITLE
Can't call HASS functions from MQTT plugin?

### ISSUE THREAD

**Issue by foxy82** [home-assistant/appdaemon#575]
I have an MQTT plugin that when it receives a certain message it will call a service in HASS. HASS is the default plugin and mqtt namespace is "mqtt" 

When I call this code:

`          self.call_service('remote/send_command',
               entity_id=self.harmony_hub,
               device=device_id,
               command=keycode,
               namespace='default')`

Gives this error:
`2019-06-02 16:31:10.546141 WARNING AppDaemon: ------------------------------------------------------------
2019-06-02 16:31:10.546939 WARNING AppDaemon: Traceback (most recent call last):
  File "/srv/appdaemon/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 600, in worker
    funcref(args["event"], data, args["kwargs"])
  File "/home/appdaemon/.appdaemon/apps/mqtt-remote-appdaemom/mqtt_remote.py", line 29, in mqtt_message
    self.send_command(device_id, key_code, key_state)
  File "/home/appdaemon/.appdaemon/apps/mqtt-remote-appdaemom/mqtt_remote.py", line 67, in send_command
    namespace='default')
  File "/srv/appdaemon/lib/python3.6/site-packages/appdaemon/plugins/mqtt/mqttapi.py", line 190, in call_service
    raise ValueError("Topic not provided, please provide Topic for Service Call")
ValueError: Topic not provided, please provide Topic for Service Call`

I tried to fudge it and add Topic but that didn't work.

**Comment by Odianosen25** [comment]
Hello @foxy82,

First what version of AD are you using?

Also can you confirm that `default` is the namespace for the HASS plugin?

Lastly if all you want to do is to listen to MQTT, then carry out a HASS service call. Might be better to do that in a HASS app, but depends on what version of AD u running.

Regards

**Comment by foxy82** [comment]
I was on 3.0.2 and then updated to 3.0.5 same issue on both.

In a HASS app can I do an mqtt subscribe?

**Comment by Odianosen25** [comment]
No you cannot use MQTT subscribe in the HASS app, but you can listen to MQTT events, then carry out a HASS service.

Apologies missed the fact u already stated the HASS was default.

Regards

**Comment by ReneTode** [comment]
the best way to listen to mqtt events is not to subscribe in the app but configure the plugin correctly(in appdaemon.yaml)
after that you can use listen_event in the app with the namespace you gave the plugin.

**Comment by Odianosen25** [comment]
@foxy82,

I believe your issue has been fixed, closing this issue and please reopen if not satisfied.

Regards
