### ISSUE TITLE
logging on the wrong places.

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#576]
over time i noticed quite some things that get logged on the wrong places since i moved to dev.
mostly i ignored it but i think its important enough for an issue.

i will use this issue to add things that go to the wrong place.
ill update the list that i make here when i find something new (or someone else reports something) or when an update has been made to repair the "bug"

1) in dev: in terminal i get a list from all dashboards when i try to load an unexisting dashboard, or use .dash in the dashboard name.
2) in AD 3: an AD instance dedicated to dashboard reports state update errors in main log.
3) in dev: "Unexpected error in namespace setup" goes to main log
4) in dev: thing like Loading custom widget 'baseAdminLog' end up in main log instead of in access log
5) in dev: "Unexpected error during DASH creation" ends up in main log

**Comment by acockburn** [comment]
Per our dicsussions - closing this. Some fixed, some are a work in progrerss
