### ISSUE TITLE
Suggestion: more pythonic/object-oriented high-level API

### ISSUE THREAD

**Issue by rytilahti** [home-assistant/appdaemon#58]
Hi, I have been doing some preliminary testing to get a feel how to work with appdaemon, and got curious whether it would be ok to provide a nicer API for common component types?

So instead of having this:
```
for light in self.get_entity("group.ceiling_lights")["attributes"]["entity_id"]:
    self.toggle(light)
```

one could write:
```
for light in self.get_group("ceiling_lights"):
    light.toggle()
```

It'd also be nice to access the common properties directly, for example in case of lights of all what Light class of homeassistant provides. I haven't yet dug into what kind of data homeassistant gives out through the API, e.g. do we get enumeration of supported operations & properties, which would make pulling this off even simpler, but assuming this sort of development would be accepted I might spend some time on it to make it happen. Any thoughts?

**Comment by acockburn** [comment]
I am all for adding additional helper functions that make simple tasks like this easier and more intuitive - I've added a few but there is a lot more that can be done :)

So I will accept suggestions, but would prefer PRs if you are willing to help.

**Comment by rytilahti** [comment]
Ok, I'll test it out when I find some time to work on it and report back how it goes :-)

On a related note, I found out that /api/bootstrap/ will return all information one wants (incl. the available methods), although it may be a bit overkill to introspect instead of just writing small wrappers for wanted functionality, but worth of thought anyway.
