### ISSUE TITLE
KeyError: '[appName]'

### ISSUE THREAD

**Issue by dlashua** [home-assistant/appdaemon#584]
AppDaemon version: 3.0.5
Installed via Docker

Occasionally, I'll get an error like the following:
````
2019-06-25 12:42:19.260713 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 595, in worker
    self.sanitize_state_kwargs(app, args["kwargs"]))
  File "/conf/apps/yamllogic/yl_state_value.py", line 167, in state_callback
    **kwargs)
  File "/conf/apps/vacuum_handler_2.py", line 227, in trigger_state_change
    self.run_in(self.clean_next_room_c,5)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appapi.py", line 338, in run_in
    name, exec_time, callback, False, None, **kwargs
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1004, in insert_schedule
    "id": self.objects[name]["id"],
KeyError: 'sofie'
````

It happens in more than just this app, this is just the most recent example I have. Restarting the App (by editing the YAML and saving the file) fixes it every time. It's like AppDaemon isn't aware of the app at the time the callback is called, even though I've not made any recent modifications to the YAML that might cause the app to be reloading or something like that.

For completeness sake (though, again, this happens in many apps), here are the functions referenced in the WARNING:

````
    def clean_next_room_c(self, kwargs):
        self.clean_next_room()
````

You can see that nothing is referencing "sofie" (the name of the app) in any way, and if it was happening in the method being called there (self.clean_next_room()) then I would see that in the traceback.

self.objects["sofie"] presumably doesn't exist when... 
````
/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1004, in insert_schedule
````
...is doing its work.

**Comment by ReneTode** [comment]
it seems like you are initialising a schedule at the moment from the error.
to see what really is going on i need to see a complete app (py module and yaml that belongs to it)

and the complete error (including the lines before and after) like:
```
2019-03-03 14:56:14.062686 WARNING AppDaemon: ------------------------------------------------------------
2019-03-03 14:56:14.063691 WARNING AppDaemon: Unexpected error in worker for App foscammartemp:
2019-03-03 14:56:14.064370 WARNING AppDaemon: Worker Ags: {'name': 'foscammartemp', 'id': UUID('b744dc99-87e6-4dcd-afc1-5e0ac4cea029'), 'type': 'timer', 'function': <bound method foscam.set_temp_sensor of <foscamtemp.foscam object at 0x7f7bb805cac8>>, 'kwargs': {'interval': 60}}
2019-03-03 14:56:14.064657 WARNING AppDaemon: ------------------------------------------------------------
2019-03-03 14:56:14.065079 WARNING AppDaemon: Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenv/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 586, in worker
    funcref(self.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/mnt/usbdrive/pi/appdaemon/ADnormal/apps/foscam/foscamtemp.py", line 43, in set_temp_sensor
    temp = data.find("degree").text
AttributeError: 'int' object has no attribute 'text'

2019-03-03 14:56:14.065290 WARNING AppDaemon: ------------------------------------------------------------
```
because the lines before often tell a lot.

**Comment by dlashua** [comment]
It's difficult to show you all of the python module, because it's over multiple files and is a substantial amount of code.

However, I'll try to show you the bits that seem relevant and let me know if you need more.

Here are the full log lines before and after the warning (from a different app with the same issue, because it happened most recently):
````
2019-06-27 08:13:20.890549 INFO AppDaemon: Terminating nook_occupied
2019-06-27 08:13:20.890679 INFO AppDaemon: Calling terminate() for nook_occupied
2019-06-27 08:13:21.168990 INFO AppDaemon: Terminating bath_occupied
2019-06-27 08:13:21.169840 INFO AppDaemon: Calling terminate() for bath_occupied
2019-06-27 08:13:21.504517 WARNING AppDaemon: ------------------------------------------------------------
2019-06-27 08:13:21.505455 WARNING AppDaemon: Unexpected error in worker for App nook_occupied:
2019-06-27 08:13:21.506035 WARNING AppDaemon: Worker Ags: {'name': 'nook_occupied', 'id': UUID('d1f93f40-cfc7-42b8-a086-5306558bfacd'), 'type': 'timer', 'function': <bound method Motion.make_ready of <motion.Motion object at 0x7f395f32ac88>>, 'kwargs': {}}
2019-06-27 08:13:21.506666 WARNING AppDaemon: ------------------------------------------------------------
2019-06-27 08:13:21.532682 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 586, in worker
    funcref(self.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/conf/apps/motion.py", line 120, in make_ready
    yamllogic.Event(self,self._trigger_events,self.trigger_event_callback)
  File "/conf/apps/yamllogic/yl_event.py", line 16, in __init__
    self.listen()
  File "/conf/apps/yamllogic/yl_event.py", line 33, in listen
    self._app.listen_event(self.event_callback, event = event, **event_data)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/plugins/hass/hassapi.py", line 192, in listen_event
    return super(Hass, self).listen_event(namespace, cb, event, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appapi.py", line 240, in listen_event
    return self.AD.add_event_callback(_name, namespace, cb, event, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 771, in add_event_callback
    "id": self.objects[_name]["id"],
KeyError: 'nook_occupied'
````

You can see it's in a timer loop calling the "make_ready" method.

make_ready() is the last thing called by initialize() and I do it this way because it can take some time (seconds) and want initialize to complete ASAP so it doesn't bog down the main executer loop.

make_ready() looks like this:
````
    def make_ready(self, kwarg = {}):
        if self._condition_states != None:
            tmp = yamllogic.StateValue(self,self._condition_states,self.state_callback,{"status_type":"condition"})
            self._condition = tmp.get_state() 

        if self._arming_states != None:
            tmp = yamllogic.StateValue(self,self._arming_states,self.state_callback,{"status_type":"armed"})
            self._armed = tmp.get_state()

        if self._trigger_states != None:
            tmp = yamllogic.StateValue(self,self._trigger_states,self.state_callback,{"status_type":"triggered"})
            self._triggered = tmp.get_state()

        if self._trigger_events != None:
            yamllogic.Event(self,self._trigger_events,self.trigger_event_callback)

        if self._trigger_state_events != None:
            yamllogic.StateEvent(self,self._trigger_state_events,self.trigger_state_event_callback)

        if self._hold_states != None:
            tmp = yamllogic.StateValue(self,self._hold_states,self.state_callback,{"status_type":"held"})
            self._held = tmp.get_state()

        if self._on_action != None:
            self._on_action_obj = yamllogic.Action(self,self._on_action)
        else:
            self._on_action_obj = False

        if self._off_action != None:
            self._off_action_obj = yamllogic.Action(self,self._off_action)
        else:
            self._off_action_obj = False

        # Sanity Check
        if not self._trigger_states and not self._trigger_events and not self._trigger_state_events:
            self.log('No Triggers. Nothing to do.',level = "WARNING")

        self.get_existing_state()
        self.set_new_state()

        ## Add Service Handlers
        # On
        self.listen_event(self.set_active, event = 'call_service', **{
                "domain": "switch",
                "service": "turn_on",
                "service_data": {
                    "entity_id": self.get_entity_id(),
                }
            })

        # Off
        self.listen_event(self.set_inactive, event = 'call_service', **{
                "domain": "switch",
                "service": "turn_off",
                "service_data": {
                    "entity_id": self.get_entity_id(),
                }
            })

        # Set
        self.listen_event(self.set_settings, event = 'admotion.set', **{
                "entity_id": self.get_entity_id(),
            })

        # READY
        self.log("{} ready.".format(self.name), level = "DEBUG")
        self._ready = True

        # Start it Up!
        self.update_state()
````

**Comment by dlashua** [comment]
Oh... and the YAML for nook_occupied is this:
````
nook_occupied:
  module: motion
  class: Motion
  friendly_name: Nook Occupied
  device_class: occupancy
  condition:
    - binary_sensor.home: "on"
  trigger:
    - binary_sensor.nook_motion_xiaomi: "on"
  trigger_events:
    - xiaomi_aqara.motion:
        entity_id: binary_sensor.nook_motion_xiaomi  
  trigger_state_events:
    - entity_id: light.nook_overhead
      to: "on"
      from: "off"
  off_delay:
    minutes: 10
````

**Comment by ReneTode** [comment]
at least it makes more sence now that you show more from the log.

```
2019-06-27 08:13:20.890549 INFO AppDaemon: Terminating nook_occupied
2019-06-27 08:13:20.890679 INFO AppDaemon: Calling terminate() for nook_occupied
```
this tells that the app is terminated. so obviously it isnt there anymore.
normally an app is only terminated when you change something in the module or yaml.

so the question is why the app is terminated at all.

i asked about the code, because a "normal" app is a seperate class inside a module, configured in the yaml.
a class should normally not be in several modules (files), it can however call other functions outside the class (preferably with get_app())

from this callback i can see where it goes wrong but not why.
i need to see the start from the class and the initialise to say more.

i think i see something that can interfere with AD though. if i am correct you use some other way then self.args to get to yaml. and yaml is a core part from AD.

**Comment by dlashua** [comment]
I believe I've fixed this as well. Time will tell. To answer your questions...

The app was terminated because I changed the PY file that defines it.

And yes, this app is "normal" in that it has a class defined in a module configured in YAML, as is expected. It's less normal because the module "imports" several other modules containing reusable pieces (defined as "global_dependencies").

There were two things that changed to "fix" this (it's been less than 12 hours since it's been fixed, so, it'll take some more time to know if it's really fixed.)

I think part of the issue is that I'm modifying YAML and PY files over a SMB/Samba connection. When I change a file, AppDaemon seems to see it changed twice in a row. Perhaps Samba changes the modified date on the file twice, or perhaps my code editor (VSCode) is saving the file twice. So while AppDaemon is starting the app, it often gets terminated again and started again. Compounded with the other issues (below) I think perhaps it added to the problem.

Another part of the issue (that is now fixed) is that my server had a hard drive failure and the only disk I had laying around was a very slow HDD. Incredibly slow. So a lot of the things that generally happen quickly were taking much much longer, and AppDaemon, when not in production mode (which mine is not) is quite disk heavy with all of the file time checks. Last night I replaced the drive with an SSD and it's MUCH faster now.

Another thing I changed yesterday was the way I was dealing with global_dependencies. AppDaemon requires me to list the global_dependencies in the YAML. This is a bit annoying since, in the case of any PY file, the global_dependencies don't change when the YAML changes, they potentially change when the PY file changes. This app has 6 global dependencies and I have about 12 apps (and many more on the way) using the same module and class. Including the global_dependencies in the YAML is tedious since it's the exact same data for every app. So I wrote a method to alter self.args["global_dependencies"] so the Class could register dependencies on it's own. What I didn't realize is that when AppDaemon sees a YAML change, it loads ALL of the YAML files again and compares the data to what it previously saw. Since the data on disk didn't contain the global_depdendencies but the config stored in memory did, AppDaemon saw this as a need to restart the App and so it would restart EVERYTHING (that I had altered self.args["global_dependencies"] for in code... which is everything for me). Restarting so many apps at once may have also led to this issue (tying up the executor even longer and coupled with my very slow HDD).  I rewrote this to not alter self.args["global_dependencies"] so, now, only the apps that actually need to be restarted are restarted.

These two things, together, seem to have fixed my issues. Again, I'm not sure if there is still an issue, but, because my disks are faster and I'm reloading fewer apps on a change the issue seems to be no longer present for me.

If you're curious, here's how I handled global_dependencies.

At the top of the PY file for every global dependency, I add this code:
````
import modulemanager
modulemanager.starting(__name__)
````

Whenever a PY file imports a global_dependency, it also includes this code:
````
modulemanager.register(dependency,self.name)
````

Then, modulemanager.py does the work (I haven't quite cleaned up the code, yet, so it's a bit messy):
````
import appdaemon.plugins.hass.hassapi as hass

deps = {}
main_app = None

def register(dep, app):
    if app not in deps:
        deps[app] = set()

    if dep in deps[app]:
        return

    deps[app].add(dep)

    if main_app == None:
#        raise Exception('No main_app for register')
        return

    main_app.log(f"App {app} depends on {dep}")

def renew(app):
    if main_app == None:
#        raise Exception('No main_app for renew')
        return

    if app in deps:
        del deps[app]
        main_app.log(f"Renewed deps for {app}")

def starting(dep):
    if main_app == None:
#        raise Exception('No main_app for starting')
        return

    main_app.log(f"Module {dep} Starting")

    termed = []
    for app in deps:
        if dep in deps[app]:
            main_app.log(f"Terminating App {app}")
            main_app.AD.term_object(app)
            termed.append(app)

    for app in termed:
        del deps[app]
        main_app.log(f"Starting App {app}")
        main_app.AD.init_object(app)

def test_log():
    main_app.log('MAIN APP WORKING')

class ModuleHandler(hass.Hass):

    def initialize(self):
        global main_app
        global deps
        main_app = self
        self.log('Watching Modules')
        test_log()

        if "restart" in self.config:
            deps = dict(self.config["restart"])
            del self.config["restart"]

    def terminate(self):
        global deps
        self.config["restart"] = dict(deps)
````

As you can see, modulemanager includes an AppDaemon App as well just to save it's own state in the event that that file gets altered.

It's not perfect, since it requires boilerplate code in every app and module that uses it, but it saves quite a bit of "noise" in my YAML files. Hopefully, AppDaemon 4 will include a feature like this (done in the core, of course) to make this easier.

**Comment by ReneTode** [comment]
the only reason why global dependencies are in yaml is to make sure that when you change something to the yaml or the code from a global file, that the apps depending on it are also restarted.

i dont really use it at all.
i got 1 app that contains my global yaml settings (it has only an init that does nothing)
i can call my global settings with self.app_config["settings"]["whatever"]
global functions are also in apps and i call them with
fnc = get_app("global_fnc_something")
fnc.some_function()

in theory i would let all my apps depend on them, and then all apps would restart when i change settings or functions.
but i find it more pratical to leave the depencies alone. if needed i restart AD.

to make sure that all settings and global functions are available when an app starts, i set priority for the global functions and settings to 1.

i understand what you are doing, but you are actually messing with the base structure from AD.
which can give you unexpected results ;)

but im glad you worked it out.
please close the issue if you are satisfied, and next time please ask questions on our discord server, it makes it easier to communicate (here i read at most once a day, on discord i am available several times during the day)

greetz

rene
