### ISSUE TITLE
Get entity id from friendly_name

### ISSUE THREAD

**Issue by simonvanderveldt** [home-assistant/appdaemon#586]
Would it be possible to add a method to get the entity id using `friendly_name`?
This is the opposite of the `self.friendly_name(<entity_id>)` method.

**Comment by acockburn** [comment]
You can write one yourself very easily by getting the whole state then looping through it. One issue is that there is no unique mapping of a friendly name to an entity as the same friendly name can be given to multiple entities.

**Comment by ReneTode** [comment]
and if you want to use that function a lot then create an app like:
```
class functions(..):
  def init(..):
    return
  def get_entity_id(self, friendlyname):
    states = self.get_state()
    for entity in states:
      if entity["friendly_name"] == friendlyname:
        return entity
```
initialise the app in yaml and then in the app call it with:
```
fnc = self.get_app("the_name_you_gave_the_app")
entityID = fnc.get_entity_id(friendly_name)
```

and in your

**Comment by Odianosen25** [comment]
Closing this issue please, and @simonvanderveldt do reopen is any further questions arises.

**Comment by simonvanderveldt** [comment]
@Odianosen25 Thanks for the reminder.
In the end I used this, I only have 1:1 relationships between friendly name and entities, so this works fine.
```
sensor_states = self.get_state(entity="sensor")
illuminance_entity_id = None
for sensor_id, sensor_data in sensor_states.items():
    if sensor_data["attributes"]["friendly_name"] == "friendlyname":
        illuminance_entity_id = sensor_id
```

I do think it would be nice to have a convenience function for this, but I can also understand the desire to keep the codebase small.

Thanks for the pointers @acockburn and @ReneTode !
