### ISSUE TITLE
Feature request: Allow a dashboard to import an arbitrary js file

### ISSUE THREAD

**Issue by mad-ady** [home-assistant/appdaemon#59]
There are some dashboard use cases which may be difficult to implement without some user code running in the browser after the dashboard has been loaded. Some examples are:
 - changing style-sheets for DOM elements where no change is allowed via the configuration
 - implementing custom code that, for examples triggers loading a different dashboard after a period of time (cycling through dashboards)
 - further custom development

In order to implement those I suggest adding a dashboard global parameter that points to a js file (either local or a URL) that is included in the generated HTML file after the required javascript code is loaded. The user's javascript code could then use something like ```$( document ).ready()``` to add their custom code to be executed according to their needs.

If I manage to find where to add such functionality, I'll submit a PR.

**Comment by acockburn** [comment]
If I understand you correctly, you can already do this via the head and body includes feature in the skinning.
