### ISSUE TITLE
HADashboard script widget status

### ISSUE THREAD

**Issue by rp3tya** [home-assistant/appdaemon#596]
The script widget toggles back when it is clicked even if the script is still running. The widget will show the correct status only if the dashboard is reloaded. Otherwise the widget shows wrong status and is unusable with long-running scripts (eg. those with hours of delays).

**Comment by ReneTode** [comment]
there is no way to tell if a script is running or not. the widget sends a service call to HA and then it has done its job,
if you want to know if a script is running you could do the following:
add an input_boolean in HA
add an automation in HA (or use an app) that starts the script
at the end from the script set the input_boolean to off
use that input_boolean with an input_boolean or switch widget.

**Comment by rp3tya** [comment]
Ended up using a switch widget to achieve the desired effect.
Actually also HA uses different UI controls for different scripts: "Scripts in the Overview panel will be displayed with an EXECUTE button if the device has no delay: or wait: statement, and as a toggle switch if it has either of those."
The script widget is an execute button, while for long-running scripts a switch is more appropriate. Maybe worthwhile to be mentioned in the widget documentation.
