### ISSUE TITLE
Support GET requests in API endpoints

### ISSUE THREAD

**Issue by sriramsv** [home-assistant/appdaemon#600]
Currently, the REST API endpoint only support a `POST` request to be made to them, I have a use case where I need to just to a GET to query some internal state I would like to maintain inside the appdaemon function context. Would be really useful if you could support GET and POST

**Comment by Odianosen25** [comment]
Hello @sriramsv,

In the next update, AD will be able to support GET by default over the REST API. You can check that now, using AD 4.0 in dev.

Regards

**Comment by Odianosen25** [comment]
I will be closing this @sriramsv, kindly reopen is still needed.

Kind regards

**Comment by pcmihnea** [comment]
Hi, sorry to necro the thread, but it's the only result related to this question. As per current stable release, https://appdaemon.readthedocs.io/en/4.2.3/APPGUIDE.html#restful-api-support, only POST requests are supported. Is there any way to enable GET requests on AppDaemon HAOS add-on v0.11.0?

**Comment by acockburn** [comment]
Well it just so happens that I was in that area of code working on something else so I added GET method support - it's currently in dev and will be part of the net release (4.3.0)

**Comment by pcmihnea** [comment]
Hah, now that's a lucky coincidence. I'll check the dev commit then. Thanks!
