### ISSUE TITLE
Optional arguments for weather widget

### ISSUE THREAD

**Issue by bhaap** [home-assistant/appdaemon#62]
I wonder if you could add the function to define entities for the weather widget. 

Like optional arguments for all the entities. and if nothing is defined it will got to default aka. Dark sky.

Im asking because i have my own weather station that i collect data from :) (and also dark sky sucks anywhere else but US and UK)

**Comment by acockburn** [comment]
I have something like that in mind - the weather widget needs to be a lot more flexible I agree, I'll add it to the list!

**Comment by bhaap** [comment]
Thank you. (I tried to modify it to check other sensors but failed). dashbooard loads up to the weather widget but then after that just gray squares xD.

**Comment by acockburn** [comment]
This is on my list as a feature request so closing.
