### ISSUE TITLE
compatibility for requests-2.16.0

### ISSUE THREAD

**Issue by cycl0psg** [home-assistant/appdaemon#63]
After updating to requests-2.16.0 (automatically updated when updating home assistant to 0.45.1) appdaemon won't start anymore:

`May 27 13:45:56 appdaemon[1407]: Traceback (most recent call last):
May 27 13:45:56 appdaemon[1407]: File "/usr/local/bin/appdaemon", line 11, in <module>
May 27 13:45:56 appdaemon[1407]: load_entry_point('appdaemon==1.5.2', 'console_scripts', 'appdaemon')()
May 27 13:45:56 appdaemon[1407]: File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
May 27 13:45:56 appdaemon[1407]: return get_distribution(dist).load_entry_point(group, name)
May 27 13:45:56 appdaemon[1407]: File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
May 27 13:45:56 appdaemon[1407]: return ep.load()
May 27 13:45:56 appdaemon[1407]: File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2302, in load
May 27 13:45:56 appdaemon[1407]: return self.resolve()
May 27 13:45:56 appdaemon[1407]: File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
May 27 13:45:56 appdaemon[1407]: module = __import__(self.module_name, fromlist=['__name__'], level=0)
May 27 13:45:56 appdaemon[1407]: File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 30, in <module>
May 27 13:45:56 appdaemon[1407]: import appdaemon.homeassistant as ha
May 27 13:45:56 appdaemon[1407]: File "/usr/local/lib/python3.4/dist-packages/appdaemon/homeassistant.py", line 8, in <module>
May 27 13:45:56 appdaemon[1407]: from requests.packages.urllib3.exceptions import InsecureRequestWarning
May 27 13:45:56 appdaemon[1407]: ImportError: No module named 'requests.packages'
`

I had to manually downgrade requests to the previous version: sudo pip install --upgrade requests==2.14.2

**Comment by acockburn** [comment]
My Hass is still using 2.14.2.

In general this is why it is good to use a virtual environment.

I'll take a quick look and see if I can reproduce it.
