### ISSUE TITLE
Option to not set the TZ environment variable

### ISSUE THREAD

**Issue by Hate-Usernames** [home-assistant/appdaemon#65]
The following line in [appdaemon.py](https://github.com/home-assistant/appdaemon/blob/dev/appdaemon/appdaemon.py#L1662) causes all of the callbacks in my setup to run one hour late during daylight saving time:
`os.environ['TZ'] = conf.time_zone`
Which was introduced in version 1.3.2

Both `datetime.datetime.now()` and the unix `date` command report the correct date when run independently of appdaemon, as does the initial log entry:
`2017-06-11 17:09:42.740172 INFO AppDaemon Version 1.5.2 starting` <-- this is the correct time
`2017-06-11 16:09:53.338815 INFO Got initial state` <-- Now we have an incorrect time

The system `TZ` environment variable is set correctly at system startup, however my system requires the [extended format](https://www.gnu.org/savannah-checkouts/gnu/libc/manual/html_node/TZ-Variable.html) to correctly adjust for DST rather than the simpler Region/City format used in the HA config.

Is it possible to adjust this to one of the following options:
* Only set `TZ` if it is currently blank
* Provide an option (defaulting to False) to use the system supplied timezone
* Get the current time using the same method as home assistant (which reports the correct time on my system).

**Comment by acockburn** [comment]
Sure, I'll take a look at this - for testing, what is your actual timezone?

**Comment by Hate-Usernames** [comment]
The correct system timezone is:
`TZ=GMT+0BST-1,M3.5.0/01:00:00,M10.5.0/02:00:00`

This is equivalent to Europe/London, which is specified in the HA config file, but not supported by the OS.

Other common options are listed, for example, [here](http://www.remotemonitoringsystems.ca/time-zone-abbreviations.php) which would presumably have a similar effect.

**Comment by acockburn** [comment]
In the next release I have added the ability to specify a timezone to explicitly override the one that AppDaemon gets from HASS - I tested with your TZ string and it seems to work ok. This will be in 2.0.4 when I release it.
