### ISSUE TITLE
HADashboard V2 Request: input_select

### ISSUE THREAD

**Issue by duckpuppy** [home-assistant/appdaemon#66]
I want to make a dashboard for my kid's room, and part of that is picking from a specific list of playlists from an input_select and running a script that starts the playlist playing on a music player in the room.  I've got all that working right now in HA, but there's no input_select widget for HA Dashboard V2.

Is the input_select widget on the roadmap?

**Comment by acockburn** [comment]
Yes it is - I'll be looking at that after the beta is finished.

**Comment by acockburn** [comment]
This is on my list so closing.
