### ISSUE TITLE
Wrong formulas for latitude and longitude in scheduler.py

### ISSUE THREAD

**Issue by Burningstone91** [home-assistant/appdaemon#680]
Someone on the home assistant forum noticed, that the formulas to validate longitude and latitude are wrong in the scheduler.py for the init_sun method.

**if -90 > latitude < 90:** 
should be 
**if -90 > latitude or latitude > 90:**
With the current formula, a latitude of 100 would be a valid latitude.

The same goes for longitude.

**Comment by ReneTode** [comment]
better readable would be:

**if latitude < -90 or latitude > 90:**

but i think you are right
the existing formula gives
if True<90: for any value above -90

**Comment by Burningstone91** [comment]
Yes, totally agree on the readability.
I quickly tested the current implementation with a small python script and it turns out, that it indeed wouldn't give an error if the latitude is above 90.

**Comment by acockburn** [comment]
Well that's what you get for copying code ;)

Fixed in dev.
