### ISSUE TITLE
Cannot listen to DEBUG Log entries

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#683]
Tried to listen to `DEBUG` log entries using the `listen_log`, but unfortunately it doesn't report it back.

I found out it is not even getting into the stream, so this is something internal I can't seem to find.

Regards

**Comment by acockburn** [comment]
It was a design choice to not include DEBUG level log entries in the stream.

**Comment by Odianosen25** [comment]
Oh ok.

Just that in the plugin, if wanting to to get remote debug log it would not be possible, though the others work.

I do understand so will be closing this for now. Thanks

**Comment by acockburn** [comment]
If you want to add it, I'll take a PR - I just didn't see the value at the time.
