### ISSUE TITLE
AppDaemon log messages not sent to listen_log() callback

### ISSUE THREAD

**Issue by mattthewclayton** [home-assistant/appdaemon#684]
Hey, I liked this guys idea of sending notifications when apps go astray but when I tried to fix up his app, I noticed that it just doesn't work anymore because of some extra checking done in appdaemon.

Idea from here:
https://github.com/eifinger/appdaemon-scripts/blob/master/appWatcher/appWatcher.py

I found just removing the 'name != "AppDaemon"' check in this block of code fixes the issue, I was going to submit a pull request but no only is master completely different to dev now, I also do not understand the reasons for this check (I assume it's to prevent some sort of infinite loop situation)

```
    def process_log_callback(self, level, message, name, ts):
        with self.log_callbacks_lock:
            for thisname in self.log_callbacks:
                if thisname != name and name != "AppDaemon":
                    try:
                        self.log_callbacks[thisname](name, ts, level, message)
                    except:
                        self.err("WARNING", '-' * 60)
                        self.err("WARNING", "Unexpected error in log callback for: {}:".format(name))
                        self.err("WARNING", '-' * 60)
                        self.err("WARNING", traceback.format_exc())
                        self.err("WARNING", '-' * 60)
                        if self.errfile != "STDERR" and self.logfile != "STDOUT":
                            self.log("WARNING", "Logged an error to {}".format(self.errfile))
```

**Comment by acockburn** [comment]
Yes, this is there for loop prevention

**Comment by mattthewclayton** [comment]
Fair enough, well I don't want to mess with that..

I just took the effort to move to v4.0.0+, this does not happen on the tip of dev branch so I will just close this issue.

Thanks,
Matt
