### ISSUE TITLE
Feature Request: Need Event Registry to store custom event

### ISSUE THREAD

**Issue by sriramsv** [home-assistant/appdaemon#686]
There is no way to add custom event callbacks in AD currently unless we use the homeassistant event system. This unnecessarily causes API calls to be made to HA if we want to use custom events.

If there was a eventRegistry inbuilt into AD, we can leverage custom callbacks effectively.
```
class EventRegistry:
    funcdict = {}

    @staticmethod
    def register(key, func):
        EventRegistry.funcdict[key] = func

    @staticmethod
    def get_callbacks():
        return EventRegistry.funcdict

    @staticmethod
    def run(key, kwargs):
        if key not in EventRegistry.funcdict:
            raise KeyError
        try:
            func = EventRegistry.funcdict[key]
            if kwargs:
                return func(**kwargs)
            return func()
        except:
            raise
```

```
def hello(self, kwargs):
  self.log("hello")

EventRegistry.register("hello", hello)
EventRegistry.run("hello")
```

**Comment by ReneTode** [comment]
@sriramsv please before you ask for features check if it isnt already in the dev version which is in beta in the moment
you can find the dev docs here
https://appdaemon.readthedocs.io/en/dev/index.html

inside that you will find fire_event which will fire an event in the AD bus.

https://appdaemon.readthedocs.io/en/dev/AD_API_REFERENCE.html#appdaemon.adapi.ADAPI.fire_event
