### ISSUE TITLE
[DISCUSSION] How to monitor AppDaemon

### ISSUE THREAD

**Issue by wsw70** [home-assistant/appdaemon#688]
Now that AppDaemon became the center of the universe and a condition to peace in my household I am wondering how best to monitor its functionality.

Right now I am just making sure that the docker container it runs in is alive and in a proper running state. I feel that this is not enough as it is very robust to misconfigurations and its threaded nature makes it resilient.

What would be the right elements to check in order to ensure that what was configured is actually operational? I understand that the correctness of the actual automation code is out of scope, but at least knowing that is configured in `apps.py` actually runs.

How to define "actually runs"? Is there an indication in AppDaemon that a class was correctly loaded?

I would be glad to build a simple API as an add-on to expose this information and raise a PR.

**Comment by ReneTode** [comment]
to see if it runs, you simply look at the log files.
there you see if an app is added correctly, if no errors then everything is allright.

in appdaemon 4.0 (which is now in beta) we got our admin interface.
that will show you all running apps, threads, callbacks, and more.

**Comment by acockburn** [comment]
AD 4 has a very comprehensive (albeit undocumented) REST API. It's quite likely that it already does what you need.  For instance, you can grab all of the app objects in the admin namespace to find their current state - the state will reflect if they are inactive or have a compilation error. You can also query callbacks to determine if a given app has any active callbacks registered.

**Comment by acockburn** [comment]
Another possibility would be to subscribe to the (undocumented) stream and raise an alarm if you don;t see anything for a period of time (there is a guaranteed heartbeat there every second in the uptime sensor)

**Comment by wsw70** [comment]
@acockburn this is fantastic news, thank you. If there is no documentation I will dig into the code to try to understand the endpoint. The features you mention are more than enough for my monitoring needs (and vastly superior to what I have today)

**Comment by acockburn** [comment]
We will get around to documenting it - but for now check out http.py, it's all in there.

**Comment by acockburn** [comment]
Also, if you are looking at the stream, it's about to get some significant changes in the next few days, so maybe hold off on that. The REST API is pretty stable however.

**Comment by wsw70** [comment]
> check out http.py, it's all in there

Thanks a lot @acockburn - I saw that the routing in `setup_api_routes` indeed has everything needed.
