### ISSUE TITLE
Unable to run HaDashboard inside simple docker image

### ISSUE THREAD

**Issue by cannfoddr** [home-assistant/appdaemon#74]
Been tinkering since the betas but ran into an issue where I could not reliably configure the dash_url to work inside a docker image:

- **set dash_url = http://0.0.0.0:5050** - this sort of works but all sublinks within pages also try to use 0.0.0.0 which causes them to fail

- **set dash_url = http://_docker host ip_:5050** - this fails as the address cannot be bound but I am guessing that the links will all be correct 

- **set dash_url = http://_docker container ip_:5050** - this binds but the links are unreachable from outside of the container

I was hoping with V2 release that this might have been addressed?

**Comment by acockburn** [comment]
I just completed the beta, now I am planning on looking into support for hass.io which will likely involve some docker work as well, so I'll be looking into this.

**Comment by mezz64** [comment]
You can resolve this with the current release by running your container in host mode.  It's not ideal, but it's the easiest solution.

**Comment by acockburn** [comment]
Thanks @mezz64 - for reference until I fix this, what dash_url are you using when you run in host mode? The actual docker host IP?

**Comment by mezz64** [comment]
@acockburn Yes, the actual docker host IP is what I have specified.
```dash_url: http://192.168.11.5:5056```

**Comment by acockburn** [comment]
Thanks!

**Comment by acockburn** [comment]
Should be fixed in 2.0.1
