### ISSUE TITLE
Docker hub image?

### ISSUE THREAD

**Issue by kolayuk** [home-assistant/appdaemon#75]
I would like to run it with docker-compose, have you ready-to-go image on docker hub? I cant find it here https://hub.docker.com/u/homeassistant/?page=2

**Comment by acockburn** [comment]
Not an official one as yet - it's on my list along with hass.io support.

**Comment by kolayuk** [comment]
OK, I will try to build & attach container to docker-compose myself, thank you! Hope, I will refuse ugly yaml-based automations in HASS with your solution...

**Comment by acockburn** [comment]
As of 2.0.1, just released, there is now an official docker hub image under `acockburn/appdaemon:latest`
