### ISSUE TITLE
be more concrete on the home assistant tutorial

### ISSUE THREAD

**Issue by danielo515** [home-assistant/appdaemon#755]
Hello and thanks for this great tool and it's great documentation.
However, I came here for the home assistant tutorial, and I'm a bit lost.
The examples are great, and I have the appdaemon addon installed, but, how I'm supposed to add my apps?  Where should I put them? How do I tell the addon to run them?

Thanks.

**Comment by danielo515** [comment]
Ok, I see that after running the addon for the first time it creates a configs folder, great. In any case, it will be nice to add a small note about that for dumb users like me.

Regards

**Comment by ReneTode** [comment]
@danielo515 the addon is just a small piece of code that makes it possible to install and start appdaemon on hassio.

the addon isnt created by us, and we dont have control over it.

**Comment by danielo515** [comment]
Hello @ReneTode 
I can understand that. But maybe a small documentation about how it is supposed to work? Like, saying that X or Y folders will be created after the addon starts. That is not something specific to appDaemon, looks like something tied to this plugin.

Regards

**Comment by ReneTode** [comment]
> looks like something tied to this plugin.

indeed, and we dont have anything to do with that plugin.
we cant say that X or Y folders are created by appdaemon, because appdaemon doest create the folders for you.
our docs: 
https://appdaemon.readthedocs.io/en/latest/index.html

tell you in the installation and configuration part how to create your config dir and how to configure it and how to start appdaemon.

because none of us uses hassio (and so also not the addon) we cant tell where the addon creates something or what settings are set to what.

if you want some information about that then you need to look up the docs for addons, but not the docs for appdaemon.

**Comment by danielo515** [comment]
Ok, I see.
It is very hard to get help about any HASSIO addon because, if you ask on the hassio addon repo, they point you to the thing they are wrapping (in this case appdaemon) if you ask on the repo of the thing that is wrapped by a hassio addon they point you to the addon repository.

It is very convenient that you have a noobs tutorial for HASSIO and appdaemon, but I feel it is still unclear how they interact.
Thanks in any case

**Comment by ReneTode** [comment]
we  can help you understand the way they interact.
just come to discord and we can talk about it.

its indeed not easy to decide where you need to be. but it helps if you read the logs.
the first part of the logging is created by the addon. untill you see the line where appdaemon starts and tells you which version from appdaemon you are working with.

appdaemon works on any system that runs python. in almost all you need to take care of your own configuration. thats why that is in the docs.

hassio is just 1 platform, that takes away the need for you to worry about settings and configuration.
that comes with a downside. if you let others do the work for you, you dont have control over how they do it.

our (my) tutorials are not for hassio specific. they dont talk about installing and configuring.
there is enough about that on the internet. (google for it)

my goal is to help people work with appdaemon, after they have installed it. and then i expect they know where to find there configuration ;) 

please close this issue if you have the answers you need.
