### ISSUE TITLE
Bad request when try to notify

### ISSUE THREAD

**Issue by danielo515** [home-assistant/appdaemon#756]
Hello,
following the docs I'm trying to call one of my notify services from appdaemon.
Something as simple as this:
`self.notify("test", title="test")`

Triggers the following error

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://hassio/homeassistant/api/services/notify/notify
```

It happens for every notify service that I tried. They work fine inside hassio, so there must be a misalignment between appdaemon and the latest hassio.
I don't know much about python, so sorry for not providing more clues. I would love to see the entire error response, or the provided params, but I don't know how.

Regards

**Comment by danielo515** [comment]
Ok, it was my mistake.
What I did to find my error (in case it is of any help)
I started using call_service instead of just notify:

```python
self.call_service("notify/telegram",message="test")
```

That worked without any problem, so then I started to translate that back to notify. I had to wrap my calls to get smaller error messages

```
    try:
      self.notify("Test msg",name="notify.telegram")
    except Exception as e:
      print(e)
      self.log("Dam, failed")
```

That started to give me clues like the url `Bad Request for url: http://hassio/homeassistant/api/services/notify/notify.telegram`

The notify service name is what I usually use on hassio, so I just copy pasted it. Then I realize that it was working when I was calling `notify/telegram` on call_service, so I just tried to switch to that. Then I got this error:
`too many values to unpack (expected 2)`
Since I was providing the correct amount of params to the notify function, the error must be somewhere else, and I don't know why I started suspecting that the error could be on the url construction part, so I changed the name again: ` self.notify("Test message",name="telegram")`
And that worked!!
So the name to provide is just the notification service name, without any prefix or anything similar. It was a bit confusing to find out, and I'm not sure if this is mentioned on the docs.

Regards

**Comment by Odianosen25** [comment]
Glad you fixed it, will be closing this if you don’t mind.

Regards

**Comment by danielo515** [comment]
> it will help you a lot if you look there first. ;)

Indeed I looked there first, I'm not that bad person 🤣
But they docs does not specify that you don't need to put the `notify/` prefix on the name. In fact, the following line could lead to the confusion.

>  If the name is not specified it will default to notify/notify.

Making you think that maybe the correct way of naming notification services is `notify/name`.
Thanks for the advise about self.log. Can I ask why? Apart from not getting the timestamp, what is bad about it?

**Comment by ReneTode** [comment]
we hardly can tell you everything that you DONT need to specify, can we?
and if we should change the line to:
> If the name is not specified it will default to notify.

noone would understand it ;) 
it clearly states that nofify.notify or notify/notify is a service.
and yeah HA didnt make it easy by also chosing notify as name for the general service. ;) 

the difference between print and self.log is that print goes to the console/terminal and log to the logs.
if you learn yourself that you use the log and not print, you will not come in a situation where you miss stuff when the console/terminal isnt there.
logging is saved, printing isnt.

its not that its really bad, and that it breaks stuff, but its just saver to get used to logging and if needed trailing the logs. (saves you also the trouble to look at different places)

**Comment by danielo515** [comment]
Thanks @ReneTode for your answers.
Hassio is quite complex, even reading their documentation, so tying to make something external interact with it will be tricky too, I didn't expected less.
At least, in the future people like me (or even future-me) will be able to find this issue in case the have the same problem.

Regards

**Comment by ReneTode** [comment]
dont confuse hassio with home assistant.
home assistant is a program that runs on the hassio platform

i never found the docs complex, or at least not when it comes to adding components or installing.
and i dont think thay much people will have that problem. when they have questions they ask on the forum or on discord.
appdaemon is used by (hundred)thousends of people and you are the first that ever had that issue.
i think that says more about how you read docs and try things then about the issue ;) 

thats no problem, not everyone sees things the same (i know, i always have a different view ;) )
so please if you have trouble, dont understand something, or just dont know how to go on, visit our discord server and we will help you in any way we can.
