### ISSUE TITLE
Reconsider deepcopying of callback keyword arguments

### ISSUE THREAD

**Issue by efficiosoft** [home-assistant/appdaemon#773]
Hi @acockburn 

Recently, [this issue](https://github.com/efficiosoft/hass-apps/issues/39) was raised. It seems that AD 4.0.0b2 deepcopies keyword arguments for callbacks. I don't think this is a good idea, as it basically disallows you to pass arbitrary objects to callback functions.

Deepcopying creates a new object and hence a comparison using the `is` operator with the originally passed object returns `False`, which seems magical and unexpected. Even worse, if you pass an object holding a reference to the `App` object, this recursively copies **the whole** AppDaemon, naturally including everything.

Is there a particular reason why you added this deepcopy step?

Best regards
Robert

**Comment by ReneTode** [comment]
@acockburn changed to deepcopy at the end of december 2018.
i dont know why, but i guess he had his reasons.
as soon as he has the time he will take a look at it.

**Comment by efficiosoft** [comment]
> @acockburn changed to deepcopy at the end of december 2018.
> i dont know why, but i guess he had his reasons.

Ah, at least this issue came up now. The thing is that people may don't even notice the deepcopying even when they pass custom objects, it's just pretty dangerous because it potentially copies several MiB of AppDaemon state regularly without notice, which is a performance issue at least and this probably was just not considered when implementing.

A solution could be one of:

1. Don't deepcopy user-provided keyword arguments. Given that nothing stands against it, I'd prefer this route, since it's the behavior I think one would expect when he passes a mutable object.

2. Clearly document that keyword arguments must be safely deepcopyable. In fact, this would make it dangerous to pass something different than Python's built-in types, because you always need to ensure there is no link to potentially large objects that would be deepcopied alongside.

3. Make deepcopying keyword arguments a per-app opt-out feature.

> as soon as he has the time he will take a look at it.

No hurry, but it would be nice if this could be sorted out before the final release.

**Comment by ReneTode** [comment]
IF andrew wants to change this, or add things to documents, he will do so.
if he decides to leave it like it is, because he has reasons why it is as it is, then i guess youll need to live with it.

i the end its always up to him to decide what is changed and what isnt, and when and how is also up to him.

**Comment by efficiosoft** [comment]
@ReneTode You're so right.

**Comment by acockburn** [comment]
Which type of callback? For state, if a deepcopy isn't used, an app can unwittingly change AD's internal state via the new state argument which doesn't seem like a good idea, however since you found the issue in schedy I assume it was a scheduler callback that was affected?

**Comment by acockburn** [comment]
Had a look at the code and don;t remember making that particular change - I'll think on it some more but it can probably be safely reverted since it is all app stuff and not AD's interbals we are talking about here.

**Comment by acockburn** [comment]
OK, I reverted it in dev - will be in the next version (4.0.0)

**Comment by efficiosoft** [comment]
> Which type of callback? For state, if a deepcopy isn't used, an app can unwittingly change AD's internal state via the new state argument which doesn't seem like a good idea

Definitely, I was only talking about user-provided keyword arguments, not the positional ones inserted by AD.

> OK, I reverted it in dev - will be in the next version (4.0.0)

Great, thanks a lot for your prompt reply!

Best regards
Robert

**Comment by efficiosoft** [comment]
Hi again,

This still seems to be a problem in 4.0.1. Consider this app:

```
from appdaemon.plugins.hass import hassapi

class FatObj:
    def __deepcopy__(self, memo=None):
        raise RuntimeError("Don't copy me!")

class App(hassapi.Hass):
    def initialize(self):
        self.run_in(lambda *a, **kw: None, 1, fatobj=FatObj())
```

It generates this traceback on AppDaemon 4.0.1:

```
ad_1    | 12:00:14 AppDaemon  INFO    : Initializing app deepcopytest using class App from module deepcopytest
ad_1    | 12:00:14 AppDaemon  WARNING : ------------------------------------------------------------
ad_1    | 12:00:14 AppDaemon  WARNING : Unexpected error during process_event()
ad_1    | 12:00:14 AppDaemon  WARNING : ------------------------------------------------------------
ad_1    | 12:00:14 AppDaemon  WARNING : Traceback (most recent call last):
ad_1    |   File "/usr/local/lib/python3.8/site-packages/appdaemon/events.py", line 206, in process_event
ad_1    |     mydata = deepcopy(data)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 146, in deepcopy
ad_1    |     y = copier(x, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 229, in _deepcopy_dict
ad_1    |     y[deepcopy(key, memo)] = deepcopy(value, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 146, in deepcopy
ad_1    |     y = copier(x, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 229, in _deepcopy_dict
ad_1    |     y[deepcopy(key, memo)] = deepcopy(value, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 146, in deepcopy
ad_1    |     y = copier(x, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 229, in _deepcopy_dict
ad_1    |     y[deepcopy(key, memo)] = deepcopy(value, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 146, in deepcopy
ad_1    |     y = copier(x, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 229, in _deepcopy_dict
ad_1    |     y[deepcopy(key, memo)] = deepcopy(value, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 146, in deepcopy
ad_1    |     y = copier(x, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 229, in _deepcopy_dict
ad_1    |     y[deepcopy(key, memo)] = deepcopy(value, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 153, in deepcopy
ad_1    |     y = copier(memo)
ad_1    |   File "/conf/apps/deepcopytest.py", line 6, in __deepcopy__
ad_1    |     raise RuntimeError("Don't copy me!")
ad_1    | RuntimeError: Don't copy me!
ad_1    |
ad_1    | 12:00:14 AppDaemon  WARNING : ------------------------------------------------------------
ad_1    | 2020-02-19 12:00:16.004549 WARNING deepcopytest: ------------------------------------------------------------
ad_1    | 2020-02-19 12:00:16.005267 WARNING deepcopytest: Unexpected error during exec_schedule() for App: deepcopytest
ad_1    | 2020-02-19 12:00:16.005944 WARNING deepcopytest: Args: {'name': 'deepcopytest', 'id': '7adbc6455a9c4d93945a235de8837b5b', 'callback': <function App.initialize.<locals>.<lambda> at 0x7ff153a41670>, 'timestamp': datetime.datetime(2020, 2, 19, 11, 0, 16, tzinfo=<UTC>), 'interval': 0, 'basetime': datetime.datetime(2020, 2, 19, 11, 0, 16, tzinfo=<UTC>), 'repeat': False, 'offset': 0, 'type': None, 'pin_app': True, 'pin_thread': 2, 'kwargs': {'fatobj': <deepcopytest.FatObj object at 0x7ff153c20df0>, 'deepcopy': False}}
ad_1    | 2020-02-19 12:00:16.006593 WARNING deepcopytest: ------------------------------------------------------------
ad_1    | 2020-02-19 12:00:16.008118 WARNING deepcopytest: Traceback (most recent call last):
ad_1    |   File "/usr/local/lib/python3.8/site-packages/appdaemon/scheduler.py", line 130, in exec_schedule
ad_1    |     await self.AD.threading.dispatch_worker(name, {
ad_1    |   File "/usr/local/lib/python3.8/site-packages/appdaemon/threading.py", line 668, in dispatch_worker
ad_1    |     await self.add_to_attr("_threading", "admin", "{}_callback.{}".format(myargs["type"], myargs["id"]), "fired", 1)
ad_1    |   File "/usr/local/lib/python3.8/site-packages/appdaemon/state.py", line 388, in add_to_attr
ad_1    |     state = await self.get_state(name, namespace, entity_id, attribute="all")
ad_1    |   File "/usr/local/lib/python3.8/site-packages/appdaemon/state.py", line 335, in get_state
ad_1    |     return maybe_copy(state)
ad_1    |   File "/usr/local/lib/python3.8/site-packages/appdaemon/state.py", line 326, in <lambda>
ad_1    |     maybe_copy = lambda data: deepcopy(data) if copy else data
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 146, in deepcopy
ad_1    |     y = copier(x, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 229, in _deepcopy_dict
ad_1    |     y[deepcopy(key, memo)] = deepcopy(value, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 146, in deepcopy
ad_1    |     y = copier(x, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 229, in _deepcopy_dict
ad_1    |     y[deepcopy(key, memo)] = deepcopy(value, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 146, in deepcopy
ad_1    |     y = copier(x, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 229, in _deepcopy_dict
ad_1    |     y[deepcopy(key, memo)] = deepcopy(value, memo)
ad_1    |   File "/usr/local/lib/python3.8/copy.py", line 153, in deepcopy
ad_1    |     y = copier(memo)
ad_1    |   File "/conf/apps/deepcopytest.py", line 6, in __deepcopy__
ad_1    |     raise RuntimeError("Don't copy me!")
ad_1    | RuntimeError: Don't copy me!
ad_1    |
ad_1    | 2020-02-19 12:00:16.008733 WARNING deepcopytest: ------------------------------------------------------------
ad_1    | 2020-02-19 12:00:16.009291 WARNING deepcopytest: Scheduler entry has been deleted
ad_1    | 2020-02-19 12:00:16.009832 WARNING deepcopytest: ------------------------------------------------------------
```

Seems it breaks at two different points, once directly when processing the event and once when the kwargs are stored in the admin namespace somehow...

Is this a new issue or just the previous one not fixed yet?

Thanks and best regards
Robert

**Comment by ReneTode** [comment]
you could also do it in a way that doesnt create the error.

sometimes it helps to think: if the way i am used to doing things doesnt work, then lets try it in another way ;)
