### ISSUE TITLE
Weather widget: Uncaught TypeError: child.ViewModel.title is not a function

### ISSUE THREAD

**Issue by gingerlime** [home-assistant/appdaemon#78]
Hello,

Thanks for creating HADashboard and AppDaemon. It's really neat.

I'm playing around with some dashboards, but am seeing these errors in the console when I use the weather widget:

```
Uncaught TypeError: child.ViewModel.title is not a function
    at Object.success (dashboard.js:147)
    at i (jquery-3.1.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.1.1.min.js:2)
    at A (jquery-3.1.1.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-3.1.1.min.js:4)
```

I have darksky installed and configured with all the required sensors as per the readme. I can also see on the Network tab that values are returned correctly. And I see all those values on my HA states page. However, the widget isn't working and I can see those errors above.

![2017-07-09_550x172_sceenshot](https://user-images.githubusercontent.com/524274/27996815-bac22ea8-64ea-11e7-983c-5e24d7efc8ea.png)

Here are a few screenshots from the console after setting a breakpoint where the error happens

![2017-07-09_444x417_sceenshot](https://user-images.githubusercontent.com/524274/27996820-ea5e7446-64ea-11e7-8377-0716e644f6ea.png)
![2017-07-09_548x231_sceenshot](https://user-images.githubusercontent.com/524274/27996821-ea5e818e-64ea-11e7-8908-767035f43421.png)
![2017-07-09_682x433_sceenshot](https://user-images.githubusercontent.com/524274/27996822-ea5efdc6-64ea-11e7-9c7e-b45bc626b3c0.png)

Am I doing something wrong? Would appreciate some help :)

**Comment by acockburn** [comment]
I think some underlying error is causing my code to try and put an error in the title field which exists for other widgets but not for Weather - I'll add one as I have seen this a couple of times. In the meantime, the most likely explanation is a missing Dark Sky sensor - I know you mentioned that you have them all but Weather is so simple that I can;t think of anything else that could go wrong!

I'll put in the fix and drop a new release then you can retry and might actually see a relevant error.

**Comment by gingerlime** [comment]
Thanks for the quick response, @acockburn. I doubled checked and If you look at the screenshot above, I think I have all required sensors configured... Happy to try anything if it helps debugging this.

**Comment by acockburn** [comment]
Try upgrading to 2.0.3 (just released) and see if you get an error message in the widget.

**Comment by gingerlime** [comment]
I'm using the docker image... If I pull the latest, would it upgrade?

**Comment by acockburn** [comment]
Give it a few minutes to build

**Comment by gingerlime** [comment]
![2017-07-09_263x261_sceenshot](https://user-images.githubusercontent.com/524274/27997221-101ff41c-64f4-11e7-9ce0-f035ee287d5d.png)

Thanks so much, @acockburn !

**Comment by acockburn** [comment]
Hmm, that shouldn't have fixed anything

Unless ... were you passing a title to it? That wasn't supported until just now and wasn't meant to be anything other than a debug tool ;)

**Comment by gingerlime** [comment]
I'm not passing any titles... Here's my dashboard config

```yaml
weather:
  widget_type: weather
office:
  widget_type: switch
  # ...
layout:
  - office, weather.weather(2x2)
```
