### ISSUE TITLE
Feature request docker for unraid.

### ISSUE THREAD

**Issue by Hellowlol** [home-assistant/appdaemon#80]
I would love to have a docker for unraid ^^

**Comment by acockburn** [comment]
From what I am told the existing docker setup should work for unraid - have you tried the latest version?

**Comment by mezz64** [comment]
The docker does indeed work as published with unraid there just isn't a pre-made template currently available.  You'll need to setup the container manually using the instructions provided.

**Comment by acockburn** [comment]
Thanks for the confirmation @mezz64 - closing this FR. More than happy to help on the forum if you need help getting this working.

**Comment by Hellowlol** [comment]
I was refering to the template. Ill see if cant make that instead. Thanks!

**Comment by acockburn** [comment]
Cool - I have no way of figuring that out as I don;t have an unraid, but if you make a template and explain how to use it I would be very happy to include it in the docs :)
