### ISSUE TITLE
now_is_between() has non-strict inequality semantics

### ISSUE THREAD

**Issue by ZzetT** [home-assistant/appdaemon#819]
I have the following app:
- turn the (decoration) lights on after the first motion is detected between a certain time A and B (for that I use the now_is_between() API)
- in addition, turn off the lights at time B (use run_daily callback)

In very rare cases, it happens that the lights are still one after time B. When I checked the HA logs, I saw that it indeed turned the lights off at time B, but also turned them on again in the same second.

I guess, that the reason for this is a race condition that happens because even at time B now_is_between() returns true.
See also:
https://github.com/home-assistant/appdaemon/blob/9c4db4e43fabc7d43c0e904a58cd324141f2c009/appdaemon/scheduler.py#L558

Maybe a hint in the docs would be good to clarify what "between" means which is not start_time < now() < end_time but with "non-strict inequality" semantics.
Do you think there is a chance to have a now_is_between() with "strict semantics"? Actually, it would also be fine for me, to subtract 1 minute from the time that I pass to now_is_between(), but from the docs this seems only be possible for sunset/sunrise.
Is there any other workaround? Or do I have to convert the time to UTC and do my calculations there?

**Comment by ReneTode** [comment]
a better way would be not to use now_is_between at all.

def init():
    self.listen_state(self.cb,"sensor.motion", new="on", constrain_start_time= "sunrise", constrain_end_time = "sunset")
    self.run_daily(self.cb2,"23:00:00")
def cb(...):
    # turn on lights
def cb2(...):
   # turn off lights
```
start time and and time can also be times or sunset/rise with offset
set the turn off 1 or more sec after the constrain ends, and you cant have them not turn off.

**Comment by ZzetT** [comment]
>set the turn off 1 or more sec after the constrain ends, and you cant have them not turn off.

But this also means that I have to convert the time (which is passed as a string parameter to the app) first to UTC, subtract 1 minute and convert it back to a datetime object, because I can't just write "23:00:00 - 00:01:00" right?

**Comment by ReneTode** [comment]
no indeed you cant substract a minute like that.
the expression you found is just 1 of the many, many possibilities to solve it.
