### ISSUE TITLE
Dashboard on older iPads broken by 4.0.0

### ISSUE THREAD

**Issue by acockburn** [home-assistant/appdaemon#841]
iPads running iOS 9 or earlier seem unable to correctly render dashboards since the upgrade to 4.0.0. The screen is loaded but all the tiles appear as unresponsive grey squares.

Reversion to 3.0.5 fixes the issue.

**Comment by acockburn** [comment]
I had initially suspected the upgrade to aiohttp from 3.44 to 3.6.2 may have caused this but a quick test still shows the issue.

**Comment by benleb** [comment]
> I had initially suspected the upgrade to aiohttp from 3.44 to 3.6.2 may have caused this but a quick test still shows the issue.

this upgrade fixed the api/http in py 3.8 afaik

**Comment by acockburn** [comment]
OK, I figured it out - this will be fixed in 4.0.1

**Comment by miraculixdruid** [comment]
This problem has re appeared in 4.1.0. Currently all my widgets are "blank". Are running all my dashboard on Ipad Gen1 and ios 9.3.5. Keeping my fingers crossed that this will be solved :)
