### ISSUE TITLE
Cannot start AppDaemon 4.x with SSL enabled in http component

### ISSUE THREAD

**Issue by crowbarz** [home-assistant/appdaemon#851]
According to the [documentation for the http component](https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#configuring-the-http-component) AppDaemon 4.x should support https if `dash_ssl_certificate` and `dash_ssl_key` are configured in the `http` section of `appdaemon.yaml`. However, these options seem to be ignored by AppDaemon, and the server on port 5050 doesn't respond to SSL TLS requests even when the options are configured:
```
$ curl -vvo- https://appdaemon.[example.com]:5050/
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to appdaemon.[example.com] (x.x.x.x) port 5050 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
^C
```

Looking at the [code for http.py](https://github.com/home-assistant/appdaemon/blob/dev/appdaemon/http.py#L103) it looks to me that SSL certificate options are parsed* and an SSL context is created from those options, but the context is only used in a [(now?) commented out section](https://github.com/home-assistant/appdaemon/blob/dev/appdaemon/http.py#L282). The web server seems to be now started later in [`start_server()`](https://github.com/home-assistant/appdaemon/blob/dev/appdaemon/http.py#L295) but it does not pass the SSL context to `aiohttp.web.TCPSite()` which [appears to accept an SSL context option](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.TCPSite).

If this can be solved simply by storing the SSL context during `_init()` in the `http` class and then passing it to `aiohttp.web.TCPSite()` during `start_server()`, then I can raise a PR for that, though I don't know the development framework used here well enough to test the change.

\* note: the options parsed by the code are called `ssl_certificate` and `ssl_key`, and not `dash_ssl_certificate` and `dash_ssl_key` as indicated in the [documentation](https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#configuring-the-http-component). In my testing, I tried both, but SSL didn't work with either. So it seems that either the code or the documentation is wrong - which one is intended to be correct?

**Comment by Odianosen25** [comment]
As at this point AD's SSL hasn't been enabled and we will fix it hopefully within the next release.

Regards

**Comment by acockburn** [comment]
What happened here was that the semantics for aiohttp changed and I couldn't immediately see the right way to pass the SSL context through so I commented it out and forgot to go back to it later.

If you know how to do this you can save me some time by submitting a PR ;)

**Comment by ReneTode** [comment]
this issue also makes that connecting from amazon or google isnt directly possible anymore, which makes that the alexa and dialogflow functions are out of order @acockburn 

unless people use a proxyserver.

**Comment by acockburn** [comment]
SSL support has now been re-added and will be available in the next release.

**Comment by Dio55** [comment]
> SSL support has now been re-added and will be available in the next release.

Unfortunately, it is still not working in version 0.2.1

**Comment by ReneTode** [comment]
@Dio55 there has been no next release from appdaemon.
you did upgrade the addon, but the addon is just a connector between appdaemon and hassio.

the version from appdaemon you have can be seen in the logs, and that addon version still uses the same version as 1 month ago.

**Comment by bruxy70** [comment]
@ReneTode , since your last comment, there were two relases:  4.0.2 (7 days ago), and 4.0.3 (6 days ago).
5 days ago there was the add-on update including app-daemon 4.0.3.

Does this mean that this is now working?

The documentation states that the only place where you can add the certificates is by `dash_ssl_certificate`, where it says it is there to "To enable https support for HADashboard". It is confusing as the name and documentation imply that it is for the dashboard. It does not mention HTTPS API (neither HTTPS for admin). Will that same dashboard certificate work for the API as well?

Btw, the example [here](https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#configuration-of-the-hass-plugin)  does include configuration of `api_ssl_certificate`. And the section Upgrading from 3.x does not include the note to remove these. So it adds to the confusion.

**Comment by ReneTode** [comment]
that example shows a AD3 configuration. so ignore it.

i cant tell if it should work now. @acockburn can tell you.
but i know that you should only configure SSL in the http section now, because api, dashboard and the admin interface are all on the same server now. (just different paths)

**Comment by acockburn** [comment]
We had 2 unexpected emergency fix releases due to a leap year bug, the fix for this will be in the next non-emergency release 4.0.4, sorry for the confusion!

**Comment by odelli** [comment]
Hi,

Just curious about any release plans that might fix this issue. AppDaemon 3 is not supported anymore, so SSL in version 4 is becoming crucial.

**Comment by odelli** [comment]
I'm sorry for bumping this, but I see no other way to draw attention to this problem.

**Comment by odelli** [comment]
I'm sorry for bumping this @acockburn and @ReneTode, but I see no other way to draw attention to this issue. See my previous post above.

**Comment by ReneTode** [comment]
sorry, i cant help you there.
im not part of the team anymore and so i have no knowledge about future releases.
youll need to wait for Andrew.
