### ISSUE TITLE
HASS API Presence Architecture

### ISSUE THREAD

**Issue by trankillity** [home-assistant/appdaemon#853]
The presence functionality currently operates off "device_tracker" entity status instead of "person" entity status. There are many situations where you would want device trackers that aren't attached to people, so the built-in functions of anyone_home(), noone_home(), everyone_home() report false positives.

Changing the architecture to enumerate through the state of "person" entities instead of "device_tracker" entities would be a much more reliable way of using these functions.

**Comment by Odianosen25** [comment]
Hello @trankillity,

Yes we are working on this, and will be fixed in the next release.

Regards

**Comment by trankillity** [comment]
Fantastic! Looking forward to simplifying my apps even more 😄

**Comment by acockburn** [comment]
Maybe not the next release, we are just about to drop a bugfix release, but soon after ...

**Comment by acockburn** [comment]
It wasn't in the next release, but it will be in the next release :) This will be in 4.0.2

**Comment by engrbm87** [comment]
Hello @acockburn , it seems this didn't make it in 4.0.2 Any chance you can include it soon.

**Comment by acockburn** [comment]
It’s in the dev branch, we just had to rush out a couple of emergency fixes for a leap year bug, it will be in the next planned release currently expected to be 4.0.4

**Comment by neographikal** [comment]
Just ran into this, this would be great!
