### ISSUE TITLE
input_select widget broken in AppDaemon 4.0.1

### ISSUE THREAD

**Issue by Dominion0815** [home-assistant/appdaemon#860]
Hi,

seems like input_select doesn't work anymore. You can test it with simple example code:

Error message:
    who_cooks: Error in widget definition '%s':
    who_cooks: parser says
    who_cooks: in "", line 2, column 10: entity: {{entity}} ^
    who_cooks: found unhashable key while constructing a mapping

Dashboard:
who_cooks:
    widget_type: input_select
    title: Cooks
    entity: input_select.who_cooks

Homeassistant:
input_select:
  who_cooks:
    name: Cooks
    options:
      - Paulus
      - Anne

Regards
Dominion

**Comment by ReneTode** [comment]
is it possible you got a custom widget?
because in AD 3 the line was
```
entity: {{entity}}
```
and in AD 4 that must be
```
entity: "{{entity}}"
```
which it is in the widget from AD 4 in the code.

**Comment by Dominion0815** [comment]
no I am using default input_select widget:
https://www.home-assistant.io/integrations/input_select/
https://appdaemon.readthedocs.io/en/stable/DASHBOARD_CREATION.html#input-select

**Comment by ReneTode** [comment]
how did you install AD 4?
please show the log from AD 4, from the moment you restart AD.
and please show the complete dashboard, as codeblock
to create a codeblock use 3x ` on an empty line before the code (and logs) and after the code
` not '

**Comment by Dominion0815** [comment]
ok my fault ... 
There was a leftover folder "custom_widgets" in ~/.homeassistant/conf/ ;(
Sliders working again after moving this old folder away.

**Comment by Dominion0815** [comment]
ok my fault ... 
There was a leftover folder "custom_widgets" in ~/.homeassistant/conf/ ;(
Sliders working again after moving this old folder away.
