### ISSUE TITLE
Log shows: Error calling Home Assistant service default/media_player/turn_off

### ISSUE THREAD

**Issue by scadaguru** [home-assistant/appdaemon#867]
After update to AppDaemon to 4.0.1 I am noticing the following warning/error in log.

`2020-01-30 13:45:44.021881 WARNING HASS: Code: 400, error: 400: Bad Request`
`2020-01-30 13:45:44.021633 WARNING HASS: Error calling Home Assistant service default/media_player/turn_off`

And here is the line of code which causes this:
`self.call_service("media_player/turn_off", entity_id = "media_player.living_display")`

And this is the line of code which starts media playing:
`self.call_service("media_player/play_media", entity_id = "media_player.living_display", media_content_id = "http://192.168.1.23:81/mjpg/cam9/video.mjpg?user=xxxx&pw=xxxx", media_content_type = "image/jpg")`

Troubleshooting already done:
1. I don't remember noticing this error in AppDaemon 3.0.
2. Entity exist in HA and it does stream media

I tried to see any breaking changes but didn't find any so asking for help here,
Thanks all.

**Comment by ReneTode** [comment]
the app looks in AD for namespace default.
did you change the namespacename in appdaemon.yaml?

**Comment by scadaguru** [comment]
No, I have not specified namespace in my appdaemon.yaml nor in app at all.
I wonder in that case why the only this service call causes issue I have many more other service call to Home Assistant without specifying namespace.
I appreciate your reply and it was so quick thank you so much.

**Comment by ReneTode** [comment]
the error tells that HA doesnt accept the service call.

so please check in HA if the service actually exist and if you can use it with that entity_id.
also in the case that the media_player is not playing.

you can also try if the service homeassistant/turn_off works better.
or even self.turn_off("media_player.living_display")

**Comment by scadaguru** [comment]
I think I found the issue and looks like self.run_in() call provides one more extra key:value which has thread details and that is causing issue.
Last function stop_streaming() loops through the kwargs and that has two items but I was expecting one.

```
  def show_media_on_google_displays(self, media_content_id):
    self.start_streaming(media_content_id, {'entity_id':self.entity_name_living})
    self.start_streaming(media_content_id, {'entity_id':self.entity_name_media})
    self.start_streaming(media_content_id, {'entity_id':self.entity_name_dining})

  def start_streaming(self, media_content_id, kwargs):
    for key, entity_name in kwargs.items():
      player_state = self.get_state(entity_name)
      if LOGGING_DEBUG:
        self.log("Starting streaming on:{} state:{} content:{} params:{}".format(entity_name, player_state, media_content_id, kwargs))
      if player_state == "off":
        self.call_service("media_player/play_media", entity_id=entity_name, media_content_id = media_content_id, media_content_type = "image/jpg")
        self.run_in(self.stop_streaming, self.stream_camera_for_seconds, entity_id=entity_name)

  def stop_streaming(self, kwargs):
    for key, entity_name in kwargs.items():
      if LOGGING_DEBUG:
        self.log("Stopped streaming camera on:{} params:{}".format(entity_name, kwargs))
      self.call_service("media_player/turn_off", entity_id=entity_name)
```

Here is log output from stop_streaming function where it is calling twice: one with correct entity_id and next with bad one! I will rework on this with my limited Python knowledge!

```
2020-01-30 15:31:31.018014 INFO IPCameras: Stopped streaming camera on:thread-25 params:{'entity_id': 'media_player.media_display', '__thread_id': 'thread-25'}
2020-01-30 15:31:31.009374 INFO IPCameras: Stopped streaming camera on:media_player.media_display params:{'entity_id': 'media_player.media_display', '__thread_id': 'thread-25'}
```

**Comment by ReneTode** [comment]
yeah thats a bad callback.

this would be enough:
```
  def stop_streaming(self, kwargs):
      self.call_service("media_player/turn_off", entity_id=kwargs["entity_name"])
```

**Comment by scadaguru** [comment]
@ReneTode Appreciate your help, thank you so much.
I will close the issue as it is not an issue for AppDaemon.
Thanks one more time!
