### ISSUE TITLE
Req. for docs clarification

### ISSUE THREAD

**Issue by Flurkmark** [home-assistant/appdaemon#868]
Hi all. 

It was not clear to me that the admin interface depends on `api:` 
Perhaps this could be noted clearly in the docs. 

Have a nice weekend.

**Comment by ReneTode** [comment]
hi @Flurkmark 

it was never intended to be depended on each other. thats why its not in the docs.
it will be fixed one way or the other.

**Comment by Flurkmark** [comment]
@ReneTode Ah, thanks for the reply, closing issue.
