### ISSUE TITLE
RuntimeError: File descriptor 19 is used by transport

### ISSUE THREAD

**Issue by fabianonline** [home-assistant/appdaemon#87]
Hi.

I just noticed AppDaemon (especially my Dashboard) was not responding anymore. A quick look into the logfiles revealed lots and lots of following error messages:

```
Exception in callback SendfilePayloadWriter._sendfile_cb(<Future cancelled>, 19, 18, 123080, 6508, <_UnixSelecto...e debug=False>, True)
handle: <Handle SendfilePayloadWriter._sendfile_cb(<Future cancelled>, 19, 18, 123080, 6508, <_UnixSelecto...e debug=False>, True)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_fileresponse.py", line 38, in _sendfile_cb
    loop.remove_writer(out_fd)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 351, in remove_writer
    self._ensure_fd_no_transport(fd)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
    fd, transport))
RuntimeError: File descriptor 19 is used by transport <_SelectorSocketTransport fd=19 read=polling write=<polling, bufsize=0>>
Exception in callback SendfilePayloadWriter._sendfile_cb(<Future cancelled>, 14, 13, 27512, 493202, <_UnixSelecto...e debug=False>, True)
handle: <Handle SendfilePayloadWriter._sendfile_cb(<Future cancelled>, 14, 13, 27512, 493202, <_UnixSelecto...e debug=False>, True)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_fileresponse.py", line 38, in _sendfile_cb
    loop.remove_writer(out_fd)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 351, in remove_writer
    self._ensure_fd_no_transport(fd)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
    fd, transport))
RuntimeError: File descriptor 14 is used by transport <_SelectorSocketTransport fd=14 read=polling write=<polling, bufsize=0>>
Exception in callback SendfilePayloadWriter._sendfile_cb(<Future cancelled>, 21, 20, 27512, 9814, <_UnixSelecto...e debug=False>, True)
handle: <Handle SendfilePayloadWriter._sendfile_cb(<Future cancelled>, 21, 20, 27512, 9814, <_UnixSelecto...e debug=False>, True)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_fileresponse.py", line 38, in _sendfile_cb
    loop.remove_writer(out_fd)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 351, in remove_writer
    self._ensure_fd_no_transport(fd)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
    fd, transport))
RuntimeError: File descriptor 21 is used by transport <_SelectorSocketTransport fd=21 read=polling write=<polling, bufsize=0>>
```

They came as fast as my server could generate them. Far too many to scroll back to find the first exception of this kind.

AppDaemon version is eb9e47d + the changes from PR #85 (which didn't touch anything in that area and thus should be innocent).

**Comment by acockburn** [comment]
I haven't seen that before but I haven't been testing on 3.6 (yet).

The error though is not anywhere in my code as far as I can see from the stack trace, it looks like an aiohttp issue - what version do you have? I wonder if you might need to upgrade to work with python 3.6.

**Comment by acockburn** [comment]
Closing die to lack of response. Happy to re-open if you can let me have the additional information I requested.

**Comment by matkor** [comment]
I encountered (if I can tell) similar issue. hass was busy producing exceptions :
[ha-loop_exceptions_log.txt](https://github.com/home-assistant/appdaemon/files/1733561/ha-loop_exceptions_log.txt)
I to was also performing sluggish: response to simple actions was noticable slower than usually in web browser.

Running on Raspbery Pi B/raspbian:
HA git checkout:
commit 5995c2f3133bb65e14b430ac17561c9425d41dd4
Date:   Tue Feb 13 22:03:56 2018 +0200
SMA sensor add SSL and upgrade to pysma 0.2 (#12354)

 matkor@raspberrypi3:~ $ dpkg -s python3 | grep Version
Version: 3.5.3-1

 (home-assistant) matkor@raspberrypi3:~/src/home-assistant $ pip freeze
aiohttp==2.3.10
aiohttp-cors==0.6.0
astral==1.5
async-timeout==2.0.0
attrs==17.4.0
boto3==1.5.27
botocore==1.8.41
certifi==2018.1.18
chardet==3.0.4
colorlog==3.1.2
distro==1.2.0
docutils==0.14
ecdsa==0.13
envs==1.2.4
future==0.16.0
gTTS-token==1.1.1
home-assistant-frontend==20180211.0
-e git+https://github.com/matkor/home-assistant.git@5995c2f3133bb65e14b430ac17561c9425d41dd4#egg=homeassistant
idna==2.6
idna-ssl==1.0.0
Jinja2==2.10
jmespath==0.9.3
MarkupSafe==1.0
multidict==4.1.0
mutagen==1.40.0
pkg-resources==0.0.0
pluggy==0.6.0
py==1.5.2
pycryptodome==3.3.1
python-dateutil==2.6.1
python-jose-cryptodome==1.3.2
pytz==2018.3
PyYAML==3.12
requests==2.18.4
RPi.GPIO==0.6.1
s3transfer==0.1.12
six==1.11.0
SQLAlchemy==1.2.2
tox==2.9.1
typing==3.6.4
ua-parser==0.7.3
urllib3==1.22
user-agents==1.1.0
virtualenv==15.1.0
voluptuous==0.10.5
warrant==0.6.1
xmltodict==0.11.0
yarl==1.1.0

**Comment by rotcop4u2** [comment]
I have the same exact issue on my RPI 3B+, except its descriptor 12. I have been trying to figure out how to stop it. At first I thought it seemed random, but it seems like it happens when I am in the IP/port of my appdaemon dashboard and then close out. It also happens when I am in my HA IP/port and close out without logging off. I wonder if the system doesn't recognize that the webresponse client is not longer attached when it goes to feed data to it so it starts erroring. I am not sure how to correct that. It has happened to me so bad one time I was forced to restart my RPI.

**Comment by rotcop4u2** [comment]
I believe I found the issue. I need a couple more days to verify that the error will not happen again. and will comment back to confirm or deny fix.

**Comment by rotcop4u2** [comment]
The issue was not resolved. It seems to happen more so with I log into the HA Dashboard or into Home Assistant. The error will randomly populate again after selecting new dash panels from my bottom_panel.yaml attached to all of me Dash files
