### ISSUE TITLE
Option To Fetch Latitude / Longitude / Elevation and TimeZone From HA or Environment Variables

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [home-assistant/appdaemon#875]
Hi,

I can see in my log files that AppDaemon is now looking for some new parameters (Latitude, Longitude, Elevation and TimeZone) in its configuration file.

It would be beneficial if there was an option to pull these values directly from HA via the following API endpoint:

[Home Assistant Get Config](https://developers.home-assistant.io/docs/en/external_api_rest.html#get-apiconfig)

This will allow for AppDaemon and HomeAssistant to stay in-sync.

Further to this, it would also be beneficial if the parameters could be set / overridden via Environment Variables so that these can be set in Docker Containers, etc.

Apologies if this functionality already exists - I couldn't find it in the documentation..

**Comment by Odianosen25** [comment]
Hello @danieledwardgeorgehitchcock,

The reason it wouldn’t be possible to get these values from HA, is that now AD’s internal schedulers are started before the plying, and dependent  on these values. So if we have the option to get it from HA as was the case before, it just wouldn’t be feasible at the moment.

We can look into the environment variables, but what level do you want to be able to set? The config in appdaemon.yaml?

Regards

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks for the quick reply!

Yes I see the Environment Variables being applied at the config level in appdaemon.yaml or maybe being able to reference them in a similar way to HomeAssistant:

[Home Assistant Environment Variables](https://www.home-assistant.io/docs/configuration/yaml/#environmental-variables)

**Comment by Odianosen25** [comment]
Ok no worries, we will see what we can do, but at this time honestly no promises. Will discuss it with the other devs especially @acockburn, and see what we can come up with.

Regards

**Comment by Odianosen25** [comment]
@danieledwardgeorgehitchcock,

This is now in dev, please check it out and let us know if further stuffs needed
