### ISSUE TITLE
after install appdaemon.yaml default file has something different that instructions say to use. 

### ISSUE THREAD

**Issue by stovedoctor** [home-assistant/appdaemon#879]
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

**Comment by Odianosen25** [comment]
Hello @stovedoctor,

What do you mean by this issue pls?

**Comment by stovedoctor** [comment]
I was looking at a old config setup.😒☹️
All good 
Just had to update
Location 
And url to my system.
