### ISSUE TITLE
AppDaemon delete state from Hass

### ISSUE THREAD

**Issue by panagorn** [home-assistant/appdaemon#892]
Hello,

I am creating custom sensors for hass with set_state. I am using  self.remove_entity(entity_id) to delete the entity i created and its removed from AD, however I still see the entity when i open HA and go to developer tools under states.

To workaround this I am doing a DELETE API call from AD when i remove the entity to http://myhass:8123/api/states/entity_id to also remove the entity there. Everything works as expected, however when I try to do set_state from AD for the same entity_id (to recreate the entity) It gives me the below error:

`  File "/usr/lib/python3.8/site-packages/appdaemon/http.py", line 744, in call_api
    ret, code = await self.dispatch_app_by_name(app, args)
  File "/usr/lib/python3.8/site-packages/appdaemon/http.py", line 786, in dispatch_app_by_name
    return await utils.run_in_executor(self, callback, args)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/occasion/occasion.py", line 150, in _add_occasion
    self._helper_save_occasion(occasion, True)
  File "/config/appdaemon/apps/occasion/occasion.py", line 155, in _helper_save_occasion
    self.set_state(occasion.entity_id(), state=occasion.state(
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 1360, in set_state
    return await self.AD.state.set_state(self.name, namespace, entity_id, **kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 416, in set_state
    new_state = self.parse_state(entity_id, namespace, **kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 368, in parse_state
    new_state["state"] = kwargs["state"]
TypeError: 'NoneType' object does not support item assignment`

Do you know why it cannot recreate the entity (it looks like AD new_state is invalid or something)? Is there any option to delete the entity from AD and Hass when we do  `self.remove_entity(entity_id)`?

**Comment by ReneTode** [comment]
remove_entity is for internal entities.
thats why it doesnt work on HA entities.

HA has the option in newer versions to delete an entity, but if an entity is deleted you can add that same entity again untill you restart HA.

so the best thing is to leave HA entities that are created by HA as they were. dont try to delete them.
if you made a mistake in naming or such things then just restart HA and all entities created by AD dissapear untill you recreate them

**Comment by panagorn** [comment]
Thank you for the update @ReneTode,

The entities i am using are just virtual sensors (not an actual sensor) and i made some api calls to update the data and then i use set_state to create/update the state/sensor.

If I use the hass API to set state/create an entity:
`curl -X POST -H "Authorization: Bearer token" \
       -H "Content-Type: application/json" http://myhass:8123/api/states/myoccasion.test -d '{"state": "below_horizon","attributes": {"next_rising":"2016-05-31T03:39:14+00:00"}}'
{"attributes": {"next_rising": "2016-05-31T03:39:14+00:00"}, "context": {"id": "3fb338cb7fe04462b4ef4a322fb37475", "parent_id": null, "user_id": "5b78d1dfff884e6fb378bdbf75e31a07"}, "entity_id": "myoccasion.test", "last_changed": "2020-02-23T13:23:16.980053+00:00", "last_updated": "2020-02-23T13:23:16.980053+00:00", "state": "below_horizon"}%`

Then delete the state:
`curl -X DELETE -H "Authorization: Bearer  token" \
       -H "Content-Type: application/json" http://myhass:8123/api/states/myoccasion.test
{"message": "Entity removed."}%`

And then create it again it works as expected with no issues. So it looks like HA allows you to set the state, delete it and then set it again with no issues. So this is what i am trying to achieve with AD the same way i explained with API. I do set_state (create state if it does not exist) then i do a delete with an api call and then i use set_state (with AD) and this is what is failing. I am not sure if AD keeps something internal that prevents the set_state to fail if i delete the state from the API but HA allows you to set the state, delete it and then set it again through the API.

**Comment by ReneTode** [comment]
if you delete it with an api call then it still exists in the plugin.
so you probably would need:

set_state to create

delete with api call AND delete with remove_entity() afterwards at this moment.

we were not aware that the deletion from HA entities now is correctly working.
so ill as @Odianosen25 if he will make the remove_entity() function work correct with the hass plugin.

**Comment by panagorn** [comment]
Hello @ReneTode,

I am doing both delete with API and remove_entity() and the error happens after i do set_state() again. Probably something remains/undeleted or unchecked somewhere. It would be nice if remove_entity() can be updated to make a delete api call to HA and remove the state. That would avoid the need of restarting HA. 

I am doing a custom panel for HA to dynamically create transport entities based on the bus stops i am interested. I have a functionality to add remove/entities by making an API call to AD app for bus stops and also creating custom alarms and manage them with an interface instead of yaml Configuration.

Thank you

**Comment by ReneTode** [comment]
i think that creating and deleting entities for such a goal isnt the best way.
its better just to create the entities once, and let them show and hide, if necesary with different friendly names.

but the remove_entity will be updated.

**Comment by panagorn** [comment]
Thank you. I will be waiting for the update

**Comment by Odianosen25** [comment]
@panagorn trying to add this feature, but can't find an official api call for deleting entities on HA. Can you assist with this please?

Regards

**Comment by panagorn** [comment]
Hello @Odianosen25,

I didn't get that from any official doc but i found that here [here](https://community.home-assistant.io/t/its-easy-to-create-http-binary-sensor-how-to-delete-one/7892/4)

I am using requests and my code looks like this and it works with no errors so it looks like HA can handle delete requests with no issues and i do not need to restart HA.
```python
def remove_entity_from_hass(self, entity_id):    
  _url = globals.get_secret("secret_hass_url").format(
      f'api/states/{entity_id}')
  headers = {"Content-Type": "application/json",
             "Authorization": "Bearer {}".format(globals.get_secret("secret_token"))}
  try:
      response = requests.delete(_url, headers=headers)
      self.logger.info('Delete API -- Response: %s Code: %s' %
                       (response.json(), response.status_code))
      return response
  except requests.exceptions.RequestException as e:
      raise
```

**Comment by panagorn** [comment]
I check the API and I found the delete handler [here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/api/__init__.py#L261)

**Comment by Odianosen25** [comment]
@panagorn ok the PR has been put in for this, once in you can remove an entity in hass using the standard api call `remove_entity` and it will also remove the entity from hass. As long as you working within the right namespace

**Comment by panagorn** [comment]
Thank you, we can close this now.
