### ISSUE TITLE
AppDaemon doesn't seem to install correctly

### ISSUE THREAD

**Issue by DoughnutWuff** [home-assistant/appdaemon#893]
Installing via PIP3, all goes well until you try and find the conf folder. Nowhere to be found, and the documentation doesn't say anything about creating folders, it just says to run `appdaemon -c /home/homeassistant/conf`

Manually made a folder with the apps folder and everything, goes to run:
![image](https://user-images.githubusercontent.com/22278710/75186973-f0efeb00-5740-11ea-8942-725ecbbff4bf.png)

I've given up, AppDaemon's documentation seems to have changed and a lot is missing from it. 
As it stands, I cannot even get it to run anymore, I get no output, even with `-D DEBUG` on the end.

Any ideas?

**Comment by ReneTode** [comment]
in the docs:
>-c is the path to the configuration directory. If not specified, AppDaemon will look for a file named appdaemon.cfg first in ~/.homeassistant then in /etc/appdaemon. If the directory is not specified and it is not found in either location, AppDaemon will raise an exception. In addition, AppDaemon expects to find a dir named apps immediately subordinate to the config directory.

the .cfg file is wrong (should be .yaml nowadays, is noted that it should be changed)

and how to configure appdaemon.yaml can be found in the section configuration:
https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html

**Comment by ttimasdf** [comment]
Add the following inside your `appdaemon.yaml`, all of the four settings are required for AD to startup. The latitude, longitude could be retrived from HA developer settings under entity `home.home`

```yaml
appdaemon:
  time_zone: Asia/Hong_Kong
  latitude: 1234
  longitude: 1234
  elevation: 123
```

**Comment by acockburn** [comment]
We decided a while ago to make these variables part of ADs configs as some users don;t use AD with HASS.
