### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by schettada** [home-assistant/appdaemon#93]
Got the below error while trying to install the appdaemon. its not going forward from this point.

HypriotOS/armv6: root@hadash in ~
$ docker run --rm -it -p 5050:5050 \
>   -e HA_URL="https://rigel.schettada.net" \
>   -e HA_KEY="Musafir@85" \
>   -e DASH_URL="http://$HOSTNAME:5050" \
>   acockburn/appdaemon:latest
Unable to find image 'acockburn/appdaemon:latest' locally
latest: Pulling from acockburn/appdaemon
9f0706ba7422: Pull complete 
d3942a742d22: Pull complete 
c6575234aef3: Pull complete 
8af5f3519ed2: Pull complete 
27868e2bc876: Pull complete 
950451fe7eeb: Pull complete 
14a848c2c9be: Pull complete 
32ee9ba90ac2: Pull complete 
166fc66a108a: Pull complete 
7089a6f6cbd2: Pull complete 
3f002f8c3e28: Pull complete 
82f49033cf46: Pull complete 
Digest: sha256:42487de40281a7f2fe92827a65f2bfe5330c33d6bc6e235bb0241185a5ae63bc
Status: Downloaded newer image for acockburn/appdaemon:latest
standard_init_linux.go:178: exec user process caused "exec format error"
HypriotOS/armv6: root@hadash in ~
$ docker run --rm -it -p 5050:5050   -e HA_URL="https://rigel.schettada.net"   -e HA_KEY="Musafir@85"   -e DASH_URL="http://$HOSTNAME:5050"   acockburn/appdaemon:latest
standard_init_linux.go:178: exec user process caused "exec format error"

HypriotOS/armv6: root@hadash in ~
$ docker -v
Docker version 17.05.0-ce, build 89658be
HypriotOS/armv6: root@hadash in ~
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 4.4.50-hypriotos+
Operating System: Raspbian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv6l
CPUs: 1
Total Memory: 370.6MiB
Name: hadash
ID: MR4H:N4EZ:MM7G:6QWO:DJPU:TQKM:2DQ3:VHS5:5KRC:ULBN:FBXX:LPFQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

HypriotOS/armv6: root@hadash in ~
$

**Comment by acockburn** [comment]
Looks like you are trying to run on a PI - unfortunately the docker image on the hub doesn't support that - I'll add some instructions on docker support for PI soon, you will need to build your own image.

**Comment by schettada** [comment]
Thanks for the reply. I'll wait for the new instructions. Do you think I can install this in a Mac?

Sent from my iPhone

On Jul 22, 2017, at 05:28, Andrew Cockburn <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like you are trying to run on a PI - unfortunately the docker image on the hub doesn't support that - I'll add some instructions on docker support for PI soon, you will need to build your own image.

**Comment by acockburn** [comment]
Not 100% sure - the docker hub image *may* work on a mac - if you give it a try let me know how it works out!

**Comment by schettada** [comment]
Ok! i'll wait for the instructions for RPI. Thank you for the reply. Trying from long time to install HADashboard.


Thanks,

Sooraj


________________________________

**Comment by schettada** [comment]
Just to Update! I was able to run it on a mac without any issues.


OS: MacOS Sierra

Model: Mac Mini 2014


________________________________

**Comment by acockburn** [comment]
Cool - thanks for the update! I'll make a note that the docker image works on MAC and I'll add instructions for the PI as I said.

Thanks for trying it out!
