### ISSUE TITLE
remove_entity

### ISSUE THREAD

**Issue by hmmkash** [home-assistant/appdaemon#948]
Hi, will remove_entity() be able to delete entities from HA? when will the 4.0.4 release will be available, because with ver. 4.0.3 does only removes from AD dbase.
Thanks

**Comment by Odianosen25** [comment]
@hmmkash,

Yes in 4.0.4 it will be able to remove the entity in HA.

Regards

**Comment by hmmkash** [comment]
Thanks!! when will be available to upgrade?

**Comment by Odianosen25** [comment]
@hmmkash,  

Unfortunately I can’t answer that now but only @acockburn. Due to the drama going on around the world right now, I would think will be a while.

Regards

**Comment by hmmkash** [comment]
Hello and thank you for answering,
Is there is a Way That i can use someof those files in the go to be able to use the remove _entity even though for restinga? Just want this option  so I will be able to delete entities from Ha.
Thank you very much

**Comment by Odianosen25** [comment]
Hello @hmmkash,

Unfortunately not. The only way to access it now as far as I know is to use the dev version of AD. 

Regards

**Comment by hmmkash** [comment]
Thank you, I will try to upgrade manually and see.

**Comment by Odianosen25** [comment]
PR submitted for this #847, so closing for now
