### ISSUE TITLE
run_daily doesnt use new summertime

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#951]
today the summertime has started, but all run_daily callbacks still run in wintertime.

minor issue, that can be fixed by restarting AD, but i thought it was worth mentioning.
running dev version from 25 februar.

**Comment by dlashua** [comment]
I believe this is fixed in latest dev (as of 2 days ago). @acockburn can confirm.

**Comment by ReneTode** [comment]
found it.
i missed that one.
thx.

**Comment by acockburn** [comment]
This was caused because you didn’t like it when DST forced a restart of all apps :) The fix in dev is not 100% there yet I have a couple of issues to work through but it will be working in the next full release - keep an eye on commits if you want to keep your branch up to date

**Comment by ReneTode** [comment]
yeah i check regularly what commits are there and if i can use them.

restart app causes that running schedules are lost. so i dont think i would have been the only one who would have objected ;)

by the way, because i noticed some valuable changes, i did go to latest dev from today. (saved my own changes and will implement those later on.)
but the AI now keeps old schedulars listed. is that a known issue?
