### ISSUE TITLE
self.toggle("switch.lamp") blocks HA-log and app indefinitely

### ISSUE THREAD

**Issue by dekiesel** [home-assistant/appdaemon#956]
Appdaemon 4.0.4

I have a switch "switch.lamp" that I toggle with my TV remote via a mysensors-sensor.

Running 

self.toggle("switch.lamp")

freezes the logfile, no new loglines are shown when I send other IR codes and the appdaemon-app doesn't react. Restarting appdaemon isn't enough, I have to restart HA too, though HA is responsive in the web-GUI.

Running 

self.call_service("switch/toggle", entity_id="switch.lamp")

on the other hand works as expected and doesn't block.

The app is quite long, please let me know if you want the whole thing anyway. The logfile contains no loglines after issuing the command, so I have nothing to paste here.

**Comment by dekiesel** [comment]
Please close this issue, it also happens with the service call, just less frequently, I will need to debug this further.

**Comment by Odianosen25** [comment]
@dekiesel you close it and let us know how it goes. Regards
