### ISSUE TITLE
Dashboard Namespace Bug

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#978]
When a sequence widget is used with at the bottom of a dashboard, for some reasons it overrides the namespace for all service calls within that dashboard. This is not the case when its at the top of the dashboard page.

**Comment by acockburn** [comment]
Can you re-test with the current dev - I made a fix in this area.

**Comment by Odianosen25** [comment]
Ok boss will back to you on it

**Comment by Odianosen25** [comment]
This has been fixed boss @acockburn
