### ISSUE TITLE
Presence Architecture in 4.0.4: noone_home not working correctly

### ISSUE THREAD

**Issue by neographikal** [home-assistant/appdaemon#980]
Okay, since the current implementation in the stable channel didn't make sense I got the dev image from Docker Hub and tested it where the new Presence architecture should be present. I have two persons in HomeAssistant and the following code:

```
import hassapi as hass

class AlarmManager(hass.Hass):
  def initialize(self):
    self.listen_state(self.event, "person.inge")
    self.listen_state(self.event, "person.neo")

  def event(self, entity, attribute, old, new, kwargs):
    self.log("Person" + entity + " new state: " +new)
    if self.noone_home():
      self.set_state("input_boolean.alarm", state="on")
      self.log("No one home - setting alarm to on")
    if self.anyone_home():
      self.set_state("input_boolean.alarm", state="off")
      self.log("Anyone home - setting alarm to off")
```
The if self.noone_home(): is never hit. Confirmed both entities reporting not_home in HA.

**Comment by Odianosen25** [comment]
@neographikal to use person and not device tracker in the self.noon_home(), pass thru parameter `person=True` In it. So your function should be `self.noon_home(person=True)`.

Regards

**Comment by neographikal** [comment]
Thanks, will try that. If I encounter a bug I'll report it :)
