### ISSUE TITLE
Another FA Pro question

### ISSUE THREAD

**Issue by ACJUK** [home-assistant/appdaemon#985]
I've got a Pro account with FA and I'm trying to use some of their icons.

I need to use:

far fa-lamp
fas fa-lamp

If I enter those into my dash file and then inspect the code in the browser I get:

```class="far fa fa-lamp"```

and

```class="fas fa fa-lamp"```

So the icons don't actually work.  Well, the icon is the solid one (fas) but it doesn't change when I turn the light on and off even though the code changes.

Any ideas on how to fix?

**Comment by ReneTode** [comment]
i am afraid that there needs to be some rewriting from dashboard to enable that.thats because it was written with older versions from FA.
and rewriting wasnt needed for the free icons.

**Comment by ACJUK** [comment]
Ok.  I saw a post (https://github.com/home-assistant/appdaemon/issues/211) that said you could do this by using ```/img/myicon.png```

I'm guessing that is probably the only option.  So if I convert the SVG files to PNG and upload them into my img directory then that will work?

**Comment by ACJUK** [comment]
Nope.  Can't make that work.

If someone could point me at the file that adds in the "fa" then I'm happy to edit a bit of html or Javascript to fudge this.

**Comment by ACJUK** [comment]
Yay!  So simple!

This is one I'm trying to use:

https://fontawesome.com/icons/light-ceiling?style=solid

This is my .dash:

```
utility_button:
    widget_type: switch
    title: Utility
    entity: light.utility
    icon_on: fas-light-ceiling
    icon_off: far-light-ceiling
```

I've tried with a few different icons including fad, fas and far.  

So, if FA says:

```fas fa-light-ceiling```

Just replace the fa with fas and it works.

Having spend $99, I was determined to find a way round this.

**Comment by ReneTode** [comment]
great that you found a way.
i guess thats maybe because of the fact that AD also uses MDI, but it can also be a FA problem.

i hope you realise that its 99 a year, not just 1 time?

**Comment by ACJUK** [comment]
Yeah, I'm a UX consultant for a living and spend my days building and testing user interfaces for digital products.  This will be a nice addition to my collection of tools.
