### ISSUE TITLE
app_init_delay

### ISSUE THREAD

**Issue by thomasdelaet** [home-assistant/appdaemon#988]
Hey,

I think the app_init_delay option for the hass plugin is not working. I can find it in the documentation but not in the code anymore + it also doesn't seem to do anything when I add it to my configuration.

Is there a reason for this? For me this would be useful to have since it would make sure that after (re)connect to home assistant, apps only get initialized when I'm sure all entities are available.

Thanks!

Thomas

**Comment by ReneTode** [comment]
in the docs it points to 
https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html?highlight=app_init_delay#hass-plugin-startup-conditions

which should work.

i guess the line about app_init_delay should be removed.

**Comment by thomasdelaet** [comment]
Thanks! That should work.
