### ISSUE TITLE
umlauts getting lost when fetching data from Home Assistant

### ISSUE THREAD

**Issue by prankousky** [home-assistant/appdaemon#990]
Hi,

I am trying to grab `media_artist` and `media_album_name` from an `mpd` entity within Home Assistant.

![grafik](https://user-images.githubusercontent.com/11297070/83973160-d81cd700-a8e4-11ea-8aaa-2b3b1b764ba3.png)

As you can see, the artist name is `Die Ärzte`, with the German Umlaut `Ä`. I am trying to write an AppDaemon app to fetch the appropriate album cover via `last.fm` API, which requires me to pass on the artist and album name.

However, when I try using this (test case is `self.log(artist_name)`), I get something like `Die <?><?>rzte`. The two question marks are within a box, but I cannot copy and paste the exact output at the moment. So it's not bracket, question mark, bracket, but some weird symbol character.

This will also happen when I `self.log("Die Ärzte")`, so I don't think the problem is fetching the data from Home Assistant, but rather some general issue working with characters like these. Is there something I have to do in order to enable encoding?

I searched the docs for `encoding` and `umlaut`, but didn't find anything that helps me solve this issue.

Thank you for you reply :)

**Comment by ReneTode** [comment]
its only in the logeditor that you use.
the problem isnt in AD, but in the editor.

if you use:
self.set_state("sensor.artist_name", state = "Die Ärtze")
a sensor gets created and that sensor shows that the value is correct.

**Comment by prankousky** [comment]
Perfect, thank you.
