### ISSUE TITLE
Non-app dependencies - documentation

### ISSUE THREAD

**Issue by Oekn5w** [home-assistant/appdaemon#997]
By now, going from the docs and the logged behavior, dependencies are only recognized, if the module is part of another app.
From my point of view, we should also be able to depend on modules, that are not an app.

Use cases:
* Splitting the code for one app to multiple files for readability
* Writing a standalone class that is reused by multiple apps (e.g. some special timer)

Parsing the imports is not really necessary, but writing the modules to the deps would be a great way to implement this, especially since the deps already take module names.

Current behaviour:

`apps.yaml`
```
light_control:
  module: lights
  class: Lights
  dependencies: hPwrBtn
```

leads to this in the log:
```
2020-06-28 10:32:33.166900 INFO AppDaemon: Reloading Module: /conf/apps/hPwrBtn.py
2020-06-28 10:32:33.167446 WARNING AppDaemon: No app description found for: hPwrBtn - ignoring
...
2020-06-28 10:34:45.638392 INFO AppDaemon: Calling terminate() for light_control
2020-06-28 10:34:45.639911 WARNING AppDaemon: Unable to find app hPwrBtn in dependencies for light_control
2020-06-28 10:34:45.640008 WARNING AppDaemon: Ignoring app light_control
2020-06-28 10:34:45.640127 INFO AppDaemon: Initializing app light_control using class Lights from module lights
```

**Comment by Odianosen25** [comment]
@Oekn5w,

What you asking for  already possible in AD. When you develop the class in a module, once AD imports all the python modules, anyone can be used in any app.

Now if you want it to be used as a dependency, then in one of the `apps.yaml` configuration, declare `global_modules`.  So should be:
```
global_modules:
    hPwrBtn
```

If not wanting to go via the yaml to declare the dependencies, then use the `depends_on_module` api, and it should all work.

Regards

**Comment by Oekn5w** [comment]
@Odianosen25 thank you, that's what I wanted. Is there an update prepared for the documentation? I didn't find anything about global modules there. It only covers app deps

**Comment by Oekn5w** [comment]
Nevermind, I had an older documentation selected *faceplam*
